import type { INodeProperties } from 'n8n-workflow';

export const catalogOperations: INodeProperties[] = [

	{
		displayName: 'Operation',
		noDataExpression: true,
		name: 'operation',
		type: 'options',
		options: [
			{ name: 'Add Variant (Existing Catalog)', value: 'addVariant', action: 'Add a new variant' },
			{ name: 'Create Catalog', value: 'createCatalog', action: 'Create a catalog' },
			{ name: 'Get All Catalogs', value: 'getAllCatalogs', action: 'Get all catalogs' },
			{ name: 'Get Catalog', value: 'getCatalog', action: 'Get a catalog' },
			{ name: 'Update Catalog', value: 'updateCatalog', action: 'Update a catalog' },
			{ name: 'Update Variant (Existing Catalog)', value: 'updateVariant', action: 'Update a variant' },
		],
		default: 'createCatalog',
		displayOptions: {
			show: { resource: ['catalog'] },
		},
		description: 'Choose the operation',
	},

	{
		displayName: 'Catalog ID',
		name: 'catalogId',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				operation: ['getCatalog', 'updateCatalog','updateVariant', 'addVariant'],
			},
		},
	},

	{
		displayName: 'Catalog Name',
		name: 'catalogName',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['catalog'],
				operation: ['createCatalog'],
			},
		},
	},

	{
		displayName: 'Price',
		name: 'price',
		type: 'string',
		required: true,
		default: '',
		placeholder: '',
		displayOptions: {
			show: {
				resource: ['catalog'],
				operation: ['createCatalog'],
			},
		},
	},
	{
		displayName: 'Catalog Type',
		name: 'catalog_type',
		type: 'options',
		options: [
			{ name: 'Sales', value: 'sales' },
			{ name: 'Purchase', value: 'purchase' },
		],
		default: 'sales',
		displayOptions: {
			show: {
				operation: ['createCatalog'],
			},
		},
	},

	{
		displayName: 'Item Type',
		name: 'item_type',
		type: 'options',
		options: [
			{ name: 'Goods', value: 'goods' },
			{ name: 'Services', value: 'services' },
		],
		default: 'goods',
		displayOptions: {
			show: {
				resource: ['catalog'],
				operation: ['createCatalog'],
			},
		}
	},

	// {
	// 	displayName: 'HSN/SAC Code Name or ID',
	// 	name: 'hsn_sac_mode',
	// 	type: 'options',
	// 	typeOptions: {
	// 		loadOptionsMethod: 'getHsnSacCodes',  // Matches the loadOptions method in Ledgers.node.ts
	// 		allowManualEntry: true,  // 👈 this allows users to enter a custom value
	// 	},
	// 	required: true,
	// 	displayOptions: {
	// 		show: {
	// 			resource: ['catalog'],
	// 			operation: ['createCatalog', 'updateCatalog'],
	// 			loadOptionsDependsOn: ['catalogName'],  // 👈 This line ensures the API call waits until Catalog Name is filled
	// 		},
	// 	},
	// 	description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	// 	default: '',
	// 	placeholder: 'Select HSN/SAC Code',
	// },

	// {
	// 	displayName: 'HSN/SAC Code (Manual)',
	// 	name: 'hsn_sac_manual',
	// 	type: 'string',
	// 	default: '',
	// 	placeholder: 'Enter HSN/SAC Code',
	// 	displayOptions: {
	// 		show: {
	// 			resource: ['catalog'],
	// 			operation: ['createCatalog', 'updateCatalog'],
	// 			hsn_sac_mode: ['manualEntry'],
	// 		},
	// 	},
	// },

	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['catalog'],
				operation: ['createCatalog'],
			},
		},
		// eslint-disable-next-line n8n-nodes-base/node-param-collection-type-unsorted-items
		options: [
			{
        displayName: 'Currency', name: 'currency', type: 'options',
				options: [
					{ name: 'AED - UAE Dirham', value: 'AED' },
					{ name: 'AFN - Afghan Afghani', value: 'AFN' },
					{ name: 'ALL - Albanian Lek', value: 'ALL' },
					{ name: 'AMD - Armenian Dram', value: 'AMD' },
					{ name: 'ANG - Netherlands Antillean Guilder', value: 'ANG' },
					{ name: 'AOA - Angolan Kwanza', value: 'AOA' },
					{ name: 'ARS - Argentine Peso', value: 'ARS' },
					{ name: 'AUD - Australian Dollar', value: 'AUD' },
					{ name: 'AWG - Aruban Florin', value: 'AWG' },
					{ name: 'AZN - Azerbaijani Manat', value: 'AZN' },
					{ name: 'BAM - Bosnia and Herzegovina Convertible Mark', value: 'BAM' },
					{ name: 'BBD - Barbadian Dollar', value: 'BBD' },
					{ name: 'BDT - Bangladeshi Taka', value: 'BDT' },
					{ name: 'BGN - Bulgarian Lev', value: 'BGN' },
					{ name: 'BHD - Bahraini Dinar', value: 'BHD' },
					{ name: 'BIF - Burundian Franc', value: 'BIF' },
					{ name: 'BMD - Bermudian Dollar', value: 'BMD' },
					{ name: 'BND - Brunei Dollar', value: 'BND' },
					{ name: 'BOB - Bolivian Boliviano', value: 'BOB' },
					{ name: 'BRL - Brazilian Real', value: 'BRL' },
					{ name: 'BSD - Bahamian Dollar', value: 'BSD' },
					{ name: 'BTN - Bhutanese Ngultrum', value: 'BTN' },
					{ name: 'BWP - Botswana Pula', value: 'BWP' },
					{ name: 'BYN - Belarusian Ruble', value: 'BYN' },
					{ name: 'BZD - Belize Dollar', value: 'BZD' },
					{ name: 'CAD - Canadian Dollar', value: 'CAD' },
					{ name: 'CDF - Congolese Franc', value: 'CDF' },
					{ name: 'CHF - Swiss Franc', value: 'CHF' },
					{ name: 'CLF - Unidad De Fomento', value: 'CLF' },
					{ name: 'CLP - Chilean Peso', value: 'CLP' },
					{ name: 'CNY - Chinese Yuan', value: 'CNY' },
					{ name: 'COP - Colombian Peso', value: 'COP' },
					{ name: 'CRC - Costa Rican Colon', value: 'CRC' },
					{ name: 'CUC - Cuban Convertible Peso', value: 'CUC' },
					{ name: 'CUP - Cuban Peso', value: 'CUP' },
					{ name: 'CVE - Cape Verdean Escudo', value: 'CVE' },
					{ name: 'CZK - Czech Koruna', value: 'CZK' },
					{ name: 'DJF - Djiboutian Franc', value: 'DJF' },
					{ name: 'DKK - Danish Krone', value: 'DKK' },
					{ name: 'DOP - Dominican Peso', value: 'DOP' },
					{ name: 'DZD - Algerian Dinar', value: 'DZD' },
					{ name: 'EGP - Egyptian Pound', value: 'EGP' },
					{ name: 'ERN - Eritrean Nakfa', value: 'ERN' },
					{ name: 'ETB - Ethiopian Birr', value: 'ETB' },
					{ name: 'EUR - Euro', value: 'EUR' },
					{ name: 'FJD - Fijian Dollar', value: 'FJD' },
					{ name: 'FKP - Falkland Islands Pound', value: 'FKP' },
					{ name: 'GBP - British Pound', value: 'GBP' },
					{ name: 'GEL - Georgian Lari', value: 'GEL' },
					{ name: 'GHS - Ghanaian Cedi', value: 'GHS' },
					{ name: 'GIP - Gibraltar Pound', value: 'GIP' },
					{ name: 'GMD - Gambian Dalasi', value: 'GMD' },
					{ name: 'GNF - Guinean Franc', value: 'GNF' },
					{ name: 'GTQ - Guatemalan Quetzal', value: 'GTQ' },
					{ name: 'GYD - Guyanese Dollar', value: 'GYD' },
					{ name: 'HKD - Hong Kong Dollar', value: 'HKD' },
					{ name: 'HNL - Honduran Lempira', value: 'HNL' },
					{ name: 'HRK - Croatian Kuna', value: 'HRK' },
					{ name: 'HTG - Haitian Gourde', value: 'HTG' },
					{ name: 'HUF - Hungarian Forint', value: 'HUF' },
					{ name: 'IDR - Indonesian Rupiah', value: 'IDR' },
					{ name: 'ILS - Israeli New Shekel', value: 'ILS' },
					{ name: 'INR - Indian Rupee', value: 'INR' },
					{ name: 'IQD - Iraqi Dinar', value: 'IQD' },
					{ name: 'IRR - Iranian Rial', value: 'IRR' },
					{ name: 'ISK - Icelandic Króna', value: 'ISK' },
					{ name: 'JMD - Jamaican Dollar', value: 'JMD' },
					{ name: 'JOD - Jordanian Dinar', value: 'JOD' },
					{ name: 'JPY - Japanese Yen', value: 'JPY' },
					{ name: 'KES - Kenyan Shilling', value: 'KES' },
					{ name: 'KGS - Kyrgyzstani Som', value: 'KGS' },
					{ name: 'KHR - Cambodian Riel', value: 'KHR' },
					{ name: 'KMF - Comorian Franc', value: 'KMF' },
					{ name: 'KPW - North Korean Won', value: 'KPW' },
					{ name: 'KRW - South Korean Won', value: 'KRW' },
					{ name: 'KWD - Kuwaiti Dinar', value: 'KWD' },
					{ name: 'KYD - Cayman Islands Dollar', value: 'KYD' },
					{ name: 'KZT - Kazakhstani Tenge', value: 'KZT' },
					{ name: 'LAK - Lao Kip', value: 'LAK' },
					{ name: 'LBP - Lebanese Pound', value: 'LBP' },
					{ name: 'LKR - Sri Lankan Rupee', value: 'LKR' },
					{ name: 'LRD - Liberian Dollar', value: 'LRD' },
					{ name: 'LSL - Lesotho Loti', value: 'LSL' },
					{ name: 'LYD - Libyan Dinar', value: 'LYD' },
					{ name: 'MAD - Moroccan Dirham', value: 'MAD' },
					{ name: 'MDL - Moldovan Leu', value: 'MDL' },
					{ name: 'MGA - Malagasy Ariary', value: 'MGA' },
					{ name: 'MKD - Macedonian Denar', value: 'MKD' },
					{ name: 'MMK - Myanmar Kyat', value: 'MMK' },
					{ name: 'MNT - Mongolian Tugrik', value: 'MNT' },
					{ name: 'MOP - Macanese Pataca', value: 'MOP' },
					{ name: 'MRU - Mauritanian Ouguiya', value: 'MRU' },
					{ name: 'MUR - Mauritian Rupee', value: 'MUR' },
					{ name: 'MVR - Maldivian Rufiyaa', value: 'MVR' },
					{ name: 'MWK - Malawian Kwacha', value: 'MWK' },
					{ name: 'MXN - Mexican Peso', value: 'MXN' },
					{ name: 'MYR - Malaysian Ringgit', value: 'MYR' },
					{ name: 'MZN - Mozambican Metical', value: 'MZN' },
					{ name: 'NAD - Namibian Dollar', value: 'NAD' },
					{ name: 'NGN - Nigerian Naira', value: 'NGN' },
					{ name: 'NIO - Nicaraguan Cordoba', value: 'NIO' },
					{ name: 'NOK - Norwegian Krone', value: 'NOK' },
					{ name: 'NPR - Nepalese Rupee', value: 'NPR' },
					{ name: 'NZD - New Zealand Dollar', value: 'NZD' },
					{ name: 'OMR - Omani Rial', value: 'OMR' },
					{ name: 'PAB - Panamanian Balboa', value: 'PAB' },
					{ name: 'PEN - Peruvian Sol', value: 'PEN' },
					{ name: 'PGK - Papua New Guinean Kina', value: 'PGK' },
					{ name: 'PHP - Philippine Peso', value: 'PHP' },
					{ name: 'PKR - Pakistani Rupee', value: 'PKR' },
					{ name: 'PLN - Polish Zloty', value: 'PLN' },
					{ name: 'PYG - Paraguayan Guarani', value: 'PYG' },
					{ name: 'QAR - Qatari Riyal', value: 'QAR' },
					{ name: 'RON - Romanian Leu', value: 'RON' },
					{ name: 'RSD - Serbian Dinar', value: 'RSD' },
					{ name: 'RUB - Russian Ruble', value: 'RUB' },
					{ name: 'RWF - Rwandan Franc', value: 'RWF' },
					{ name: 'SAR - Saudi Riyal', value: 'SAR' },
					{ name: 'SBD - Solomon Islands Dollar', value: 'SBD' },
					{ name: 'SCR - Seychellois Rupee', value: 'SCR' },
					{ name: 'SDG - Sudanese Pound', value: 'SDG' },
					{ name: 'SEK - Swedish Krona', value: 'SEK' },
					{ name: 'SGD - Singapore Dollar', value: 'SGD' },
					{ name: 'SHP - Saint Helena Pound', value: 'SHP' },
					{ name: 'SLL - Sierra Leonean Leone', value: 'SLL' },
					{ name: 'SOS - Somali Shilling', value: 'SOS' },
					{ name: 'SRD - Surinamese Dollar', value: 'SRD' },
					{ name: 'SSP - South Sudanese Pound', value: 'SSP' },
					{ name: 'STN - São Tomé and Príncipe Dobra', value: 'STN' },
					{ name: 'SVC - Salvadoran Colón', value: 'SVC' },
					{ name: 'SYP - Syrian Pound', value: 'SYP' },
					{ name: 'SZL - Swazi Lilangeni', value: 'SZL' },
					{ name: 'THB - Thai Baht', value: 'THB' },
					{ name: 'TJS - Tajikistani Somoni', value: 'TJS' },
					{ name: 'TMT - Turkmenistani Manat', value: 'TMT' },
					{ name: 'TND - Tunisian Dinar', value: 'TND' },
					{ name: 'TOP - Tongan Paʻanga', value: 'TOP' },
					{ name: 'TRY - Turkish Lira', value: 'TRY' },
					{ name: 'TTD - Trinidad and Tobago Dollar', value: 'TTD' },
					{ name: 'TWD - Taiwan Dollar', value: 'TWD' },
					{ name: 'TZS - Tanzanian Shilling', value: 'TZS' },
					{ name: 'UAH - Ukrainian Hryvnia', value: 'UAH' },
					{ name: 'UGX - Ugandan Shilling', value: 'UGX' },
					{ name: 'USD - US Dollar', value: 'USD' },
					{ name: 'UYU - Uruguayan Peso', value: 'UYU' },
					{ name: 'UZS - Uzbekistani Som', value: 'UZS' },
					{ name: 'VES - Venezuelan Bolivar', value: 'VES' },
					{ name: 'VND - Vietnamese Dong', value: 'VND' },
					{ name: 'VUV - Vanuatu Vatu', value: 'VUV' },
					{ name: 'WST - Samoan Tala', value: 'WST' },
					{ name: 'XAF - CFA Franc BEAC', value: 'XAF' },
					{ name: 'XCD - East Caribbean Dollar', value: 'XCD' },
					{ name: 'XOF - CFA Franc BCEAO', value: 'XOF' },
					{ name: 'XPF - CFP Franc', value: 'XPF' },
					{ name: 'YER - Yemeni Rial', value: 'YER' },
					{ name: 'ZAR - South African Rand', value: 'ZAR' },
					{ name: 'ZMW - Zambian Kwacha', value: 'ZMW' },
					{ name: 'ZWL - Zimbabwean Dollar', value: 'ZWL' },
				],
				default: 'INR',
			},
			{
				displayName: 'Price Type',
				name: 'tax_type',
				type: 'options',
				// eslint-disable-next-line n8n-nodes-base/node-param-options-type-unsorted-items
				options: [
					{ name: 'Inclusive of Tax', value: 'inclusive of tax' },
					{ name: 'Exclusive of Tax', value: 'exclusive of tax' },
				],
				default: 'inclusive of tax',
			},
			{
				displayName: 'Tax Rate',
				name: 'tax_rate',
				type: 'options',
				options: [
					{ name: '0.1%', value: '0.1%' },
					{ name: '0.25%', value: '0.25%' },
					{ name: '0%', value: '0%' },
					{ name: '1.5%', value: '1.5%' },
					{ name: '1%', value: '1%' },
					{ name: '12%', value: '12%' },
					{ name: '18%', value: '18%' },
					{ name: '28%', value: '28%' },
					{ name: '3%', value: '3%' },
					{ name: '5%', value: '5%' },
					{ name: '7.5%', value: '7.5%' },
					{ name: 'Exempted Supply', value: 'Exempted Supply' },
					{ name: 'Nil-Rated', value: 'Nil-Rated' },
					{ name: 'Non-Tax Supply', value: 'Non-GST Supply' },
					{ name: 'Zero-Rated', value: 'Zero-Rated' },
				],
				default: '5%',
			},
			{ displayName: 'Non-Taxable', name: 'non_taxable', type: 'number', default: 0, placeholder: 'Enter Non-Taxable' },
			{
				displayName: 'Units',
				name: 'units',
				type: 'options',
				options: [
					{ name: 'BAG-BAGS', value: 'BAG-BAGS' },
					{ name: 'BAL-BALE', value: 'BAL-BALE' },
					{ name: 'BDL-BUNDLES', value: 'BDL-BUNDLES' },
					{ name: 'BKL-BUCKLES', value: 'BKL-BUCKLES' },
					{ name: 'BOU-BILLIONS OF UNITS', value: 'BOU-BILLIONS OF UNITS' },
					{ name: 'BOX-BOX', value: 'BOX-BOX' },
					{ name: 'BTL-BOTTLES', value: 'BTL-BOTTLES' },
					{ name: 'BUN-BUNCHES', value: 'BUN-BUNCHES' },
					{ name: 'CAN-CANS', value: 'CAN-CANS' },
					{ name: 'CBM-CUBIC METERS', value: 'CBM-CUBIC METERS' },
					{ name: 'CCM-CUBIC CENTIMETERS', value: 'CCM-CUBIC CENTIMETERS' },
					{ name: 'CMC-CENTIMETERS', value: 'CMC-CENTIMETERS' },
					{ name: 'CTN-CARTONS', value: 'CTN-CARTONS' },
					{ name: 'DOZ-DOZENS', value: 'DOZ-DOZENS' },
					{ name: 'DRM-DRUMS', value: 'DRM-DRUMS' },
					{ name: 'GGK-GREAT GROSS', value: 'GGK-GREAT GROSS' },
					{ name: 'GMS-GRAMMES', value: 'GMS-GRAMMES' },
					{ name: 'GRS-GROSS', value: 'GRS-GROSS' },
					{ name: 'GYD-GROSS YARDS', value: 'GYD-GROSS YARDS' },
					{ name: 'KGS-KILOGRAMS', value: 'KGS-KILOGRAMS' },
					{ name: 'KLR-KILOLITRE', value: 'KLR-KILOLITRE' },
					{ name: 'KME-KILOMETRE', value: 'KME-KILOMETRE' },
					{ name: 'LTR-LITRES', value: 'LTR-LITRES' },
					{ name: 'MLS-MILLI LITRES', value: 'MLS-MILLI LITRES' },
					{ name: 'MLT-MILILITRE', value: 'MLT-MILILITRE' },
					{ name: 'MTR-METERS', value: 'MTR-METERS' },
					{ name: 'MTS-METRIC TON', value: 'MTS-METRIC TON' },
					{ name: 'NOS-NUMBERS', value: 'NOS-NUMBERS' },
					{ name: 'OTH-OTHERS', value: 'OTH-OTHERS' },
					{ name: 'PAC-PACKS', value: 'PAC-PACKS' },
					{ name: 'PCS-PIECES', value: 'PCS-PIECES' },
					{ name: 'PRS-PAIRS', value: 'PRS-PAIRS' },
					{ name: 'QTL-QUINTAL', value: 'QTL-QUINTAL' },
					{ name: 'ROL-ROLLS', value: 'ROL-ROLLS' },
					{ name: 'SET-SETS', value: 'SET-SETS' },
					{ name: 'SQF-SQUARE FEET', value: 'SQF-SQUARE FEET' },
					{ name: 'SQM-SQUARE METERS', value: 'SQM-SQUARE METERS' },
					{ name: 'SQY-SQUARE YARDS', value: 'SQY-SQUARE YARDS' },
					{ name: 'TBS-TABLETS', value: 'TBS-TABLETS' },
					{ name: 'TGM-TEN GROSS', value: 'TGM-TEN GROSS' },
					{ name: 'THD-THOUSANDS', value: 'THD-THOUSANDS' },
					{ name: 'TON-TONNES', value: 'TON-TONNES' },
					{ name: 'TUB-TUBES', value: 'TUB-TUBES' },
					{ name: 'UGS-US GALLONS', value: 'UGS-US GALLONS' },
					{ name: 'UNT-UNITS', value: 'UNT-UNITS' },
					{ name: 'YDS-YARDS', value: 'YDS-YARDS' }
				],
				default: 'UNT-UNITS',
				placeholder: '',
			},
			{
				displayName: 'Product Description',
				name: 'description',
				type: 'string',
				default: '',
				placeholder: '',
			},
			{
				displayName: 'HSN/SAC Code',
				name: 'hsn_sac',
				type: 'string',
				default: '',
				placeholder: 'Enter HSN/SAC Code',
			},
			{
				displayName: 'Expense Name or ID',
				name: 'coa_account',
				type: 'options',
				typeOptions: {
					loadOptionsMethod: 'getCoaAccounts',
				},
				default: '',
				placeholder: 'Select Expense Type',
				description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
			},
			{
				displayName: 'Cess Type',
				name: 'cess_type',
				type: 'options',
				options: [
					{ name: 'Percentage', value: 'percentage' },
					{ name: 'Flat Value', value: 'flat' },
				],
				default: 'percentage',
			},
			{
				displayName: 'Cess Value',
				name: 'cess_value',
				type: 'number',
				default: 0,
				placeholder: 'Enter Cess Value',
			},
		],
	},

	{
		displayName: 'Update Fields',
		name: 'catalogUpdateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['catalog'],
				operation: ['updateCatalog'],
			},
		},
		// eslint-disable-next-line n8n-nodes-base/node-param-collection-type-unsorted-items
		options: [
			{
        displayName: 'Currency', name: 'currency', type: 'options',
				options: [
					{ name: 'AED - UAE Dirham', value: 'AED' },
					{ name: 'AFN - Afghan Afghani', value: 'AFN' },
					{ name: 'ALL - Albanian Lek', value: 'ALL' },
					{ name: 'AMD - Armenian Dram', value: 'AMD' },
					{ name: 'ANG - Netherlands Antillean Guilder', value: 'ANG' },
					{ name: 'AOA - Angolan Kwanza', value: 'AOA' },
					{ name: 'ARS - Argentine Peso', value: 'ARS' },
					{ name: 'AUD - Australian Dollar', value: 'AUD' },
					{ name: 'AWG - Aruban Florin', value: 'AWG' },
					{ name: 'AZN - Azerbaijani Manat', value: 'AZN' },
					{ name: 'BAM - Bosnia and Herzegovina Convertible Mark', value: 'BAM' },
					{ name: 'BBD - Barbadian Dollar', value: 'BBD' },
					{ name: 'BDT - Bangladeshi Taka', value: 'BDT' },
					{ name: 'BGN - Bulgarian Lev', value: 'BGN' },
					{ name: 'BHD - Bahraini Dinar', value: 'BHD' },
					{ name: 'BIF - Burundian Franc', value: 'BIF' },
					{ name: 'BMD - Bermudian Dollar', value: 'BMD' },
					{ name: 'BND - Brunei Dollar', value: 'BND' },
					{ name: 'BOB - Bolivian Boliviano', value: 'BOB' },
					{ name: 'BRL - Brazilian Real', value: 'BRL' },
					{ name: 'BSD - Bahamian Dollar', value: 'BSD' },
					{ name: 'BTN - Bhutanese Ngultrum', value: 'BTN' },
					{ name: 'BWP - Botswana Pula', value: 'BWP' },
					{ name: 'BYN - Belarusian Ruble', value: 'BYN' },
					{ name: 'BZD - Belize Dollar', value: 'BZD' },
					{ name: 'CAD - Canadian Dollar', value: 'CAD' },
					{ name: 'CDF - Congolese Franc', value: 'CDF' },
					{ name: 'CHF - Swiss Franc', value: 'CHF' },
					{ name: 'CLF - Unidad De Fomento', value: 'CLF' },
					{ name: 'CLP - Chilean Peso', value: 'CLP' },
					{ name: 'CNY - Chinese Yuan', value: 'CNY' },
					{ name: 'COP - Colombian Peso', value: 'COP' },
					{ name: 'CRC - Costa Rican Colon', value: 'CRC' },
					{ name: 'CUC - Cuban Convertible Peso', value: 'CUC' },
					{ name: 'CUP - Cuban Peso', value: 'CUP' },
					{ name: 'CVE - Cape Verdean Escudo', value: 'CVE' },
					{ name: 'CZK - Czech Koruna', value: 'CZK' },
					{ name: 'DJF - Djiboutian Franc', value: 'DJF' },
					{ name: 'DKK - Danish Krone', value: 'DKK' },
					{ name: 'DOP - Dominican Peso', value: 'DOP' },
					{ name: 'DZD - Algerian Dinar', value: 'DZD' },
					{ name: 'EGP - Egyptian Pound', value: 'EGP' },
					{ name: 'ERN - Eritrean Nakfa', value: 'ERN' },
					{ name: 'ETB - Ethiopian Birr', value: 'ETB' },
					{ name: 'EUR - Euro', value: 'EUR' },
					{ name: 'FJD - Fijian Dollar', value: 'FJD' },
					{ name: 'FKP - Falkland Islands Pound', value: 'FKP' },
					{ name: 'GBP - British Pound', value: 'GBP' },
					{ name: 'GEL - Georgian Lari', value: 'GEL' },
					{ name: 'GHS - Ghanaian Cedi', value: 'GHS' },
					{ name: 'GIP - Gibraltar Pound', value: 'GIP' },
					{ name: 'GMD - Gambian Dalasi', value: 'GMD' },
					{ name: 'GNF - Guinean Franc', value: 'GNF' },
					{ name: 'GTQ - Guatemalan Quetzal', value: 'GTQ' },
					{ name: 'GYD - Guyanese Dollar', value: 'GYD' },
					{ name: 'HKD - Hong Kong Dollar', value: 'HKD' },
					{ name: 'HNL - Honduran Lempira', value: 'HNL' },
					{ name: 'HRK - Croatian Kuna', value: 'HRK' },
					{ name: 'HTG - Haitian Gourde', value: 'HTG' },
					{ name: 'HUF - Hungarian Forint', value: 'HUF' },
					{ name: 'IDR - Indonesian Rupiah', value: 'IDR' },
					{ name: 'ILS - Israeli New Shekel', value: 'ILS' },
					{ name: 'INR - Indian Rupee', value: 'INR' },
					{ name: 'IQD - Iraqi Dinar', value: 'IQD' },
					{ name: 'IRR - Iranian Rial', value: 'IRR' },
					{ name: 'ISK - Icelandic Króna', value: 'ISK' },
					{ name: 'JMD - Jamaican Dollar', value: 'JMD' },
					{ name: 'JOD - Jordanian Dinar', value: 'JOD' },
					{ name: 'JPY - Japanese Yen', value: 'JPY' },
					{ name: 'KES - Kenyan Shilling', value: 'KES' },
					{ name: 'KGS - Kyrgyzstani Som', value: 'KGS' },
					{ name: 'KHR - Cambodian Riel', value: 'KHR' },
					{ name: 'KMF - Comorian Franc', value: 'KMF' },
					{ name: 'KPW - North Korean Won', value: 'KPW' },
					{ name: 'KRW - South Korean Won', value: 'KRW' },
					{ name: 'KWD - Kuwaiti Dinar', value: 'KWD' },
					{ name: 'KYD - Cayman Islands Dollar', value: 'KYD' },
					{ name: 'KZT - Kazakhstani Tenge', value: 'KZT' },
					{ name: 'LAK - Lao Kip', value: 'LAK' },
					{ name: 'LBP - Lebanese Pound', value: 'LBP' },
					{ name: 'LKR - Sri Lankan Rupee', value: 'LKR' },
					{ name: 'LRD - Liberian Dollar', value: 'LRD' },
					{ name: 'LSL - Lesotho Loti', value: 'LSL' },
					{ name: 'LYD - Libyan Dinar', value: 'LYD' },
					{ name: 'MAD - Moroccan Dirham', value: 'MAD' },
					{ name: 'MDL - Moldovan Leu', value: 'MDL' },
					{ name: 'MGA - Malagasy Ariary', value: 'MGA' },
					{ name: 'MKD - Macedonian Denar', value: 'MKD' },
					{ name: 'MMK - Myanmar Kyat', value: 'MMK' },
					{ name: 'MNT - Mongolian Tugrik', value: 'MNT' },
					{ name: 'MOP - Macanese Pataca', value: 'MOP' },
					{ name: 'MRU - Mauritanian Ouguiya', value: 'MRU' },
					{ name: 'MUR - Mauritian Rupee', value: 'MUR' },
					{ name: 'MVR - Maldivian Rufiyaa', value: 'MVR' },
					{ name: 'MWK - Malawian Kwacha', value: 'MWK' },
					{ name: 'MXN - Mexican Peso', value: 'MXN' },
					{ name: 'MYR - Malaysian Ringgit', value: 'MYR' },
					{ name: 'MZN - Mozambican Metical', value: 'MZN' },
					{ name: 'NAD - Namibian Dollar', value: 'NAD' },
					{ name: 'NGN - Nigerian Naira', value: 'NGN' },
					{ name: 'NIO - Nicaraguan Cordoba', value: 'NIO' },
					{ name: 'NOK - Norwegian Krone', value: 'NOK' },
					{ name: 'NPR - Nepalese Rupee', value: 'NPR' },
					{ name: 'NZD - New Zealand Dollar', value: 'NZD' },
					{ name: 'OMR - Omani Rial', value: 'OMR' },
					{ name: 'PAB - Panamanian Balboa', value: 'PAB' },
					{ name: 'PEN - Peruvian Sol', value: 'PEN' },
					{ name: 'PGK - Papua New Guinean Kina', value: 'PGK' },
					{ name: 'PHP - Philippine Peso', value: 'PHP' },
					{ name: 'PKR - Pakistani Rupee', value: 'PKR' },
					{ name: 'PLN - Polish Zloty', value: 'PLN' },
					{ name: 'PYG - Paraguayan Guarani', value: 'PYG' },
					{ name: 'QAR - Qatari Riyal', value: 'QAR' },
					{ name: 'RON - Romanian Leu', value: 'RON' },
					{ name: 'RSD - Serbian Dinar', value: 'RSD' },
					{ name: 'RUB - Russian Ruble', value: 'RUB' },
					{ name: 'RWF - Rwandan Franc', value: 'RWF' },
					{ name: 'SAR - Saudi Riyal', value: 'SAR' },
					{ name: 'SBD - Solomon Islands Dollar', value: 'SBD' },
					{ name: 'SCR - Seychellois Rupee', value: 'SCR' },
					{ name: 'SDG - Sudanese Pound', value: 'SDG' },
					{ name: 'SEK - Swedish Krona', value: 'SEK' },
					{ name: 'SGD - Singapore Dollar', value: 'SGD' },
					{ name: 'SHP - Saint Helena Pound', value: 'SHP' },
					{ name: 'SLL - Sierra Leonean Leone', value: 'SLL' },
					{ name: 'SOS - Somali Shilling', value: 'SOS' },
					{ name: 'SRD - Surinamese Dollar', value: 'SRD' },
					{ name: 'SSP - South Sudanese Pound', value: 'SSP' },
					{ name: 'STN - São Tomé and Príncipe Dobra', value: 'STN' },
					{ name: 'SVC - Salvadoran Colón', value: 'SVC' },
					{ name: 'SYP - Syrian Pound', value: 'SYP' },
					{ name: 'SZL - Swazi Lilangeni', value: 'SZL' },
					{ name: 'THB - Thai Baht', value: 'THB' },
					{ name: 'TJS - Tajikistani Somoni', value: 'TJS' },
					{ name: 'TMT - Turkmenistani Manat', value: 'TMT' },
					{ name: 'TND - Tunisian Dinar', value: 'TND' },
					{ name: 'TOP - Tongan Paʻanga', value: 'TOP' },
					{ name: 'TRY - Turkish Lira', value: 'TRY' },
					{ name: 'TTD - Trinidad and Tobago Dollar', value: 'TTD' },
					{ name: 'TWD - Taiwan Dollar', value: 'TWD' },
					{ name: 'TZS - Tanzanian Shilling', value: 'TZS' },
					{ name: 'UAH - Ukrainian Hryvnia', value: 'UAH' },
					{ name: 'UGX - Ugandan Shilling', value: 'UGX' },
					{ name: 'USD - US Dollar', value: 'USD' },
					{ name: 'UYU - Uruguayan Peso', value: 'UYU' },
					{ name: 'UZS - Uzbekistani Som', value: 'UZS' },
					{ name: 'VES - Venezuelan Bolivar', value: 'VES' },
					{ name: 'VND - Vietnamese Dong', value: 'VND' },
					{ name: 'VUV - Vanuatu Vatu', value: 'VUV' },
					{ name: 'WST - Samoan Tala', value: 'WST' },
					{ name: 'XAF - CFA Franc BEAC', value: 'XAF' },
					{ name: 'XCD - East Caribbean Dollar', value: 'XCD' },
					{ name: 'XOF - CFA Franc BCEAO', value: 'XOF' },
					{ name: 'XPF - CFP Franc', value: 'XPF' },
					{ name: 'YER - Yemeni Rial', value: 'YER' },
					{ name: 'ZAR - South African Rand', value: 'ZAR' },
					{ name: 'ZMW - Zambian Kwacha', value: 'ZMW' },
					{ name: 'ZWL - Zimbabwean Dollar', value: 'ZWL' },
				],
				default: 'INR',
			},
			{
				displayName: 'Tax Rate',
				name: 'tax_rate',
				type: 'options',
				options: [
					{ name: '0.1%', value: '0.1%' },
					{ name: '0.25%', value: '0.25%' },
					{ name: '0%', value: '0%' },
					{ name: '1.5%', value: '1.5%' },
					{ name: '1%', value: '1%' },
					{ name: '12%', value: '12%' },
					{ name: '18%', value: '18%' },
					{ name: '28%', value: '28%' },
					{ name: '3%', value: '3%' },
					{ name: '5%', value: '5%' },
					{ name: '7.5%', value: '7.5%' },
					{ name: 'Exempted Supply', value: 'Exempted Supply' },
					{ name: 'Nil-Rated', value: 'Nil-Rated' },
					{ name: 'Non-Tax Supply', value: 'Non-GST Supply' },
					{ name: 'Zero-Rated', value: 'Zero-Rated' },
				],
				default: '5%',
			},
			{
				displayName: 'Units',
				name: 'units',
				type: 'options',
				options: [
					{ name: 'BAG-BAGS', value: 'BAG-BAGS' },
					{ name: 'BAL-BALE', value: 'BAL-BALE' },
					{ name: 'BDL-BUNDLES', value: 'BDL-BUNDLES' },
					{ name: 'BKL-BUCKLES', value: 'BKL-BUCKLES' },
					{ name: 'BOU-BILLIONS OF UNITS', value: 'BOU-BILLIONS OF UNITS' },
					{ name: 'BOX-BOX', value: 'BOX-BOX' },
					{ name: 'BTL-BOTTLES', value: 'BTL-BOTTLES' },
					{ name: 'BUN-BUNCHES', value: 'BUN-BUNCHES' },
					{ name: 'CAN-CANS', value: 'CAN-CANS' },
					{ name: 'CBM-CUBIC METERS', value: 'CBM-CUBIC METERS' },
					{ name: 'CCM-CUBIC CENTIMETERS', value: 'CCM-CUBIC CENTIMETERS' },
					{ name: 'CMC-CENTIMETERS', value: 'CMC-CENTIMETERS' },
					{ name: 'CTN-CARTONS', value: 'CTN-CARTONS' },
					{ name: 'DOZ-DOZENS', value: 'DOZ-DOZENS' },
					{ name: 'DRM-DRUMS', value: 'DRM-DRUMS' },
					{ name: 'GGK-GREAT GROSS', value: 'GGK-GREAT GROSS' },
					{ name: 'GMS-GRAMMES', value: 'GMS-GRAMMES' },
					{ name: 'GRS-GROSS', value: 'GRS-GROSS' },
					{ name: 'GYD-GROSS YARDS', value: 'GYD-GROSS YARDS' },
					{ name: 'KGS-KILOGRAMS', value: 'KGS-KILOGRAMS' },
					{ name: 'KLR-KILOLITRE', value: 'KLR-KILOLITRE' },
					{ name: 'KME-KILOMETRE', value: 'KME-KILOMETRE' },
					{ name: 'LTR-LITRES', value: 'LTR-LITRES' },
					{ name: 'MLS-MILLI LITRES', value: 'MLS-MILLI LITRES' },
					{ name: 'MLT-MILILITRE', value: 'MLT-MILILITRE' },
					{ name: 'MTR-METERS', value: 'MTR-METERS' },
					{ name: 'MTS-METRIC TON', value: 'MTS-METRIC TON' },
					{ name: 'NOS-NUMBERS', value: 'NOS-NUMBERS' },
					{ name: 'OTH-OTHERS', value: 'OTH-OTHERS' },
					{ name: 'PAC-PACKS', value: 'PAC-PACKS' },
					{ name: 'PCS-PIECES', value: 'PCS-PIECES' },
					{ name: 'PRS-PAIRS', value: 'PRS-PAIRS' },
					{ name: 'QTL-QUINTAL', value: 'QTL-QUINTAL' },
					{ name: 'ROL-ROLLS', value: 'ROL-ROLLS' },
					{ name: 'SET-SETS', value: 'SET-SETS' },
					{ name: 'SQF-SQUARE FEET', value: 'SQF-SQUARE FEET' },
					{ name: 'SQM-SQUARE METERS', value: 'SQM-SQUARE METERS' },
					{ name: 'SQY-SQUARE YARDS', value: 'SQY-SQUARE YARDS' },
					{ name: 'TBS-TABLETS', value: 'TBS-TABLETS' },
					{ name: 'TGM-TEN GROSS', value: 'TGM-TEN GROSS' },
					{ name: 'THD-THOUSANDS', value: 'THD-THOUSANDS' },
					{ name: 'TON-TONNES', value: 'TON-TONNES' },
					{ name: 'TUB-TUBES', value: 'TUB-TUBES' },
					{ name: 'UGS-US GALLONS', value: 'UGS-US GALLONS' },
					{ name: 'UNT-UNITS', value: 'UNT-UNITS' },
					{ name: 'YDS-YARDS', value: 'YDS-YARDS' }
				],
				default: 'UNT-UNITS',
				placeholder: '',
			},
			{
				displayName: 'Product Description',
				name: 'description',
				type: 'string',
				default: '',
				placeholder: '',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'Active', value: '1' },
					{ name: 'Inactive', value: '0' },
				],
				default: '1',
			},
			{
				displayName: 'HSN/SAC Code',
				name: 'hsn_sac',
				type: 'string',
				default: '',
				placeholder: 'Enter HSN/SAC Code',
			},
			{
				displayName: 'Expense Name or ID',
				name: 'coa_account',
				type: 'options',
				typeOptions: {
					loadOptionsMethod: 'getCoaAccounts',
				},
				default: '',
				placeholder: 'Select Expense Type',
				description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
			},
			{
				displayName: 'Cess Type',
				name: 'cess_type',
				type: 'options',
				options: [
					{ name: 'Percentage', value: 'percentage' },
					{ name: 'Flat Value', value: 'flat' },
				],
				default: 'percentage',
			},
			{
				displayName: 'Cess Value',
				name: 'cess_value',
				type: 'number',
				default: '',
				placeholder: 'Enter Cess Value',
				description: 'For percentage: Enter value between 1-100. For flat: Enter absolute value.',
			},
		],
	},

	// eslint-disable-next-line n8n-nodes-base/node-param-display-name-wrong-for-dynamic-options
	{
		displayName: 'Variant Name or ID',
		name: 'variantId',
		type: 'options',
		typeOptions: {
			loadOptionsMethod: 'getCatalogVariants',
		},
		required: true,
		default: '',
		displayOptions: {
			show: {
				operation: ['updateVariant'],
			},
			hide: {
				catalogId: [''], // Hide if catalogId is empty
			},
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},
	{
		displayName: 'Update Variant Fields',
		name: 'catalogUpdateVariantFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['catalog'],
				operation: ['updateVariant'],
			},
		},
		options: [
			{
        displayName: 'Currency', name: 'currency', type: 'options',
				options: [
					{ name: 'AED - UAE Dirham', value: 'AED' },
					{ name: 'AFN - Afghan Afghani', value: 'AFN' },
					{ name: 'ALL - Albanian Lek', value: 'ALL' },
					{ name: 'AMD - Armenian Dram', value: 'AMD' },
					{ name: 'ANG - Netherlands Antillean Guilder', value: 'ANG' },
					{ name: 'AOA - Angolan Kwanza', value: 'AOA' },
					{ name: 'ARS - Argentine Peso', value: 'ARS' },
					{ name: 'AUD - Australian Dollar', value: 'AUD' },
					{ name: 'AWG - Aruban Florin', value: 'AWG' },
					{ name: 'AZN - Azerbaijani Manat', value: 'AZN' },
					{ name: 'BAM - Bosnia and Herzegovina Convertible Mark', value: 'BAM' },
					{ name: 'BBD - Barbadian Dollar', value: 'BBD' },
					{ name: 'BDT - Bangladeshi Taka', value: 'BDT' },
					{ name: 'BGN - Bulgarian Lev', value: 'BGN' },
					{ name: 'BHD - Bahraini Dinar', value: 'BHD' },
					{ name: 'BIF - Burundian Franc', value: 'BIF' },
					{ name: 'BMD - Bermudian Dollar', value: 'BMD' },
					{ name: 'BND - Brunei Dollar', value: 'BND' },
					{ name: 'BOB - Bolivian Boliviano', value: 'BOB' },
					{ name: 'BRL - Brazilian Real', value: 'BRL' },
					{ name: 'BSD - Bahamian Dollar', value: 'BSD' },
					{ name: 'BTN - Bhutanese Ngultrum', value: 'BTN' },
					{ name: 'BWP - Botswana Pula', value: 'BWP' },
					{ name: 'BYN - Belarusian Ruble', value: 'BYN' },
					{ name: 'BZD - Belize Dollar', value: 'BZD' },
					{ name: 'CAD - Canadian Dollar', value: 'CAD' },
					{ name: 'CDF - Congolese Franc', value: 'CDF' },
					{ name: 'CHF - Swiss Franc', value: 'CHF' },
					{ name: 'CLF - Unidad De Fomento', value: 'CLF' },
					{ name: 'CLP - Chilean Peso', value: 'CLP' },
					{ name: 'CNY - Chinese Yuan', value: 'CNY' },
					{ name: 'COP - Colombian Peso', value: 'COP' },
					{ name: 'CRC - Costa Rican Colon', value: 'CRC' },
					{ name: 'CUC - Cuban Convertible Peso', value: 'CUC' },
					{ name: 'CUP - Cuban Peso', value: 'CUP' },
					{ name: 'CVE - Cape Verdean Escudo', value: 'CVE' },
					{ name: 'CZK - Czech Koruna', value: 'CZK' },
					{ name: 'DJF - Djiboutian Franc', value: 'DJF' },
					{ name: 'DKK - Danish Krone', value: 'DKK' },
					{ name: 'DOP - Dominican Peso', value: 'DOP' },
					{ name: 'DZD - Algerian Dinar', value: 'DZD' },
					{ name: 'EGP - Egyptian Pound', value: 'EGP' },
					{ name: 'ERN - Eritrean Nakfa', value: 'ERN' },
					{ name: 'ETB - Ethiopian Birr', value: 'ETB' },
					{ name: 'EUR - Euro', value: 'EUR' },
					{ name: 'FJD - Fijian Dollar', value: 'FJD' },
					{ name: 'FKP - Falkland Islands Pound', value: 'FKP' },
					{ name: 'GBP - British Pound', value: 'GBP' },
					{ name: 'GEL - Georgian Lari', value: 'GEL' },
					{ name: 'GHS - Ghanaian Cedi', value: 'GHS' },
					{ name: 'GIP - Gibraltar Pound', value: 'GIP' },
					{ name: 'GMD - Gambian Dalasi', value: 'GMD' },
					{ name: 'GNF - Guinean Franc', value: 'GNF' },
					{ name: 'GTQ - Guatemalan Quetzal', value: 'GTQ' },
					{ name: 'GYD - Guyanese Dollar', value: 'GYD' },
					{ name: 'HKD - Hong Kong Dollar', value: 'HKD' },
					{ name: 'HNL - Honduran Lempira', value: 'HNL' },
					{ name: 'HRK - Croatian Kuna', value: 'HRK' },
					{ name: 'HTG - Haitian Gourde', value: 'HTG' },
					{ name: 'HUF - Hungarian Forint', value: 'HUF' },
					{ name: 'IDR - Indonesian Rupiah', value: 'IDR' },
					{ name: 'ILS - Israeli New Shekel', value: 'ILS' },
					{ name: 'INR - Indian Rupee', value: 'INR' },
					{ name: 'IQD - Iraqi Dinar', value: 'IQD' },
					{ name: 'IRR - Iranian Rial', value: 'IRR' },
					{ name: 'ISK - Icelandic Króna', value: 'ISK' },
					{ name: 'JMD - Jamaican Dollar', value: 'JMD' },
					{ name: 'JOD - Jordanian Dinar', value: 'JOD' },
					{ name: 'JPY - Japanese Yen', value: 'JPY' },
					{ name: 'KES - Kenyan Shilling', value: 'KES' },
					{ name: 'KGS - Kyrgyzstani Som', value: 'KGS' },
					{ name: 'KHR - Cambodian Riel', value: 'KHR' },
					{ name: 'KMF - Comorian Franc', value: 'KMF' },
					{ name: 'KPW - North Korean Won', value: 'KPW' },
					{ name: 'KRW - South Korean Won', value: 'KRW' },
					{ name: 'KWD - Kuwaiti Dinar', value: 'KWD' },
					{ name: 'KYD - Cayman Islands Dollar', value: 'KYD' },
					{ name: 'KZT - Kazakhstani Tenge', value: 'KZT' },
					{ name: 'LAK - Lao Kip', value: 'LAK' },
					{ name: 'LBP - Lebanese Pound', value: 'LBP' },
					{ name: 'LKR - Sri Lankan Rupee', value: 'LKR' },
					{ name: 'LRD - Liberian Dollar', value: 'LRD' },
					{ name: 'LSL - Lesotho Loti', value: 'LSL' },
					{ name: 'LYD - Libyan Dinar', value: 'LYD' },
					{ name: 'MAD - Moroccan Dirham', value: 'MAD' },
					{ name: 'MDL - Moldovan Leu', value: 'MDL' },
					{ name: 'MGA - Malagasy Ariary', value: 'MGA' },
					{ name: 'MKD - Macedonian Denar', value: 'MKD' },
					{ name: 'MMK - Myanmar Kyat', value: 'MMK' },
					{ name: 'MNT - Mongolian Tugrik', value: 'MNT' },
					{ name: 'MOP - Macanese Pataca', value: 'MOP' },
					{ name: 'MRU - Mauritanian Ouguiya', value: 'MRU' },
					{ name: 'MUR - Mauritian Rupee', value: 'MUR' },
					{ name: 'MVR - Maldivian Rufiyaa', value: 'MVR' },
					{ name: 'MWK - Malawian Kwacha', value: 'MWK' },
					{ name: 'MXN - Mexican Peso', value: 'MXN' },
					{ name: 'MYR - Malaysian Ringgit', value: 'MYR' },
					{ name: 'MZN - Mozambican Metical', value: 'MZN' },
					{ name: 'NAD - Namibian Dollar', value: 'NAD' },
					{ name: 'NGN - Nigerian Naira', value: 'NGN' },
					{ name: 'NIO - Nicaraguan Cordoba', value: 'NIO' },
					{ name: 'NOK - Norwegian Krone', value: 'NOK' },
					{ name: 'NPR - Nepalese Rupee', value: 'NPR' },
					{ name: 'NZD - New Zealand Dollar', value: 'NZD' },
					{ name: 'OMR - Omani Rial', value: 'OMR' },
					{ name: 'PAB - Panamanian Balboa', value: 'PAB' },
					{ name: 'PEN - Peruvian Sol', value: 'PEN' },
					{ name: 'PGK - Papua New Guinean Kina', value: 'PGK' },
					{ name: 'PHP - Philippine Peso', value: 'PHP' },
					{ name: 'PKR - Pakistani Rupee', value: 'PKR' },
					{ name: 'PLN - Polish Zloty', value: 'PLN' },
					{ name: 'PYG - Paraguayan Guarani', value: 'PYG' },
					{ name: 'QAR - Qatari Riyal', value: 'QAR' },
					{ name: 'RON - Romanian Leu', value: 'RON' },
					{ name: 'RSD - Serbian Dinar', value: 'RSD' },
					{ name: 'RUB - Russian Ruble', value: 'RUB' },
					{ name: 'RWF - Rwandan Franc', value: 'RWF' },
					{ name: 'SAR - Saudi Riyal', value: 'SAR' },
					{ name: 'SBD - Solomon Islands Dollar', value: 'SBD' },
					{ name: 'SCR - Seychellois Rupee', value: 'SCR' },
					{ name: 'SDG - Sudanese Pound', value: 'SDG' },
					{ name: 'SEK - Swedish Krona', value: 'SEK' },
					{ name: 'SGD - Singapore Dollar', value: 'SGD' },
					{ name: 'SHP - Saint Helena Pound', value: 'SHP' },
					{ name: 'SLL - Sierra Leonean Leone', value: 'SLL' },
					{ name: 'SOS - Somali Shilling', value: 'SOS' },
					{ name: 'SRD - Surinamese Dollar', value: 'SRD' },
					{ name: 'SSP - South Sudanese Pound', value: 'SSP' },
					{ name: 'STN - São Tomé and Príncipe Dobra', value: 'STN' },
					{ name: 'SVC - Salvadoran Colón', value: 'SVC' },
					{ name: 'SYP - Syrian Pound', value: 'SYP' },
					{ name: 'SZL - Swazi Lilangeni', value: 'SZL' },
					{ name: 'THB - Thai Baht', value: 'THB' },
					{ name: 'TJS - Tajikistani Somoni', value: 'TJS' },
					{ name: 'TMT - Turkmenistani Manat', value: 'TMT' },
					{ name: 'TND - Tunisian Dinar', value: 'TND' },
					{ name: 'TOP - Tongan Paʻanga', value: 'TOP' },
					{ name: 'TRY - Turkish Lira', value: 'TRY' },
					{ name: 'TTD - Trinidad and Tobago Dollar', value: 'TTD' },
					{ name: 'TWD - Taiwan Dollar', value: 'TWD' },
					{ name: 'TZS - Tanzanian Shilling', value: 'TZS' },
					{ name: 'UAH - Ukrainian Hryvnia', value: 'UAH' },
					{ name: 'UGX - Ugandan Shilling', value: 'UGX' },
					{ name: 'USD - US Dollar', value: 'USD' },
					{ name: 'UYU - Uruguayan Peso', value: 'UYU' },
					{ name: 'UZS - Uzbekistani Som', value: 'UZS' },
					{ name: 'VES - Venezuelan Bolivar', value: 'VES' },
					{ name: 'VND - Vietnamese Dong', value: 'VND' },
					{ name: 'VUV - Vanuatu Vatu', value: 'VUV' },
					{ name: 'WST - Samoan Tala', value: 'WST' },
					{ name: 'XAF - CFA Franc BEAC', value: 'XAF' },
					{ name: 'XCD - East Caribbean Dollar', value: 'XCD' },
					{ name: 'XOF - CFA Franc BCEAO', value: 'XOF' },
					{ name: 'XPF - CFP Franc', value: 'XPF' },
					{ name: 'YER - Yemeni Rial', value: 'YER' },
					{ name: 'ZAR - South African Rand', value: 'ZAR' },
					{ name: 'ZMW - Zambian Kwacha', value: 'ZMW' },
					{ name: 'ZWL - Zimbabwean Dollar', value: 'ZWL' },
				],
				default: 'INR',
			},
			{
				displayName: 'Non-Taxable',
				name: 'variant_non_taxable',
				type: 'number',
				default: 0,
				placeholder: 'Enter Non-Taxable',
			},
			{
				displayName: 'Price',
				name: 'variant_price',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Price Type',
					name: 'variant_tax_type',
				type: 'options',
				options: [
					{ name: 'Inclusive of Tax', value: 'inclusive of tax' },
					{ name: 'Exclusive of Tax', value: 'exclusive of tax' },
				],
				default: 'inclusive of tax',
			},
			{
				displayName: 'SKU ID',
				name: 'variant_sku',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Status',
				name: 'variant_status',
				type: 'options',
				options: [
					{ name: 'Active', value: '1' },
					{ name: 'Inactive', value: '0' },
				],
				default: '1',
			},
			{
				displayName: 'Variant Description',
				name: 'variant_description',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Variant Name',
				name: 'variant_name',
				type: 'string',
				default: '',
			},
		],
	},

	{
		displayName: 'Search Type',
		name: 'searchType',
		type: 'options',
		options: [
			{ name: 'Search by Name', value: 'search_term' },
			{ name: 'Search by Limit', value: 'limit' },
		],
		default: 'limit',
		displayOptions: {
			show: {
				resource: ['catalog'],
				operation: ['getAllCatalogs'],
			},
		},
	},

	{
		displayName: 'Search Term',
		name: 'searchTerm',
		type: 'string',
		default: '',
		placeholder: 'Enter name to search',
		displayOptions: {
			show: {
				resource: ['catalog'],
				operation: ['getAllCatalogs'],
				searchType: ['search_term'],
			},
		},
	},

	{
		displayName: 'Limit (Per Page)',
		name: 'perPage',
		type: 'number',
		default: 5,
		displayOptions: {
			show: {
				resource: ['catalog'],
				operation: ['getAllCatalogs'],
				searchType: ['search_term', 'limit'],
			},
		},
	},

	{
		displayName: 'Variant Name',
		name: 'variant_name',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				operation: ['addVariant'],
			},
		},
	},

	{
		displayName: 'Price',
		name: 'variant_price',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				operation: ['addVariant'],
			},
		},
	},

	{
		displayName: 'Additional Fields',
		name: 'variantAdditionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['addVariant'],
			},
		},
		options: [
			{
        displayName: 'Currency', name: 'currency', type: 'options',
				options: [
					{ name: 'AED - UAE Dirham', value: 'AED' },
					{ name: 'AFN - Afghan Afghani', value: 'AFN' },
					{ name: 'ALL - Albanian Lek', value: 'ALL' },
					{ name: 'AMD - Armenian Dram', value: 'AMD' },
					{ name: 'ANG - Netherlands Antillean Guilder', value: 'ANG' },
					{ name: 'AOA - Angolan Kwanza', value: 'AOA' },
					{ name: 'ARS - Argentine Peso', value: 'ARS' },
					{ name: 'AUD - Australian Dollar', value: 'AUD' },
					{ name: 'AWG - Aruban Florin', value: 'AWG' },
					{ name: 'AZN - Azerbaijani Manat', value: 'AZN' },
					{ name: 'BAM - Bosnia and Herzegovina Convertible Mark', value: 'BAM' },
					{ name: 'BBD - Barbadian Dollar', value: 'BBD' },
					{ name: 'BDT - Bangladeshi Taka', value: 'BDT' },
					{ name: 'BGN - Bulgarian Lev', value: 'BGN' },
					{ name: 'BHD - Bahraini Dinar', value: 'BHD' },
					{ name: 'BIF - Burundian Franc', value: 'BIF' },
					{ name: 'BMD - Bermudian Dollar', value: 'BMD' },
					{ name: 'BND - Brunei Dollar', value: 'BND' },
					{ name: 'BOB - Bolivian Boliviano', value: 'BOB' },
					{ name: 'BRL - Brazilian Real', value: 'BRL' },
					{ name: 'BSD - Bahamian Dollar', value: 'BSD' },
					{ name: 'BTN - Bhutanese Ngultrum', value: 'BTN' },
					{ name: 'BWP - Botswana Pula', value: 'BWP' },
					{ name: 'BYN - Belarusian Ruble', value: 'BYN' },
					{ name: 'BZD - Belize Dollar', value: 'BZD' },
					{ name: 'CAD - Canadian Dollar', value: 'CAD' },
					{ name: 'CDF - Congolese Franc', value: 'CDF' },
					{ name: 'CHF - Swiss Franc', value: 'CHF' },
					{ name: 'CLF - Unidad De Fomento', value: 'CLF' },
					{ name: 'CLP - Chilean Peso', value: 'CLP' },
					{ name: 'CNY - Chinese Yuan', value: 'CNY' },
					{ name: 'COP - Colombian Peso', value: 'COP' },
					{ name: 'CRC - Costa Rican Colon', value: 'CRC' },
					{ name: 'CUC - Cuban Convertible Peso', value: 'CUC' },
					{ name: 'CUP - Cuban Peso', value: 'CUP' },
					{ name: 'CVE - Cape Verdean Escudo', value: 'CVE' },
					{ name: 'CZK - Czech Koruna', value: 'CZK' },
					{ name: 'DJF - Djiboutian Franc', value: 'DJF' },
					{ name: 'DKK - Danish Krone', value: 'DKK' },
					{ name: 'DOP - Dominican Peso', value: 'DOP' },
					{ name: 'DZD - Algerian Dinar', value: 'DZD' },
					{ name: 'EGP - Egyptian Pound', value: 'EGP' },
					{ name: 'ERN - Eritrean Nakfa', value: 'ERN' },
					{ name: 'ETB - Ethiopian Birr', value: 'ETB' },
					{ name: 'EUR - Euro', value: 'EUR' },
					{ name: 'FJD - Fijian Dollar', value: 'FJD' },
					{ name: 'FKP - Falkland Islands Pound', value: 'FKP' },
					{ name: 'GBP - British Pound', value: 'GBP' },
					{ name: 'GEL - Georgian Lari', value: 'GEL' },
					{ name: 'GHS - Ghanaian Cedi', value: 'GHS' },
					{ name: 'GIP - Gibraltar Pound', value: 'GIP' },
					{ name: 'GMD - Gambian Dalasi', value: 'GMD' },
					{ name: 'GNF - Guinean Franc', value: 'GNF' },
					{ name: 'GTQ - Guatemalan Quetzal', value: 'GTQ' },
					{ name: 'GYD - Guyanese Dollar', value: 'GYD' },
					{ name: 'HKD - Hong Kong Dollar', value: 'HKD' },
					{ name: 'HNL - Honduran Lempira', value: 'HNL' },
					{ name: 'HRK - Croatian Kuna', value: 'HRK' },
					{ name: 'HTG - Haitian Gourde', value: 'HTG' },
					{ name: 'HUF - Hungarian Forint', value: 'HUF' },
					{ name: 'IDR - Indonesian Rupiah', value: 'IDR' },
					{ name: 'ILS - Israeli New Shekel', value: 'ILS' },
					{ name: 'INR - Indian Rupee', value: 'INR' },
					{ name: 'IQD - Iraqi Dinar', value: 'IQD' },
					{ name: 'IRR - Iranian Rial', value: 'IRR' },
					{ name: 'ISK - Icelandic Króna', value: 'ISK' },
					{ name: 'JMD - Jamaican Dollar', value: 'JMD' },
					{ name: 'JOD - Jordanian Dinar', value: 'JOD' },
					{ name: 'JPY - Japanese Yen', value: 'JPY' },
					{ name: 'KES - Kenyan Shilling', value: 'KES' },
					{ name: 'KGS - Kyrgyzstani Som', value: 'KGS' },
					{ name: 'KHR - Cambodian Riel', value: 'KHR' },
					{ name: 'KMF - Comorian Franc', value: 'KMF' },
					{ name: 'KPW - North Korean Won', value: 'KPW' },
					{ name: 'KRW - South Korean Won', value: 'KRW' },
					{ name: 'KWD - Kuwaiti Dinar', value: 'KWD' },
					{ name: 'KYD - Cayman Islands Dollar', value: 'KYD' },
					{ name: 'KZT - Kazakhstani Tenge', value: 'KZT' },
					{ name: 'LAK - Lao Kip', value: 'LAK' },
					{ name: 'LBP - Lebanese Pound', value: 'LBP' },
					{ name: 'LKR - Sri Lankan Rupee', value: 'LKR' },
					{ name: 'LRD - Liberian Dollar', value: 'LRD' },
					{ name: 'LSL - Lesotho Loti', value: 'LSL' },
					{ name: 'LYD - Libyan Dinar', value: 'LYD' },
					{ name: 'MAD - Moroccan Dirham', value: 'MAD' },
					{ name: 'MDL - Moldovan Leu', value: 'MDL' },
					{ name: 'MGA - Malagasy Ariary', value: 'MGA' },
					{ name: 'MKD - Macedonian Denar', value: 'MKD' },
					{ name: 'MMK - Myanmar Kyat', value: 'MMK' },
					{ name: 'MNT - Mongolian Tugrik', value: 'MNT' },
					{ name: 'MOP - Macanese Pataca', value: 'MOP' },
					{ name: 'MRU - Mauritanian Ouguiya', value: 'MRU' },
					{ name: 'MUR - Mauritian Rupee', value: 'MUR' },
					{ name: 'MVR - Maldivian Rufiyaa', value: 'MVR' },
					{ name: 'MWK - Malawian Kwacha', value: 'MWK' },
					{ name: 'MXN - Mexican Peso', value: 'MXN' },
					{ name: 'MYR - Malaysian Ringgit', value: 'MYR' },
					{ name: 'MZN - Mozambican Metical', value: 'MZN' },
					{ name: 'NAD - Namibian Dollar', value: 'NAD' },
					{ name: 'NGN - Nigerian Naira', value: 'NGN' },
					{ name: 'NIO - Nicaraguan Cordoba', value: 'NIO' },
					{ name: 'NOK - Norwegian Krone', value: 'NOK' },
					{ name: 'NPR - Nepalese Rupee', value: 'NPR' },
					{ name: 'NZD - New Zealand Dollar', value: 'NZD' },
					{ name: 'OMR - Omani Rial', value: 'OMR' },
					{ name: 'PAB - Panamanian Balboa', value: 'PAB' },
					{ name: 'PEN - Peruvian Sol', value: 'PEN' },
					{ name: 'PGK - Papua New Guinean Kina', value: 'PGK' },
					{ name: 'PHP - Philippine Peso', value: 'PHP' },
					{ name: 'PKR - Pakistani Rupee', value: 'PKR' },
					{ name: 'PLN - Polish Zloty', value: 'PLN' },
					{ name: 'PYG - Paraguayan Guarani', value: 'PYG' },
					{ name: 'QAR - Qatari Riyal', value: 'QAR' },
					{ name: 'RON - Romanian Leu', value: 'RON' },
					{ name: 'RSD - Serbian Dinar', value: 'RSD' },
					{ name: 'RUB - Russian Ruble', value: 'RUB' },
					{ name: 'RWF - Rwandan Franc', value: 'RWF' },
					{ name: 'SAR - Saudi Riyal', value: 'SAR' },
					{ name: 'SBD - Solomon Islands Dollar', value: 'SBD' },
					{ name: 'SCR - Seychellois Rupee', value: 'SCR' },
					{ name: 'SDG - Sudanese Pound', value: 'SDG' },
					{ name: 'SEK - Swedish Krona', value: 'SEK' },
					{ name: 'SGD - Singapore Dollar', value: 'SGD' },
					{ name: 'SHP - Saint Helena Pound', value: 'SHP' },
					{ name: 'SLL - Sierra Leonean Leone', value: 'SLL' },
					{ name: 'SOS - Somali Shilling', value: 'SOS' },
					{ name: 'SRD - Surinamese Dollar', value: 'SRD' },
					{ name: 'SSP - South Sudanese Pound', value: 'SSP' },
					{ name: 'STN - São Tomé and Príncipe Dobra', value: 'STN' },
					{ name: 'SVC - Salvadoran Colón', value: 'SVC' },
					{ name: 'SYP - Syrian Pound', value: 'SYP' },
					{ name: 'SZL - Swazi Lilangeni', value: 'SZL' },
					{ name: 'THB - Thai Baht', value: 'THB' },
					{ name: 'TJS - Tajikistani Somoni', value: 'TJS' },
					{ name: 'TMT - Turkmenistani Manat', value: 'TMT' },
					{ name: 'TND - Tunisian Dinar', value: 'TND' },
					{ name: 'TOP - Tongan Paʻanga', value: 'TOP' },
					{ name: 'TRY - Turkish Lira', value: 'TRY' },
					{ name: 'TTD - Trinidad and Tobago Dollar', value: 'TTD' },
					{ name: 'TWD - Taiwan Dollar', value: 'TWD' },
					{ name: 'TZS - Tanzanian Shilling', value: 'TZS' },
					{ name: 'UAH - Ukrainian Hryvnia', value: 'UAH' },
					{ name: 'UGX - Ugandan Shilling', value: 'UGX' },
					{ name: 'USD - US Dollar', value: 'USD' },
					{ name: 'UYU - Uruguayan Peso', value: 'UYU' },
					{ name: 'UZS - Uzbekistani Som', value: 'UZS' },
					{ name: 'VES - Venezuelan Bolivar', value: 'VES' },
					{ name: 'VND - Vietnamese Dong', value: 'VND' },
					{ name: 'VUV - Vanuatu Vatu', value: 'VUV' },
					{ name: 'WST - Samoan Tala', value: 'WST' },
					{ name: 'XAF - CFA Franc BEAC', value: 'XAF' },
					{ name: 'XCD - East Caribbean Dollar', value: 'XCD' },
					{ name: 'XOF - CFA Franc BCEAO', value: 'XOF' },
					{ name: 'XPF - CFP Franc', value: 'XPF' },
					{ name: 'YER - Yemeni Rial', value: 'YER' },
					{ name: 'ZAR - South African Rand', value: 'ZAR' },
					{ name: 'ZMW - Zambian Kwacha', value: 'ZMW' },
					{ name: 'ZWL - Zimbabwean Dollar', value: 'ZWL' },
				],
				default: 'INR',
			},
			{
				displayName: 'Non-Taxable',
				name: 'variant_non_taxable',
				type: 'number',
				default: 0,
				placeholder: 'Enter Non-Taxable',
			},
			{
				displayName: 'SKU ID',
				name: 'variant_sku',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Tax Type',
				name: 'variant_tax_type',
				type: 'options',
				options: [
					{ name: 'Inclusive of Tax', value: 'inclusive of tax' },
					{ name: 'Exclusive of Tax', value: 'exclusive of tax' },
				],
				default: 'inclusive of tax',
			},
			{
				displayName: 'Variant Description',
				name: 'variant_description',
				type: 'string',
				default: '',
			},
		],
	},
];
