import type { INodeProperties } from 'n8n-workflow';
import { getFiscalYearData } from '../GenericFunctions';

export const contactOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		noDataExpression: true,
		name: 'operation',
		type: 'options',
		options: [
			{ name: 'Add Address (Existing Contact)', value: 'addAddress', action: 'Add address to a contact' },
			{ name: 'Create Contact', value: 'createContact', action: 'Create a contact' },
			{ name: 'Get All Contacts', value: 'getAllContacts', action: 'Get all contacts' },
			{ name: 'Get Contact', value: 'getContact', action: 'Get a contact' },
			{ name: 'Update Address (Existing Contact)', value: 'updateAddress', action: 'Update address of a contact' },
			{ name: 'Update Contact', value: 'updateContact', action: 'Update a contact' },
		],
		default: 'createContact',
		displayOptions: {
			show: { resource: ['contact'] },
		},
		description: 'Choose the operation',
	},

	{
		displayName: 'Contact ID',
		name: 'contactId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: { operation: ['getContact', 'updateContact', 'addAddress', 'updateAddress'] },
		},
		description: 'The ID of the contact to work with',
	},

	{
		displayName: 'Contact Name',
		name: 'contactName',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: { operation: ['createContact'] },
		},
	},

	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['createContact'],
			},
		},
		// eslint-disable-next-line n8n-nodes-base/node-param-collection-type-unsorted-items
		options: [
			{
				displayName: 'Billing Address',
				name: 'billing_address',
				type: 'fixedCollection',
				placeholder: 'Add Billing Address',
				default: {},
				typeOptions: {
					multipleValues: true,
				},
				options: [
					{
						displayName: 'Address',
						name: 'address',
						values: [
							{
								displayName: 'Address Line 1',
								name: 'billing_address1',
								type: 'string',
								default: '',
								placeholder: 'Enter address line 1',
							},
							{
								displayName: 'Address Line 2',
								name: 'billing_address2',
								type: 'string',
								default: '',
								placeholder: 'Enter address line 2 (optional)',
							},
							{
								displayName: 'City',
								name: 'billing_city',
								type: 'string',
								default: '',
								placeholder: 'Enter city',
							},
							{
								displayName: 'Country',
								name: 'billing_country',
								type: 'string',
								default: '',
								placeholder: 'Enter country',
							},
							{
								displayName: 'Email',
								name: 'billing_email',
								type: 'string',
								default: '',
								placeholder: 'Enter email (optional)',
							},
							{
								displayName: 'Mobile',
								name: 'billing_mobile',
								type: 'string',
								default: '',
								placeholder: 'Enter mobile number (optional)',
							},
							{
								displayName: 'Postal Code',
								name: 'billing_postalcode',
								type: 'string',
								default: '',
								placeholder: 'Enter postal/pin code',
							},
							{
								displayName: 'State',
								name: 'billing_state',
								type: 'string',
								default: '',
								placeholder: 'Enter state',
							},
							{
								displayName: 'Tax Number',
								name: 'billing_tax',
								type: 'string',
								default: '',
								placeholder: 'Enter tax number',
							},
						],
					},
				],
			},
			{
        displayName: 'Currency', name: 'currency', type: 'options',
				options: [
					{ name: 'AED - UAE Dirham', value: 'AED' },
					{ name: 'AFN - Afghan Afghani', value: 'AFN' },
					{ name: 'ALL - Albanian Lek', value: 'ALL' },
					{ name: 'AMD - Armenian Dram', value: 'AMD' },
					{ name: 'ANG - Netherlands Antillean Guilder', value: 'ANG' },
					{ name: 'AOA - Angolan Kwanza', value: 'AOA' },
					{ name: 'ARS - Argentine Peso', value: 'ARS' },
					{ name: 'AUD - Australian Dollar', value: 'AUD' },
					{ name: 'AWG - Aruban Florin', value: 'AWG' },
					{ name: 'AZN - Azerbaijani Manat', value: 'AZN' },
					{ name: 'BAM - Bosnia and Herzegovina Convertible Mark', value: 'BAM' },
					{ name: 'BBD - Barbadian Dollar', value: 'BBD' },
					{ name: 'BDT - Bangladeshi Taka', value: 'BDT' },
					{ name: 'BGN - Bulgarian Lev', value: 'BGN' },
					{ name: 'BHD - Bahraini Dinar', value: 'BHD' },
					{ name: 'BIF - Burundian Franc', value: 'BIF' },
					{ name: 'BMD - Bermudian Dollar', value: 'BMD' },
					{ name: 'BND - Brunei Dollar', value: 'BND' },
					{ name: 'BOB - Bolivian Boliviano', value: 'BOB' },
					{ name: 'BRL - Brazilian Real', value: 'BRL' },
					{ name: 'BSD - Bahamian Dollar', value: 'BSD' },
					{ name: 'BTN - Bhutanese Ngultrum', value: 'BTN' },
					{ name: 'BWP - Botswana Pula', value: 'BWP' },
					{ name: 'BYN - Belarusian Ruble', value: 'BYN' },
					{ name: 'BZD - Belize Dollar', value: 'BZD' },
					{ name: 'CAD - Canadian Dollar', value: 'CAD' },
					{ name: 'CDF - Congolese Franc', value: 'CDF' },
					{ name: 'CHF - Swiss Franc', value: 'CHF' },
					{ name: 'CLF - Unidad De Fomento', value: 'CLF' },
					{ name: 'CLP - Chilean Peso', value: 'CLP' },
					{ name: 'CNY - Chinese Yuan', value: 'CNY' },
					{ name: 'COP - Colombian Peso', value: 'COP' },
					{ name: 'CRC - Costa Rican Colon', value: 'CRC' },
					{ name: 'CUC - Cuban Convertible Peso', value: 'CUC' },
					{ name: 'CUP - Cuban Peso', value: 'CUP' },
					{ name: 'CVE - Cape Verdean Escudo', value: 'CVE' },
					{ name: 'CZK - Czech Koruna', value: 'CZK' },
					{ name: 'DJF - Djiboutian Franc', value: 'DJF' },
					{ name: 'DKK - Danish Krone', value: 'DKK' },
					{ name: 'DOP - Dominican Peso', value: 'DOP' },
					{ name: 'DZD - Algerian Dinar', value: 'DZD' },
					{ name: 'EGP - Egyptian Pound', value: 'EGP' },
					{ name: 'ERN - Eritrean Nakfa', value: 'ERN' },
					{ name: 'ETB - Ethiopian Birr', value: 'ETB' },
					{ name: 'EUR - Euro', value: 'EUR' },
					{ name: 'FJD - Fijian Dollar', value: 'FJD' },
					{ name: 'FKP - Falkland Islands Pound', value: 'FKP' },
					{ name: 'GBP - British Pound', value: 'GBP' },
					{ name: 'GEL - Georgian Lari', value: 'GEL' },
					{ name: 'GHS - Ghanaian Cedi', value: 'GHS' },
					{ name: 'GIP - Gibraltar Pound', value: 'GIP' },
					{ name: 'GMD - Gambian Dalasi', value: 'GMD' },
					{ name: 'GNF - Guinean Franc', value: 'GNF' },
					{ name: 'GTQ - Guatemalan Quetzal', value: 'GTQ' },
					{ name: 'GYD - Guyanese Dollar', value: 'GYD' },
					{ name: 'HKD - Hong Kong Dollar', value: 'HKD' },
					{ name: 'HNL - Honduran Lempira', value: 'HNL' },
					{ name: 'HRK - Croatian Kuna', value: 'HRK' },
					{ name: 'HTG - Haitian Gourde', value: 'HTG' },
					{ name: 'HUF - Hungarian Forint', value: 'HUF' },
					{ name: 'IDR - Indonesian Rupiah', value: 'IDR' },
					{ name: 'ILS - Israeli New Shekel', value: 'ILS' },
					{ name: 'INR - Indian Rupee', value: 'INR' },
					{ name: 'IQD - Iraqi Dinar', value: 'IQD' },
					{ name: 'IRR - Iranian Rial', value: 'IRR' },
					{ name: 'ISK - Icelandic Króna', value: 'ISK' },
					{ name: 'JMD - Jamaican Dollar', value: 'JMD' },
					{ name: 'JOD - Jordanian Dinar', value: 'JOD' },
					{ name: 'JPY - Japanese Yen', value: 'JPY' },
					{ name: 'KES - Kenyan Shilling', value: 'KES' },
					{ name: 'KGS - Kyrgyzstani Som', value: 'KGS' },
					{ name: 'KHR - Cambodian Riel', value: 'KHR' },
					{ name: 'KMF - Comorian Franc', value: 'KMF' },
					{ name: 'KPW - North Korean Won', value: 'KPW' },
					{ name: 'KRW - South Korean Won', value: 'KRW' },
					{ name: 'KWD - Kuwaiti Dinar', value: 'KWD' },
					{ name: 'KYD - Cayman Islands Dollar', value: 'KYD' },
					{ name: 'KZT - Kazakhstani Tenge', value: 'KZT' },
					{ name: 'LAK - Lao Kip', value: 'LAK' },
					{ name: 'LBP - Lebanese Pound', value: 'LBP' },
					{ name: 'LKR - Sri Lankan Rupee', value: 'LKR' },
					{ name: 'LRD - Liberian Dollar', value: 'LRD' },
					{ name: 'LSL - Lesotho Loti', value: 'LSL' },
					{ name: 'LYD - Libyan Dinar', value: 'LYD' },
					{ name: 'MAD - Moroccan Dirham', value: 'MAD' },
					{ name: 'MDL - Moldovan Leu', value: 'MDL' },
					{ name: 'MGA - Malagasy Ariary', value: 'MGA' },
					{ name: 'MKD - Macedonian Denar', value: 'MKD' },
					{ name: 'MMK - Myanmar Kyat', value: 'MMK' },
					{ name: 'MNT - Mongolian Tugrik', value: 'MNT' },
					{ name: 'MOP - Macanese Pataca', value: 'MOP' },
					{ name: 'MRU - Mauritanian Ouguiya', value: 'MRU' },
					{ name: 'MUR - Mauritian Rupee', value: 'MUR' },
					{ name: 'MVR - Maldivian Rufiyaa', value: 'MVR' },
					{ name: 'MWK - Malawian Kwacha', value: 'MWK' },
					{ name: 'MXN - Mexican Peso', value: 'MXN' },
					{ name: 'MYR - Malaysian Ringgit', value: 'MYR' },
					{ name: 'MZN - Mozambican Metical', value: 'MZN' },
					{ name: 'NAD - Namibian Dollar', value: 'NAD' },
					{ name: 'NGN - Nigerian Naira', value: 'NGN' },
					{ name: 'NIO - Nicaraguan Cordoba', value: 'NIO' },
					{ name: 'NOK - Norwegian Krone', value: 'NOK' },
					{ name: 'NPR - Nepalese Rupee', value: 'NPR' },
					{ name: 'NZD - New Zealand Dollar', value: 'NZD' },
					{ name: 'OMR - Omani Rial', value: 'OMR' },
					{ name: 'PAB - Panamanian Balboa', value: 'PAB' },
					{ name: 'PEN - Peruvian Sol', value: 'PEN' },
					{ name: 'PGK - Papua New Guinean Kina', value: 'PGK' },
					{ name: 'PHP - Philippine Peso', value: 'PHP' },
					{ name: 'PKR - Pakistani Rupee', value: 'PKR' },
					{ name: 'PLN - Polish Zloty', value: 'PLN' },
					{ name: 'PYG - Paraguayan Guarani', value: 'PYG' },
					{ name: 'QAR - Qatari Riyal', value: 'QAR' },
					{ name: 'RON - Romanian Leu', value: 'RON' },
					{ name: 'RSD - Serbian Dinar', value: 'RSD' },
					{ name: 'RUB - Russian Ruble', value: 'RUB' },
					{ name: 'RWF - Rwandan Franc', value: 'RWF' },
					{ name: 'SAR - Saudi Riyal', value: 'SAR' },
					{ name: 'SBD - Solomon Islands Dollar', value: 'SBD' },
					{ name: 'SCR - Seychellois Rupee', value: 'SCR' },
					{ name: 'SDG - Sudanese Pound', value: 'SDG' },
					{ name: 'SEK - Swedish Krona', value: 'SEK' },
					{ name: 'SGD - Singapore Dollar', value: 'SGD' },
					{ name: 'SHP - Saint Helena Pound', value: 'SHP' },
					{ name: 'SLL - Sierra Leonean Leone', value: 'SLL' },
					{ name: 'SOS - Somali Shilling', value: 'SOS' },
					{ name: 'SRD - Surinamese Dollar', value: 'SRD' },
					{ name: 'SSP - South Sudanese Pound', value: 'SSP' },
					{ name: 'STN - São Tomé and Príncipe Dobra', value: 'STN' },
					{ name: 'SVC - Salvadoran Colón', value: 'SVC' },
					{ name: 'SYP - Syrian Pound', value: 'SYP' },
					{ name: 'SZL - Swazi Lilangeni', value: 'SZL' },
					{ name: 'THB - Thai Baht', value: 'THB' },
					{ name: 'TJS - Tajikistani Somoni', value: 'TJS' },
					{ name: 'TMT - Turkmenistani Manat', value: 'TMT' },
					{ name: 'TND - Tunisian Dinar', value: 'TND' },
					{ name: 'TOP - Tongan Paʻanga', value: 'TOP' },
					{ name: 'TRY - Turkish Lira', value: 'TRY' },
					{ name: 'TTD - Trinidad and Tobago Dollar', value: 'TTD' },
					{ name: 'TWD - Taiwan Dollar', value: 'TWD' },
					{ name: 'TZS - Tanzanian Shilling', value: 'TZS' },
					{ name: 'UAH - Ukrainian Hryvnia', value: 'UAH' },
					{ name: 'UGX - Ugandan Shilling', value: 'UGX' },
					{ name: 'USD - US Dollar', value: 'USD' },
					{ name: 'UYU - Uruguayan Peso', value: 'UYU' },
					{ name: 'UZS - Uzbekistani Som', value: 'UZS' },
					{ name: 'VES - Venezuelan Bolivar', value: 'VES' },
					{ name: 'VND - Vietnamese Dong', value: 'VND' },
					{ name: 'VUV - Vanuatu Vatu', value: 'VUV' },
					{ name: 'WST - Samoan Tala', value: 'WST' },
					{ name: 'XAF - CFA Franc BEAC', value: 'XAF' },
					{ name: 'XCD - East Caribbean Dollar', value: 'XCD' },
					{ name: 'XOF - CFA Franc BCEAO', value: 'XOF' },
					{ name: 'XPF - CFP Franc', value: 'XPF' },
					{ name: 'YER - Yemeni Rial', value: 'YER' },
					{ name: 'ZAR - South African Rand', value: 'ZAR' },
					{ name: 'ZMW - Zambian Kwacha', value: 'ZMW' },
					{ name: 'ZWL - Zimbabwean Dollar', value: 'ZWL' },
				],
				default: 'INR',
			},
			{
				displayName: 'Shipping Address',
				name: 'shipping_address',
				type: 'fixedCollection',
				placeholder: 'Add Shipping Address',
				default: {},
				typeOptions: {
					multipleValues: true,
				},
				options: [
					{
						displayName: 'Address',
						name: 'address',
						values: [
							{
								displayName: 'Address Line 1',
								name: 'shipping_address1',
								type: 'string',
								default: '',
								placeholder: 'Enter address line 1',
							},
							{
								displayName: 'Address Line 2',
								name: 'shipping_address2',
								type: 'string',
								default: '',
								placeholder: 'Enter address line 2 (optional)',
							},
							{
								displayName: 'City',
								name: 'shipping_city',
								type: 'string',
								default: '',
								placeholder: 'Enter city',
							},
							{
								displayName: 'Country',
								name: 'shipping_country',
								type: 'string',
								default: '',
								placeholder: 'Enter country',
							},
							{
								displayName: 'Email',
								name: 'shipping_email',
								type: 'string',
								default: '',
								placeholder: 'Enter email (optional)',
							},
							{
								displayName: 'Mobile',
								name: 'shipping_mobile',
								type: 'string',
								default: '',
								placeholder: 'Enter mobile number (optional)',
							},
							{
								displayName: 'Postal Code',
								name: 'shipping_postalcode',
								type: 'string',
								default: '',
								placeholder: 'Enter postal/pin code',
							},
							{
								displayName: 'State',
								name: 'shipping_state',
								type: 'string',
								default: '',
								placeholder: 'Enter state',
							},
							{
								displayName: 'TAX Number',
								name: 'shipping_tax',
								type: 'string',
								default: '',
								placeholder: 'Enter tax number',
							},
						],
					},
				],
			},
			{ displayName: 'Email', name: 'email', type: 'string', default: '', placeholder: '' },
			{
				displayName: 'Mobile Country Code',
				name: 'mobile_country_code',
				type: 'options',
				// eslint-disable-next-line n8n-nodes-base/node-param-options-type-unsorted-items
				options: [
					{ name: '🇦🇪 UAE (+971)', value: 971 },
					{ name: '🇮🇳 India (+91)', value: 91 },
					{ name: '🇺🇸 USA (+1)', value: 1 },
					{ name: '🇬🇧 UK (+44)', value: 44 },
					{ name: '🇸🇦 Saudi Arabia (+966)', value: 966 },
					{ name: '🇶🇦 Qatar (+974)', value: 974 },
					{ name: '🇰🇼 Kuwait (+965)', value: 965 },
					{ name: '🇧🇭 Bahrain (+973)', value: 973 },
					{ name: '🇴🇲 Oman (+968)', value: 968 },
					{ name: '🇯🇴 Jordan (+962)', value: 962 },
					{ name: '🇱🇧 Lebanon (+961)', value: 961 },
					{ name: '🇪🇬 Egypt (+20)', value: 20 },
					{ name: '🇲🇦 Morocco (+212)', value: 212 },
					{ name: '🇹🇳 Tunisia (+216)', value: 216 },
					{ name: '🇩🇿 Algeria (+213)', value: 213 },
					{ name: '🇱🇾 Libya (+218)', value: 218 },
					{ name: '🇸🇩 Sudan (+249)', value: 249 },
					{ name: '🇸🇾 Syria (+963)', value: 963 },
					{ name: '🇾🇪 Yemen (+967)', value: 967 },
					{ name: '🇮🇶 Iraq (+964)', value: 964 },
					{ name: '🇮🇷 Iran (+98)', value: 98 },
					{ name: '🇦🇫 Afghanistan (+93)', value: 93 },
					{ name: '🇵🇰 Pakistan (+92)', value: 92 },
					{ name: '🇧🇩 Bangladesh (+880)', value: 880 },
					{ name: '🇱🇰 Sri Lanka (+94)', value: 94 },
					{ name: '🇳🇵 Nepal (+977)', value: 977 },
					{ name: '🇧🇹 Bhutan (+975)', value: 975 },
					{ name: '🇲🇲 Myanmar (+95)', value: 95 },
					{ name: '🇹🇭 Thailand (+66)', value: 66 },
					{ name: '🇻🇳 Vietnam (+84)', value: 84 },
					{ name: '🇰🇭 Cambodia (+855)', value: 855 },
					{ name: '🇱🇦 Laos (+856)', value: 856 },
					{ name: '🇲🇳 Mongolia (+976)', value: 976 },
					{ name: '🇨🇳 China (+86)', value: 86 },
					{ name: '🇯🇵 Japan (+81)', value: 81 },
					{ name: '🇰🇷 South Korea (+82)', value: 82 },
					{ name: '🇹🇼 Taiwan (+886)', value: 886 },
					{ name: '🇭🇰 Hong Kong (+852)', value: 852 },
					{ name: '🇸🇬 Singapore (+65)', value: 65 },
					{ name: '🇲🇾 Malaysia (+60)', value: 60 },
					{ name: '🇮🇩 Indonesia (+62)', value: 62 },
					{ name: '🇵🇭 Philippines (+63)', value: 63 },
					{ name: '🇧🇷 Brazil (+55)', value: 55 },
					{ name: '🇦🇷 Argentina (+54)', value: 54 },
					{ name: '🇨🇱 Chile (+56)', value: 56 },
					{ name: '🇨🇴 Colombia (+57)', value: 57 },
					{ name: '🇵🇪 Peru (+51)', value: 51 },
					{ name: '🇺🇾 Uruguay (+598)', value: 598 },
					{ name: '🇻🇪 Venezuela (+58)', value: 58 },
					{ name: '🇲🇽 Mexico (+52)', value: 52 },
					{ name: '🇨🇦 Canada (+1)', value: 1 },
					{ name: '🇦🇺 Australia (+61)', value: 61 },
					{ name: '🇳🇿 New Zealand (+64)', value: 64 },
					{ name: '🇿🇦 South Africa (+27)', value: 27 },
					{ name: '🇳🇬 Nigeria (+234)', value: 234 },
					{ name: '🇰🇪 Kenya (+254)', value: 254 },
					{ name: '🇬🇭 Ghana (+233)', value: 233 },
					{ name: '🇺🇬 Uganda (+256)', value: 256 },
					{ name: '🇹🇿 Tanzania (+255)', value: 255 },
					{ name: '🇪🇹 Ethiopia (+251)', value: 251 },
					{ name: '🇩🇪 Germany (+49)', value: 49 },
					{ name: '🇫🇷 France (+33)', value: 33 },
					{ name: '🇮🇹 Italy (+39)', value: 39 },
					{ name: '🇪🇸 Spain (+34)', value: 34 },
					{ name: '🇵🇱 Poland (+48)', value: 48 },
					{ name: '🇷🇺 Russia (+7)', value: 7 },
					{ name: '🇹🇷 Turkey (+90)', value: 90 },
					{ name: '🇳🇱 Netherlands (+31)', value: 31 },
					{ name: '🇧🇪 Belgium (+32)', value: 32 },
					{ name: '🇨🇭 Switzerland (+41)', value: 41 },
					{ name: '🇦🇹 Austria (+43)', value: 43 },
					{ name: '🇸🇪 Sweden (+46)', value: 46 },
					{ name: '🇳🇴 Norway (+47)', value: 47 },
					{ name: '🇩🇰 Denmark (+45)', value: 45 },
					{ name: '🇫🇮 Finland (+358)', value: 358 },
					{ name: '🇮🇸 Iceland (+354)', value: 354 },
					{ name: '🇮🇪 Ireland (+353)', value: 353 },
					{ name: '🇵🇹 Portugal (+351)', value: 351 },
					{ name: '🇬🇷 Greece (+30)', value: 30 },
					{ name: '🇭🇺 Hungary (+36)', value: 36 },
					{ name: '🇨🇿 Czech Republic (+420)', value: 420 },
					{ name: '🇸🇰 Slovakia (+421)', value: 421 },
					{ name: '🇸🇮 Slovenia (+386)', value: 386 },
					{ name: '🇭🇷 Croatia (+385)', value: 385 },
					{ name: '🇷🇸 Serbia (+381)', value: 381 },
					{ name: '🇧🇬 Bulgaria (+359)', value: 359 },
					{ name: '🇷🇴 Romania (+40)', value: 40 },
					{ name: '🇺🇦 Ukraine (+380)', value: 380 },
					{ name: '🇧🇾 Belarus (+375)', value: 375 },
					{ name: '🇱🇹 Lithuania (+370)', value: 370 },
					{ name: '🇱🇻 Latvia (+371)', value: 371 },
					{ name: '🇪🇪 Estonia (+372)', value: 372 },
					{ name: '🇲🇩 Moldova (+373)', value: 373 },
					{ name: '🇦🇲 Armenia (+374)', value: 374 },
					{ name: '🇬🇪 Georgia (+995)', value: 995 },
					{ name: '🇦🇿 Azerbaijan (+994)', value: 994 },
					{ name: '🇰🇿 Kazakhstan (+7)', value: 7 },
					{ name: '🇺🇿 Uzbekistan (+998)', value: 998 },
					{ name: '🇰🇬 Kyrgyzstan (+996)', value: 996 },
				],
				default: 91,
				description: 'Select the country code for the mobile number',
			},
			{ displayName: 'Mobile', name: 'mobile', type: 'string', default: '', placeholder: '' },
			{ displayName: 'Tax Number', name: 'tax', type: 'string', default: '', placeholder: '' },
			{
				displayName: 'Opening Customer Receivable',
				name: 'opening_customer_receivable_group',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: false,
				},
				default: {},
				options: [
					{
						displayName: 'Customer Receivable',
						name: 'customer_receivable',
						values: [
							{
								displayName: 'Amount',
								name: 'amount',
								type: 'string',
								default: '',
								description: 'Enter the opening customer receivable amount',
							},
							{
								displayName: 'Financial Year',
								name: 'fiscal_year',
								type: 'options',
								options: getFiscalYearData().options,
								default: '',
								description: 'Select the financial year',
							},
						],
					},
				],
			},
			{
				displayName: 'Opening Supplier Payable',
				name: 'opening_supplier_payable_group',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: false,
				},
				default: {},
				options: [
					{
						displayName: 'Supplier Payable',
						name: 'supplier_payable',
						values: [
							{
								displayName: 'Amount',
								name: 'amount',
								type: 'string',
								default: '',
								description: 'Enter the opening supplier payable amount',
							},
							{
								displayName: 'Financial Year',
								name: 'fiscal_year',
								type: 'options',
								options: getFiscalYearData().options,
								default: '',
								description: 'Select the financial year',
							},
						],
					},
				],
			},
			{ displayName: 'PAN (India Only)', name: 'pan', type: 'string', default: '', placeholder: '' },
			{
				displayName: 'Business Name',
				name: 'business_name',
				type: 'string',
				default: '',
				placeholder: '',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Inactive', value: 'inactive' },
				],
				default: 'active',
			},
		],
	},

	{
		displayName: 'Additional Fields',
		name: 'contactAdditionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['updateContact'],
			},
		},
		// eslint-disable-next-line n8n-nodes-base/node-param-collection-type-unsorted-items
		options: [
			{ displayName: 'Email', name: 'email', type: 'string', default: '', placeholder: '' },
			{
				displayName: 'Mobile Country Code',
				name: 'mobile_country_code',
				type: 'options',
				options: [
					{ name: '🇦🇪 UAE (+971)', value: 971 },
					{ name: '🇮🇳 India (+91)', value: 91 },
					{ name: '🇺🇸 USA (+1)', value: 1 },
					{ name: '🇬🇧 UK (+44)', value: 44 },
					{ name: '🇸🇦 Saudi Arabia (+966)', value: 966 },
					{ name: '🇶🇦 Qatar (+974)', value: 974 },
					{ name: '🇰🇼 Kuwait (+965)', value: 965 },
					{ name: '🇧🇭 Bahrain (+973)', value: 973 },
					{ name: '🇴🇲 Oman (+968)', value: 968 },
					{ name: '🇯🇴 Jordan (+962)', value: 962 },
					{ name: '🇱🇧 Lebanon (+961)', value: 961 },
					{ name: '🇪🇬 Egypt (+20)', value: 20 },
					{ name: '🇲🇦 Morocco (+212)', value: 212 },
					{ name: '🇹🇳 Tunisia (+216)', value: 216 },
					{ name: '🇩🇿 Algeria (+213)', value: 213 },
					{ name: '🇱🇾 Libya (+218)', value: 218 },
					{ name: '🇸🇩 Sudan (+249)', value: 249 },
					{ name: '🇸🇾 Syria (+963)', value: 963 },
					{ name: '🇾🇪 Yemen (+967)', value: 967 },
					{ name: '🇮🇶 Iraq (+964)', value: 964 },
					{ name: '🇮🇷 Iran (+98)', value: 98 },
					{ name: '🇦🇫 Afghanistan (+93)', value: 93 },
					{ name: '🇵🇰 Pakistan (+92)', value: 92 },
					{ name: '🇧🇩 Bangladesh (+880)', value: 880 },
					{ name: '🇱🇰 Sri Lanka (+94)', value: 94 },
					{ name: '🇳🇵 Nepal (+977)', value: 977 },
					{ name: '🇧🇹 Bhutan (+975)', value: 975 },
					{ name: '🇲🇲 Myanmar (+95)', value: 95 },
					{ name: '🇹🇭 Thailand (+66)', value: 66 },
					{ name: '🇻🇳 Vietnam (+84)', value: 84 },
					{ name: '🇰🇭 Cambodia (+855)', value: 855 },
					{ name: '🇱🇦 Laos (+856)', value: 856 },
					{ name: '🇲🇳 Mongolia (+976)', value: 976 },
					{ name: '🇨🇳 China (+86)', value: 86 },
					{ name: '🇯🇵 Japan (+81)', value: 81 },
					{ name: '🇰🇷 South Korea (+82)', value: 82 },
					{ name: '🇹🇼 Taiwan (+886)', value: 886 },
					{ name: '🇭🇰 Hong Kong (+852)', value: 852 },
					{ name: '🇸🇬 Singapore (+65)', value: 65 },
					{ name: '🇲🇾 Malaysia (+60)', value: 60 },
					{ name: '🇮🇩 Indonesia (+62)', value: 62 },
					{ name: '🇵🇭 Philippines (+63)', value: 63 },
					{ name: '🇧🇷 Brazil (+55)', value: 55 },
					{ name: '🇦🇷 Argentina (+54)', value: 54 },
					{ name: '🇨🇱 Chile (+56)', value: 56 },
					{ name: '🇨🇴 Colombia (+57)', value: 57 },
					{ name: '🇵🇪 Peru (+51)', value: 51 },
					{ name: '🇺🇾 Uruguay (+598)', value: 598 },
					{ name: '🇻🇪 Venezuela (+58)', value: 58 },
					{ name: '🇲🇽 Mexico (+52)', value: 52 },
					{ name: '🇨🇦 Canada (+1)', value: 1 },
					{ name: '🇦🇺 Australia (+61)', value: 61 },
					{ name: '🇳🇿 New Zealand (+64)', value: 64 },
					{ name: '🇿🇦 South Africa (+27)', value: 27 },
					{ name: '🇳🇬 Nigeria (+234)', value: 234 },
					{ name: '🇰🇪 Kenya (+254)', value: 254 },
					{ name: '🇬🇭 Ghana (+233)', value: 233 },
					{ name: '🇺🇬 Uganda (+256)', value: 256 },
					{ name: '🇹🇿 Tanzania (+255)', value: 255 },
					{ name: '🇪🇹 Ethiopia (+251)', value: 251 },
					{ name: '🇩🇪 Germany (+49)', value: 49 },
					{ name: '🇫🇷 France (+33)', value: 33 },
					{ name: '🇮🇹 Italy (+39)', value: 39 },
					{ name: '🇪🇸 Spain (+34)', value: 34 },
					{ name: '🇵🇱 Poland (+48)', value: 48 },
					{ name: '🇷🇺 Russia (+7)', value: 7 },
					{ name: '🇹🇷 Turkey (+90)', value: 90 },
					{ name: '🇳🇱 Netherlands (+31)', value: 31 },
					{ name: '🇧🇪 Belgium (+32)', value: 32 },
					{ name: '🇨🇭 Switzerland (+41)', value: 41 },
					{ name: '🇦🇹 Austria (+43)', value: 43 },
					{ name: '🇸🇪 Sweden (+46)', value: 46 },
					{ name: '🇳🇴 Norway (+47)', value: 47 },
					{ name: '🇩🇰 Denmark (+45)', value: 45 },
					{ name: '🇫🇮 Finland (+358)', value: 358 },
					{ name: '🇮🇸 Iceland (+354)', value: 354 },
					{ name: '🇮🇪 Ireland (+353)', value: 353 },
					{ name: '🇵🇹 Portugal (+351)', value: 351 },
					{ name: '🇬🇷 Greece (+30)', value: 30 },
					{ name: '🇭🇺 Hungary (+36)', value: 36 },
					{ name: '🇨🇿 Czech Republic (+420)', value: 420 },
					{ name: '🇸🇰 Slovakia (+421)', value: 421 },
					{ name: '🇸🇮 Slovenia (+386)', value: 386 },
					{ name: '🇭🇷 Croatia (+385)', value: 385 },
					{ name: '🇷🇸 Serbia (+381)', value: 381 },
					{ name: '🇧🇬 Bulgaria (+359)', value: 359 },
					{ name: '🇷🇴 Romania (+40)', value: 40 },
					{ name: '🇺🇦 Ukraine (+380)', value: 380 },
					{ name: '🇧🇾 Belarus (+375)', value: 375 },
					{ name: '🇱🇹 Lithuania (+370)', value: 370 },
					{ name: '🇱🇻 Latvia (+371)', value: 371 },
					{ name: '🇪🇪 Estonia (+372)', value: 372 },
					{ name: '🇲🇩 Moldova (+373)', value: 373 },
					{ name: '🇦🇲 Armenia (+374)', value: 374 },
					{ name: '🇬🇪 Georgia (+995)', value: 995 },
					{ name: '🇦🇿 Azerbaijan (+994)', value: 994 },
					{ name: '🇰🇿 Kazakhstan (+7)', value: 7 },
					{ name: '🇺🇿 Uzbekistan (+998)', value: 998 },
					{ name: '🇰🇬 Kyrgyzstan (+996)', value: 996 },
				],
				default: 91,
			},
			{ displayName: 'Mobile', name: 'mobile', type: 'string', default: '', placeholder: '' },
			{ displayName: 'TAX Number', name: 'tax', type: 'string', default: '', placeholder: '' },
			{ displayName: 'PAN (India Only)', name: 'pan', type: 'string', default: '', placeholder: '' },
			{
        displayName: 'Currency', name: 'currency', type: 'options',
				options: [
					{ name: 'AED - UAE Dirham', value: 'AED' },
					{ name: 'AFN - Afghan Afghani', value: 'AFN' },
					{ name: 'ALL - Albanian Lek', value: 'ALL' },
					{ name: 'AMD - Armenian Dram', value: 'AMD' },
					{ name: 'ANG - Netherlands Antillean Guilder', value: 'ANG' },
					{ name: 'AOA - Angolan Kwanza', value: 'AOA' },
					{ name: 'ARS - Argentine Peso', value: 'ARS' },
					{ name: 'AUD - Australian Dollar', value: 'AUD' },
					{ name: 'AWG - Aruban Florin', value: 'AWG' },
					{ name: 'AZN - Azerbaijani Manat', value: 'AZN' },
					{ name: 'BAM - Bosnia and Herzegovina Convertible Mark', value: 'BAM' },
					{ name: 'BBD - Barbadian Dollar', value: 'BBD' },
					{ name: 'BDT - Bangladeshi Taka', value: 'BDT' },
					{ name: 'BGN - Bulgarian Lev', value: 'BGN' },
					{ name: 'BHD - Bahraini Dinar', value: 'BHD' },
					{ name: 'BIF - Burundian Franc', value: 'BIF' },
					{ name: 'BMD - Bermudian Dollar', value: 'BMD' },
					{ name: 'BND - Brunei Dollar', value: 'BND' },
					{ name: 'BOB - Bolivian Boliviano', value: 'BOB' },
					{ name: 'BRL - Brazilian Real', value: 'BRL' },
					{ name: 'BSD - Bahamian Dollar', value: 'BSD' },
					{ name: 'BTN - Bhutanese Ngultrum', value: 'BTN' },
					{ name: 'BWP - Botswana Pula', value: 'BWP' },
					{ name: 'BYN - Belarusian Ruble', value: 'BYN' },
					{ name: 'BZD - Belize Dollar', value: 'BZD' },
					{ name: 'CAD - Canadian Dollar', value: 'CAD' },
					{ name: 'CDF - Congolese Franc', value: 'CDF' },
					{ name: 'CHF - Swiss Franc', value: 'CHF' },
					{ name: 'CLF - Unidad De Fomento', value: 'CLF' },
					{ name: 'CLP - Chilean Peso', value: 'CLP' },
					{ name: 'CNY - Chinese Yuan', value: 'CNY' },
					{ name: 'COP - Colombian Peso', value: 'COP' },
					{ name: 'CRC - Costa Rican Colon', value: 'CRC' },
					{ name: 'CUC - Cuban Convertible Peso', value: 'CUC' },
					{ name: 'CUP - Cuban Peso', value: 'CUP' },
					{ name: 'CVE - Cape Verdean Escudo', value: 'CVE' },
					{ name: 'CZK - Czech Koruna', value: 'CZK' },
					{ name: 'DJF - Djiboutian Franc', value: 'DJF' },
					{ name: 'DKK - Danish Krone', value: 'DKK' },
					{ name: 'DOP - Dominican Peso', value: 'DOP' },
					{ name: 'DZD - Algerian Dinar', value: 'DZD' },
					{ name: 'EGP - Egyptian Pound', value: 'EGP' },
					{ name: 'ERN - Eritrean Nakfa', value: 'ERN' },
					{ name: 'ETB - Ethiopian Birr', value: 'ETB' },
					{ name: 'EUR - Euro', value: 'EUR' },
					{ name: 'FJD - Fijian Dollar', value: 'FJD' },
					{ name: 'FKP - Falkland Islands Pound', value: 'FKP' },
					{ name: 'GBP - British Pound', value: 'GBP' },
					{ name: 'GEL - Georgian Lari', value: 'GEL' },
					{ name: 'GHS - Ghanaian Cedi', value: 'GHS' },
					{ name: 'GIP - Gibraltar Pound', value: 'GIP' },
					{ name: 'GMD - Gambian Dalasi', value: 'GMD' },
					{ name: 'GNF - Guinean Franc', value: 'GNF' },
					{ name: 'GTQ - Guatemalan Quetzal', value: 'GTQ' },
					{ name: 'GYD - Guyanese Dollar', value: 'GYD' },
					{ name: 'HKD - Hong Kong Dollar', value: 'HKD' },
					{ name: 'HNL - Honduran Lempira', value: 'HNL' },
					{ name: 'HRK - Croatian Kuna', value: 'HRK' },
					{ name: 'HTG - Haitian Gourde', value: 'HTG' },
					{ name: 'HUF - Hungarian Forint', value: 'HUF' },
					{ name: 'IDR - Indonesian Rupiah', value: 'IDR' },
					{ name: 'ILS - Israeli New Shekel', value: 'ILS' },
					{ name: 'INR - Indian Rupee', value: 'INR' },
					{ name: 'IQD - Iraqi Dinar', value: 'IQD' },
					{ name: 'IRR - Iranian Rial', value: 'IRR' },
					{ name: 'ISK - Icelandic Króna', value: 'ISK' },
					{ name: 'JMD - Jamaican Dollar', value: 'JMD' },
					{ name: 'JOD - Jordanian Dinar', value: 'JOD' },
					{ name: 'JPY - Japanese Yen', value: 'JPY' },
					{ name: 'KES - Kenyan Shilling', value: 'KES' },
					{ name: 'KGS - Kyrgyzstani Som', value: 'KGS' },
					{ name: 'KHR - Cambodian Riel', value: 'KHR' },
					{ name: 'KMF - Comorian Franc', value: 'KMF' },
					{ name: 'KPW - North Korean Won', value: 'KPW' },
					{ name: 'KRW - South Korean Won', value: 'KRW' },
					{ name: 'KWD - Kuwaiti Dinar', value: 'KWD' },
					{ name: 'KYD - Cayman Islands Dollar', value: 'KYD' },
					{ name: 'KZT - Kazakhstani Tenge', value: 'KZT' },
					{ name: 'LAK - Lao Kip', value: 'LAK' },
					{ name: 'LBP - Lebanese Pound', value: 'LBP' },
					{ name: 'LKR - Sri Lankan Rupee', value: 'LKR' },
					{ name: 'LRD - Liberian Dollar', value: 'LRD' },
					{ name: 'LSL - Lesotho Loti', value: 'LSL' },
					{ name: 'LYD - Libyan Dinar', value: 'LYD' },
					{ name: 'MAD - Moroccan Dirham', value: 'MAD' },
					{ name: 'MDL - Moldovan Leu', value: 'MDL' },
					{ name: 'MGA - Malagasy Ariary', value: 'MGA' },
					{ name: 'MKD - Macedonian Denar', value: 'MKD' },
					{ name: 'MMK - Myanmar Kyat', value: 'MMK' },
					{ name: 'MNT - Mongolian Tugrik', value: 'MNT' },
					{ name: 'MOP - Macanese Pataca', value: 'MOP' },
					{ name: 'MRU - Mauritanian Ouguiya', value: 'MRU' },
					{ name: 'MUR - Mauritian Rupee', value: 'MUR' },
					{ name: 'MVR - Maldivian Rufiyaa', value: 'MVR' },
					{ name: 'MWK - Malawian Kwacha', value: 'MWK' },
					{ name: 'MXN - Mexican Peso', value: 'MXN' },
					{ name: 'MYR - Malaysian Ringgit', value: 'MYR' },
					{ name: 'MZN - Mozambican Metical', value: 'MZN' },
					{ name: 'NAD - Namibian Dollar', value: 'NAD' },
					{ name: 'NGN - Nigerian Naira', value: 'NGN' },
					{ name: 'NIO - Nicaraguan Cordoba', value: 'NIO' },
					{ name: 'NOK - Norwegian Krone', value: 'NOK' },
					{ name: 'NPR - Nepalese Rupee', value: 'NPR' },
					{ name: 'NZD - New Zealand Dollar', value: 'NZD' },
					{ name: 'OMR - Omani Rial', value: 'OMR' },
					{ name: 'PAB - Panamanian Balboa', value: 'PAB' },
					{ name: 'PEN - Peruvian Sol', value: 'PEN' },
					{ name: 'PGK - Papua New Guinean Kina', value: 'PGK' },
					{ name: 'PHP - Philippine Peso', value: 'PHP' },
					{ name: 'PKR - Pakistani Rupee', value: 'PKR' },
					{ name: 'PLN - Polish Zloty', value: 'PLN' },
					{ name: 'PYG - Paraguayan Guarani', value: 'PYG' },
					{ name: 'QAR - Qatari Riyal', value: 'QAR' },
					{ name: 'RON - Romanian Leu', value: 'RON' },
					{ name: 'RSD - Serbian Dinar', value: 'RSD' },
					{ name: 'RUB - Russian Ruble', value: 'RUB' },
					{ name: 'RWF - Rwandan Franc', value: 'RWF' },
					{ name: 'SAR - Saudi Riyal', value: 'SAR' },
					{ name: 'SBD - Solomon Islands Dollar', value: 'SBD' },
					{ name: 'SCR - Seychellois Rupee', value: 'SCR' },
					{ name: 'SDG - Sudanese Pound', value: 'SDG' },
					{ name: 'SEK - Swedish Krona', value: 'SEK' },
					{ name: 'SGD - Singapore Dollar', value: 'SGD' },
					{ name: 'SHP - Saint Helena Pound', value: 'SHP' },
					{ name: 'SLL - Sierra Leonean Leone', value: 'SLL' },
					{ name: 'SOS - Somali Shilling', value: 'SOS' },
					{ name: 'SRD - Surinamese Dollar', value: 'SRD' },
					{ name: 'SSP - South Sudanese Pound', value: 'SSP' },
					{ name: 'STN - São Tomé and Príncipe Dobra', value: 'STN' },
					{ name: 'SVC - Salvadoran Colón', value: 'SVC' },
					{ name: 'SYP - Syrian Pound', value: 'SYP' },
					{ name: 'SZL - Swazi Lilangeni', value: 'SZL' },
					{ name: 'THB - Thai Baht', value: 'THB' },
					{ name: 'TJS - Tajikistani Somoni', value: 'TJS' },
					{ name: 'TMT - Turkmenistani Manat', value: 'TMT' },
					{ name: 'TND - Tunisian Dinar', value: 'TND' },
					{ name: 'TOP - Tongan Paʻanga', value: 'TOP' },
					{ name: 'TRY - Turkish Lira', value: 'TRY' },
					{ name: 'TTD - Trinidad and Tobago Dollar', value: 'TTD' },
					{ name: 'TWD - Taiwan Dollar', value: 'TWD' },
					{ name: 'TZS - Tanzanian Shilling', value: 'TZS' },
					{ name: 'UAH - Ukrainian Hryvnia', value: 'UAH' },
					{ name: 'UGX - Ugandan Shilling', value: 'UGX' },
					{ name: 'USD - US Dollar', value: 'USD' },
					{ name: 'UYU - Uruguayan Peso', value: 'UYU' },
					{ name: 'UZS - Uzbekistani Som', value: 'UZS' },
					{ name: 'VES - Venezuelan Bolivar', value: 'VES' },
					{ name: 'VND - Vietnamese Dong', value: 'VND' },
					{ name: 'VUV - Vanuatu Vatu', value: 'VUV' },
					{ name: 'WST - Samoan Tala', value: 'WST' },
					{ name: 'XAF - CFA Franc BEAC', value: 'XAF' },
					{ name: 'XCD - East Caribbean Dollar', value: 'XCD' },
					{ name: 'XOF - CFA Franc BCEAO', value: 'XOF' },
					{ name: 'XPF - CFP Franc', value: 'XPF' },
					{ name: 'YER - Yemeni Rial', value: 'YER' },
					{ name: 'ZAR - South African Rand', value: 'ZAR' },
					{ name: 'ZMW - Zambian Kwacha', value: 'ZMW' },
					{ name: 'ZWL - Zimbabwean Dollar', value: 'ZWL' },
				],
				default: 'INR',
			},
			{
				displayName: 'Business Name',
				name: 'business_name',
				type: 'string',
				default: '',
				placeholder: '',
			},
			{
				displayName: 'Opening Customer Receivable',
				name: 'opening_customer_receivable_group',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: false,
				},
				default: {},
				options: [
					{
						displayName: 'Customer Receivable',
						name: 'customer_receivable',
						values: [
							{
								displayName: 'Amount',
								name: 'amount',
								type: 'string',
								default: '',
								description: 'Enter the opening customer receivable amount',
							},
							{
								displayName: 'Financial Year',
								name: 'fiscal_year',
								type: 'options',
								options: getFiscalYearData().options,
								default: '',
								description: 'Select the financial year',
							},
						],
					},
				],
			},
			{
				displayName: 'Opening Supplier Payable',
				name: 'opening_supplier_payable_group',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: false,
				},
				default: {},
				options: [
					{
						displayName: 'Supplier Payable',
						name: 'supplier_payable',
						values: [
							{
								displayName: 'Amount',
								name: 'amount',
								type: 'string',
								default: '',
								description: 'Enter the opening supplier payable amount',
							},
							{
								displayName: 'Financial Year',
								name: 'fiscal_year',
								type: 'options',
								options: getFiscalYearData().options,
								default: '',
								description: 'Select the financial year',
							},
						],
					},
				],
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Inactive', value: 'inactive' },
				],
				default: 'active',
			},
		],
	},

	{
		displayName: 'Address Type',
		name: 'addressType',
		type: 'options',
		options: [
			{ name: 'Billing Address', value: 'billing' },
			{ name: 'Shipping Address', value: 'shipping' },
			{ name: 'Both (Billing & Shipping)', value: 'both' },
		],
		default: 'billing',
		displayOptions: {
			show: { operation: ['addAddress'] },
		},
		description: 'Type of address to add (can add to both billing and shipping at the same time)',
	},

	{
		displayName: 'Address Type',
		name: 'addressType',
		type: 'options',
		options: [
			{ name: 'Billing Address', value: 'billing' },
			{ name: 'Shipping Address', value: 'shipping' },
		],
		default: 'billing',
		displayOptions: {
			show: { operation: ['updateAddress'] },
		},
		description: 'Type of address to update (one type at a time)',
	},

	{
		displayName: 'Address Name or ID',
		name: 'addressSelector',
		type: 'options',
		default: '',
		displayOptions: {
			show: { operation: ['updateAddress'] },
		},
		typeOptions: {
			loadOptionsMethod: 'getAddressOptions',
			loadOptionsDependsOn: ['contactId', 'addressType'],
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},

	{
		displayName: 'Update Fields',
		name: 'addressUpdateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['updateAddress'],
			},
		},
		// eslint-disable-next-line n8n-nodes-base/node-param-collection-type-unsorted-items
		options: [
			{
				displayName: 'Address Line 1',
				name: 'address1',
				type: 'string',
				default: '',
				placeholder: 'Enter address line 1',
			},
			{
				displayName: 'Address Line 2',
				name: 'address2',
				type: 'string',
				default: '',
				placeholder: 'Enter address line 2 (optional)',
			},
			{
				displayName: 'City',
				name: 'location',
				type: 'string',
				default: '',
				placeholder: 'Enter city',
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				default: '',
				placeholder: 'Enter country',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				default: '',
				placeholder: 'Enter email (optional)',
			},
			{
				displayName: 'Mobile',
				name: 'mobile',
				type: 'string',
				default: '',
				placeholder: 'Enter mobile (optional)',
			},
			{
				displayName: 'Postal Code',
				name: 'postalCode',
				type: 'string',
				default: '',
				placeholder: 'Enter postal/pin code',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
				placeholder: 'Enter state',
			},
			{
				displayName: 'TAX Number',
				name: 'tax',
				type: 'string',
				default: '',
				placeholder: 'Enter tax number',
			},
		],
	},

	{
		displayName: 'Address Fields',
		name: 'addressFields',
		type: 'collection',
		placeholder: 'Add Address Field',
		default: {},
		displayOptions: {
			show: { operation: ['addAddress'] },
		},
		options: [
			{
				displayName: 'Address Line 1',
				name: 'address1',
				type: 'string',
				default: '',
				placeholder: 'Enter address line 1',
			},
			{
				displayName: 'Address Line 2',
				name: 'address2',
				type: 'string',
				default: '',
				placeholder: 'Enter address line 2 (optional)',
			},
			{
				displayName: 'City',
				name: 'location',
				type: 'string',
				default: '',
				placeholder: 'Enter city',
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				default: '',
				placeholder: 'Enter country',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				default: '',
				placeholder: 'Enter email (optional)',
			},
			{
				displayName: 'Mobile',
				name: 'mobile',
				type: 'string',
				default: '',
				placeholder: 'Enter mobile (optional)',
			},
			{
				displayName: 'Postal Code',
				name: 'postalcode',
				type: 'string',
				default: '',
				placeholder: 'Enter postal/pin code',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
				placeholder: 'Enter state',
			},
			{
				displayName: 'Tax Number',
				name: 'tax',
				type: 'string',
				default: '',
				placeholder: 'Enter tax number',
			},
		],
	},

	{
		displayName: 'Search Type',
		name: 'searchType',
		type: 'options',
		options: [
			{ name: 'Search by Name', value: 'name' },
			{ name: 'Search by Limit', value: 'limit' },
		],
		default: 'limit',
		displayOptions: {
			show: {
				operation: ['getAllContacts'],
			},
		},
	},

	{
		displayName: 'Search Term',
		name: 'searchTerm',
		type: 'string',
		default: '',
		placeholder: 'Enter name to search',
		displayOptions: {
			show: {
				operation: ['getAllContacts'],
				searchType: ['name'],
			},
		},
	},

	{
		displayName: 'Limit (Per Page)',
		name: 'perPage',
		type: 'number',
		default: 5,
		displayOptions: {
			show: {
				operation: ['getAllContacts'],
				searchType: ['name', 'limit'],
			},
		},
	},
];
