import type { INodeProperties } from 'n8n-workflow';
import { getFiscalYearData } from '../GenericFunctions';

export const contactOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		noDataExpression: true,
		name: 'operation',
		type: 'options',
		options: [
			{ name: 'Add Address (Existing Contact)', value: 'addAddress', action: 'Add address to a contact' },
			{ name: 'Create Contact', value: 'createContact', action: 'Create a contact' },
			{ name: 'Get All Contacts', value: 'getAllContacts', action: 'Get all contacts' },
			{ name: 'Get Contact', value: 'getContact', action: 'Get a contact' },
			{ name: 'Update Address (Existing Contact)', value: 'updateAddress', action: 'Update address of a contact' },
			{ name: 'Update Contact', value: 'updateContact', action: 'Update a contact' },
		],
		default: 'createContact',
		displayOptions: {
			show: { resource: ['contact'] },
		},
		description: 'Choose the operation',
	},

	{
		displayName: 'Contact ID',
		name: 'contactId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: { operation: ['getContact', 'updateContact', 'addAddress', 'updateAddress'] },
		},
		description: 'The ID of the contact to work with',
	},

	{
		displayName: 'Contact Name',
		name: 'contactName',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: { operation: ['createContact'] },
		},
	},

	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['createContact'],
			},
		},
		// eslint-disable-next-line n8n-nodes-base/node-param-collection-type-unsorted-items
		options: [
			{
				displayName: 'Billing Address',
				name: 'billing_address',
				type: 'fixedCollection',
				placeholder: 'Add Billing Address',
				default: {},
				typeOptions: {
					multipleValues: true,
				},
				options: [
					{
						displayName: 'Address',
						name: 'address',
						values: [
							{
								displayName: 'Address Line 1',
								name: 'billing_address1',
								type: 'string',
								default: '',
							},
							{
								displayName: 'Address Line 2',
								name: 'billing_address2',
								type: 'string',
								default: '',
							},
							{
								displayName: 'City',
								name: 'billing_city',
								type: 'string',
								default: '',
							},
							{
								displayName: 'Country',
								name: 'billing_country',
								type: 'string',
								default: '',
								placeholder: 'Enter country name',
							},
							{
								displayName: 'Email',
								name: 'billing_email',
								type: 'string',
								default: '',
								placeholder: 'Enter email',
							},
							{
								displayName: 'Mobile',
								name: 'billing_mobile',
								type: 'string',
								default: '',
								placeholder: 'Enter mobile number',
							},
							{
								displayName: 'Postal Code',
								name: 'billing_postalcode',
								type: 'string',
								default: '',
								placeholder: 'Enter postal code',
							},
							{
								displayName: 'State',
								name: 'billing_state',
								type: 'string',
								default: '',
								placeholder: 'Enter state name',
							},
							{
								displayName: 'TAX Number',
								name: 'billing_tax',
								type: 'string',
								default: '',
								placeholder: 'Enter TAX Number',
							},
						],
					},
				],
			},
			{
				displayName: 'Shipping Address',
				name: 'shipping_address',
				type: 'fixedCollection',
				placeholder: 'Add Shipping Address',
				default: {},
				typeOptions: {
					multipleValues: true,
				},
				options: [
					{
						displayName: 'Address',
						name: 'address',
						values: [
							{
								displayName: 'Address Line 1',
								name: 'shipping_address1',
								type: 'string',
								default: '',
							},
							{
								displayName: 'Address Line 2',
								name: 'shipping_address2',
								type: 'string',
								default: '',
							},
							{
								displayName: 'City',
								name: 'shipping_city',
								type: 'string',
								default: '',
							},
							{
								displayName: 'Country',
								name: 'shipping_country',
								type: 'string',
								default: '',
								placeholder: 'Enter country name',
							},
							{
								displayName: 'Email',
								name: 'shipping_email',
								type: 'string',
								default: '',
								placeholder: 'Enter email',
							},
							{
								displayName: 'Mobile',
								name: 'shipping_mobile',
								type: 'string',
								default: '',
								placeholder: 'Enter mobile number',
							},
							{
								displayName: 'Postal Code',
								name: 'shipping_postalcode',
								type: 'string',
								default: '',
								placeholder: 'Enter postal code',
							},
							{
								displayName: 'State',
								name: 'shipping_state',
								type: 'string',
								default: '',
								placeholder: 'Enter state name',
							},
							{
								displayName: 'TAX Number',
								name: 'shipping_tax',
								type: 'string',
								default: '',
								placeholder: 'Enter TAX Number',
							},
						],
					},
				],
			},
			{ displayName: 'Email', name: 'email', type: 'string', default: '', placeholder: '' },
			{
				displayName: 'Mobile Country Code',
				name: 'mobile_country_code',
				type: 'options',
				// eslint-disable-next-line n8n-nodes-base/node-param-options-type-unsorted-items
				options: [
					{ name: '🇦🇪 UAE (+971)', value: 971 },
					{ name: '🇮🇳 India (+91)', value: 91 },
					{ name: '🇺🇸 USA (+1)', value: 1 },
					{ name: '🇬🇧 UK (+44)', value: 44 },
					{ name: '🇸🇦 Saudi Arabia (+966)', value: 966 },
					{ name: '🇶🇦 Qatar (+974)', value: 974 },
					{ name: '🇰🇼 Kuwait (+965)', value: 965 },
					{ name: '🇧🇭 Bahrain (+973)', value: 973 },
					{ name: '🇴🇲 Oman (+968)', value: 968 },
					{ name: '🇯🇴 Jordan (+962)', value: 962 },
					{ name: '🇱🇧 Lebanon (+961)', value: 961 },
					{ name: '🇪🇬 Egypt (+20)', value: 20 },
					{ name: '🇲🇦 Morocco (+212)', value: 212 },
					{ name: '🇹🇳 Tunisia (+216)', value: 216 },
					{ name: '🇩🇿 Algeria (+213)', value: 213 },
					{ name: '🇱🇾 Libya (+218)', value: 218 },
					{ name: '🇸🇩 Sudan (+249)', value: 249 },
					{ name: '🇸🇾 Syria (+963)', value: 963 },
					{ name: '🇾🇪 Yemen (+967)', value: 967 },
					{ name: '🇮🇶 Iraq (+964)', value: 964 },
					{ name: '🇮🇷 Iran (+98)', value: 98 },
					{ name: '🇦🇫 Afghanistan (+93)', value: 93 },
					{ name: '🇵🇰 Pakistan (+92)', value: 92 },
					{ name: '🇧🇩 Bangladesh (+880)', value: 880 },
					{ name: '🇱🇰 Sri Lanka (+94)', value: 94 },
					{ name: '🇳🇵 Nepal (+977)', value: 977 },
					{ name: '🇧🇹 Bhutan (+975)', value: 975 },
					{ name: '🇲🇲 Myanmar (+95)', value: 95 },
					{ name: '🇹🇭 Thailand (+66)', value: 66 },
					{ name: '🇻🇳 Vietnam (+84)', value: 84 },
					{ name: '🇰🇭 Cambodia (+855)', value: 855 },
					{ name: '🇱🇦 Laos (+856)', value: 856 },
					{ name: '🇲🇳 Mongolia (+976)', value: 976 },
					{ name: '🇨🇳 China (+86)', value: 86 },
					{ name: '🇯🇵 Japan (+81)', value: 81 },
					{ name: '🇰🇷 South Korea (+82)', value: 82 },
					{ name: '🇹🇼 Taiwan (+886)', value: 886 },
					{ name: '🇭🇰 Hong Kong (+852)', value: 852 },
					{ name: '🇸🇬 Singapore (+65)', value: 65 },
					{ name: '🇲🇾 Malaysia (+60)', value: 60 },
					{ name: '🇮🇩 Indonesia (+62)', value: 62 },
					{ name: '🇵🇭 Philippines (+63)', value: 63 },
					{ name: '🇧🇷 Brazil (+55)', value: 55 },
					{ name: '🇦🇷 Argentina (+54)', value: 54 },
					{ name: '🇨🇱 Chile (+56)', value: 56 },
					{ name: '🇨🇴 Colombia (+57)', value: 57 },
					{ name: '🇵🇪 Peru (+51)', value: 51 },
					{ name: '🇺🇾 Uruguay (+598)', value: 598 },
					{ name: '🇻🇪 Venezuela (+58)', value: 58 },
					{ name: '🇲🇽 Mexico (+52)', value: 52 },
					{ name: '🇨🇦 Canada (+1)', value: 1 },
					{ name: '🇦🇺 Australia (+61)', value: 61 },
					{ name: '🇳🇿 New Zealand (+64)', value: 64 },
					{ name: '🇿🇦 South Africa (+27)', value: 27 },
					{ name: '🇳🇬 Nigeria (+234)', value: 234 },
					{ name: '🇰🇪 Kenya (+254)', value: 254 },
					{ name: '🇬🇭 Ghana (+233)', value: 233 },
					{ name: '🇺🇬 Uganda (+256)', value: 256 },
					{ name: '🇹🇿 Tanzania (+255)', value: 255 },
					{ name: '🇪🇹 Ethiopia (+251)', value: 251 },
					{ name: '🇩🇪 Germany (+49)', value: 49 },
					{ name: '🇫🇷 France (+33)', value: 33 },
					{ name: '🇮🇹 Italy (+39)', value: 39 },
					{ name: '🇪🇸 Spain (+34)', value: 34 },
					{ name: '🇵🇱 Poland (+48)', value: 48 },
					{ name: '🇷🇺 Russia (+7)', value: 7 },
					{ name: '🇹🇷 Turkey (+90)', value: 90 },
					{ name: '🇳🇱 Netherlands (+31)', value: 31 },
					{ name: '🇧🇪 Belgium (+32)', value: 32 },
					{ name: '🇨🇭 Switzerland (+41)', value: 41 },
					{ name: '🇦🇹 Austria (+43)', value: 43 },
					{ name: '🇸🇪 Sweden (+46)', value: 46 },
					{ name: '🇳🇴 Norway (+47)', value: 47 },
					{ name: '🇩🇰 Denmark (+45)', value: 45 },
					{ name: '🇫🇮 Finland (+358)', value: 358 },
					{ name: '🇮🇸 Iceland (+354)', value: 354 },
					{ name: '🇮🇪 Ireland (+353)', value: 353 },
					{ name: '🇵🇹 Portugal (+351)', value: 351 },
					{ name: '🇬🇷 Greece (+30)', value: 30 },
					{ name: '🇭🇺 Hungary (+36)', value: 36 },
					{ name: '🇨🇿 Czech Republic (+420)', value: 420 },
					{ name: '🇸🇰 Slovakia (+421)', value: 421 },
					{ name: '🇸🇮 Slovenia (+386)', value: 386 },
					{ name: '🇭🇷 Croatia (+385)', value: 385 },
					{ name: '🇷🇸 Serbia (+381)', value: 381 },
					{ name: '🇧🇬 Bulgaria (+359)', value: 359 },
					{ name: '🇷🇴 Romania (+40)', value: 40 },
					{ name: '🇺🇦 Ukraine (+380)', value: 380 },
					{ name: '🇧🇾 Belarus (+375)', value: 375 },
					{ name: '🇱🇹 Lithuania (+370)', value: 370 },
					{ name: '🇱🇻 Latvia (+371)', value: 371 },
					{ name: '🇪🇪 Estonia (+372)', value: 372 },
					{ name: '🇲🇩 Moldova (+373)', value: 373 },
					{ name: '🇦🇲 Armenia (+374)', value: 374 },
					{ name: '🇬🇪 Georgia (+995)', value: 995 },
					{ name: '🇦🇿 Azerbaijan (+994)', value: 994 },
					{ name: '🇰🇿 Kazakhstan (+7)', value: 7 },
					{ name: '🇺🇿 Uzbekistan (+998)', value: 998 },
					{ name: '🇰🇬 Kyrgyzstan (+996)', value: 996 },
				],
				default: 91,
				description: 'Select the country code for the mobile number',
			},
			{ displayName: 'Mobile', name: 'mobile', type: 'string', default: '', placeholder: '' },
			{ displayName: 'TAX Number', name: 'tax', type: 'string', default: '', placeholder: '' },
			{
				displayName: 'Opening Customer Receivable',
				name: 'opening_customer_receivable_group',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: false,
				},
				default: {},
				options: [
					{
						displayName: 'Customer Receivable',
						name: 'customer_receivable',
						values: [
							{
								displayName: 'Amount',
								name: 'amount',
								type: 'string',
								default: '',
								description: 'Enter the opening customer receivable amount',
							},
							{
								displayName: 'Financial Year',
								name: 'fiscal_year',
								type: 'options',
								options: getFiscalYearData().options,
								default: '',
								description: 'Select the financial year',
							},
						],
					},
				],
			},
			{
				displayName: 'Opening Supplier Payable',
				name: 'opening_supplier_payable_group',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: false,
				},
				default: {},
				options: [
					{
						displayName: 'Supplier Payable',
						name: 'supplier_payable',
						values: [
							{
								displayName: 'Amount',
								name: 'amount',
								type: 'string',
								default: '',
								description: 'Enter the opening supplier payable amount',
							},
							{
								displayName: 'Financial Year',
								name: 'fiscal_year',
								type: 'options',
								options: getFiscalYearData().options,
								default: '',
								description: 'Select the financial year',
							},
						],
					},
				],
			},
			{ displayName: 'PAN (India Only)', name: 'pan', type: 'string', default: '', placeholder: '' },
			{
				displayName: 'Business Name',
				name: 'business_name',
				type: 'string',
				default: '',
				placeholder: '',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Inactive', value: 'inactive' },
				],
				default: 'active',
			},
		],
	},

	{
		displayName: 'Additional Fields',
		name: 'contactAdditionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['updateContact'],
			},
		},
		// eslint-disable-next-line n8n-nodes-base/node-param-collection-type-unsorted-items
		options: [
			{ displayName: 'Email', name: 'email', type: 'string', default: '', placeholder: '' },
			{
				displayName: 'Mobile Country Code',
				name: 'mobile_country_code',
				type: 'options',
				options: [
					{ name: '🇦🇪 UAE (+971)', value: 971 },
					{ name: '🇮🇳 India (+91)', value: 91 },
					{ name: '🇺🇸 USA (+1)', value: 1 },
					{ name: '🇬🇧 UK (+44)', value: 44 },
					{ name: '🇸🇦 Saudi Arabia (+966)', value: 966 },
					{ name: '🇶🇦 Qatar (+974)', value: 974 },
					{ name: '🇰🇼 Kuwait (+965)', value: 965 },
					{ name: '🇧🇭 Bahrain (+973)', value: 973 },
					{ name: '🇴🇲 Oman (+968)', value: 968 },
					{ name: '🇯🇴 Jordan (+962)', value: 962 },
					{ name: '🇱🇧 Lebanon (+961)', value: 961 },
					{ name: '🇪🇬 Egypt (+20)', value: 20 },
					{ name: '🇲🇦 Morocco (+212)', value: 212 },
					{ name: '🇹🇳 Tunisia (+216)', value: 216 },
					{ name: '🇩🇿 Algeria (+213)', value: 213 },
					{ name: '🇱🇾 Libya (+218)', value: 218 },
					{ name: '🇸🇩 Sudan (+249)', value: 249 },
					{ name: '🇸🇾 Syria (+963)', value: 963 },
					{ name: '🇾🇪 Yemen (+967)', value: 967 },
					{ name: '🇮🇶 Iraq (+964)', value: 964 },
					{ name: '🇮🇷 Iran (+98)', value: 98 },
					{ name: '🇦🇫 Afghanistan (+93)', value: 93 },
					{ name: '🇵🇰 Pakistan (+92)', value: 92 },
					{ name: '🇧🇩 Bangladesh (+880)', value: 880 },
					{ name: '🇱🇰 Sri Lanka (+94)', value: 94 },
					{ name: '🇳🇵 Nepal (+977)', value: 977 },
					{ name: '🇧🇹 Bhutan (+975)', value: 975 },
					{ name: '🇲🇲 Myanmar (+95)', value: 95 },
					{ name: '🇹🇭 Thailand (+66)', value: 66 },
					{ name: '🇻🇳 Vietnam (+84)', value: 84 },
					{ name: '🇰🇭 Cambodia (+855)', value: 855 },
					{ name: '🇱🇦 Laos (+856)', value: 856 },
					{ name: '🇲🇳 Mongolia (+976)', value: 976 },
					{ name: '🇨🇳 China (+86)', value: 86 },
					{ name: '🇯🇵 Japan (+81)', value: 81 },
					{ name: '🇰🇷 South Korea (+82)', value: 82 },
					{ name: '🇹🇼 Taiwan (+886)', value: 886 },
					{ name: '🇭🇰 Hong Kong (+852)', value: 852 },
					{ name: '🇸🇬 Singapore (+65)', value: 65 },
					{ name: '🇲🇾 Malaysia (+60)', value: 60 },
					{ name: '🇮🇩 Indonesia (+62)', value: 62 },
					{ name: '🇵🇭 Philippines (+63)', value: 63 },
					{ name: '🇧🇷 Brazil (+55)', value: 55 },
					{ name: '🇦🇷 Argentina (+54)', value: 54 },
					{ name: '🇨🇱 Chile (+56)', value: 56 },
					{ name: '🇨🇴 Colombia (+57)', value: 57 },
					{ name: '🇵🇪 Peru (+51)', value: 51 },
					{ name: '🇺🇾 Uruguay (+598)', value: 598 },
					{ name: '🇻🇪 Venezuela (+58)', value: 58 },
					{ name: '🇲🇽 Mexico (+52)', value: 52 },
					{ name: '🇨🇦 Canada (+1)', value: 1 },
					{ name: '🇦🇺 Australia (+61)', value: 61 },
					{ name: '🇳🇿 New Zealand (+64)', value: 64 },
					{ name: '🇿🇦 South Africa (+27)', value: 27 },
					{ name: '🇳🇬 Nigeria (+234)', value: 234 },
					{ name: '🇰🇪 Kenya (+254)', value: 254 },
					{ name: '🇬🇭 Ghana (+233)', value: 233 },
					{ name: '🇺🇬 Uganda (+256)', value: 256 },
					{ name: '🇹🇿 Tanzania (+255)', value: 255 },
					{ name: '🇪🇹 Ethiopia (+251)', value: 251 },
					{ name: '🇩🇪 Germany (+49)', value: 49 },
					{ name: '🇫🇷 France (+33)', value: 33 },
					{ name: '🇮🇹 Italy (+39)', value: 39 },
					{ name: '🇪🇸 Spain (+34)', value: 34 },
					{ name: '🇵🇱 Poland (+48)', value: 48 },
					{ name: '🇷🇺 Russia (+7)', value: 7 },
					{ name: '🇹🇷 Turkey (+90)', value: 90 },
					{ name: '🇳🇱 Netherlands (+31)', value: 31 },
					{ name: '🇧🇪 Belgium (+32)', value: 32 },
					{ name: '🇨🇭 Switzerland (+41)', value: 41 },
					{ name: '🇦🇹 Austria (+43)', value: 43 },
					{ name: '🇸🇪 Sweden (+46)', value: 46 },
					{ name: '🇳🇴 Norway (+47)', value: 47 },
					{ name: '🇩🇰 Denmark (+45)', value: 45 },
					{ name: '🇫🇮 Finland (+358)', value: 358 },
					{ name: '🇮🇸 Iceland (+354)', value: 354 },
					{ name: '🇮🇪 Ireland (+353)', value: 353 },
					{ name: '🇵🇹 Portugal (+351)', value: 351 },
					{ name: '🇬🇷 Greece (+30)', value: 30 },
					{ name: '🇭🇺 Hungary (+36)', value: 36 },
					{ name: '🇨🇿 Czech Republic (+420)', value: 420 },
					{ name: '🇸🇰 Slovakia (+421)', value: 421 },
					{ name: '🇸🇮 Slovenia (+386)', value: 386 },
					{ name: '🇭🇷 Croatia (+385)', value: 385 },
					{ name: '🇷🇸 Serbia (+381)', value: 381 },
					{ name: '🇧🇬 Bulgaria (+359)', value: 359 },
					{ name: '🇷🇴 Romania (+40)', value: 40 },
					{ name: '🇺🇦 Ukraine (+380)', value: 380 },
					{ name: '🇧🇾 Belarus (+375)', value: 375 },
					{ name: '🇱🇹 Lithuania (+370)', value: 370 },
					{ name: '🇱🇻 Latvia (+371)', value: 371 },
					{ name: '🇪🇪 Estonia (+372)', value: 372 },
					{ name: '🇲🇩 Moldova (+373)', value: 373 },
					{ name: '🇦🇲 Armenia (+374)', value: 374 },
					{ name: '🇬🇪 Georgia (+995)', value: 995 },
					{ name: '🇦🇿 Azerbaijan (+994)', value: 994 },
					{ name: '🇰🇿 Kazakhstan (+7)', value: 7 },
					{ name: '🇺🇿 Uzbekistan (+998)', value: 998 },
					{ name: '🇰🇬 Kyrgyzstan (+996)', value: 996 },
				],
				default: 91,
			},
			{ displayName: 'Mobile', name: 'mobile', type: 'string', default: '', placeholder: '' },
			{ displayName: 'TAX Number', name: 'tax', type: 'string', default: '', placeholder: '' },
			{ displayName: 'PAN (India Only)', name: 'pan', type: 'string', default: '', placeholder: '' },
			{
				displayName: 'Business Name',
				name: 'business_name',
				type: 'string',
				default: '',
				placeholder: '',
			},
			{
				displayName: 'Opening Customer Receivable',
				name: 'opening_customer_receivable_group',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: false,
				},
				default: {},
				options: [
					{
						displayName: 'Customer Receivable',
						name: 'customer_receivable',
						values: [
							{
								displayName: 'Amount',
								name: 'amount',
								type: 'string',
								default: '',
								description: 'Enter the opening customer receivable amount',
							},
							{
								displayName: 'Financial Year',
								name: 'fiscal_year',
								type: 'options',
								options: getFiscalYearData().options,
								default: '',
								description: 'Select the financial year',
							},
						],
					},
				],
			},
			{
				displayName: 'Opening Supplier Payable',
				name: 'opening_supplier_payable_group',
				type: 'fixedCollection',
				typeOptions: {
					multipleValues: false,
				},
				default: {},
				options: [
					{
						displayName: 'Supplier Payable',
						name: 'supplier_payable',
						values: [
							{
								displayName: 'Amount',
								name: 'amount',
								type: 'string',
								default: '',
								description: 'Enter the opening supplier payable amount',
							},
							{
								displayName: 'Financial Year',
								name: 'fiscal_year',
								type: 'options',
								options: getFiscalYearData().options,
								default: '',
								description: 'Select the financial year',
							},
						],
					},
				],
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Inactive', value: 'inactive' },
				],
				default: 'active',
			},
		],
	},

	{
		displayName: 'Address Type',
		name: 'addressType',
		type: 'options',
		options: [
			{ name: 'Billing Address', value: 'billing' },
			{ name: 'Shipping Address', value: 'shipping' },
			{ name: 'Both (Billing & Shipping)', value: 'both' },
		],
		default: 'billing',
		displayOptions: {
			show: { operation: ['addAddress'] },
		},
		description: 'Type of address to add (can add to both billing and shipping at the same time)',
	},

	{
		displayName: 'Address Type',
		name: 'addressType',
		type: 'options',
		options: [
			{ name: 'Billing Address', value: 'billing' },
			{ name: 'Shipping Address', value: 'shipping' },
		],
		default: 'billing',
		displayOptions: {
			show: { operation: ['updateAddress'] },
		},
		description: 'Type of address to update (one type at a time)',
	},

	{
		displayName: 'Address Name or ID',
		name: 'addressSelector',
		type: 'options',
		default: '',
		displayOptions: {
			show: { operation: ['updateAddress'] },
		},
		typeOptions: {
			loadOptionsMethod: 'getAddressOptions',
			loadOptionsDependsOn: ['contactId', 'addressType'],
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},

	{
		displayName: 'Update Fields',
		name: 'addressUpdateFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['updateAddress'],
			},
		},
		// eslint-disable-next-line n8n-nodes-base/node-param-collection-type-unsorted-items
		options: [
			{
				displayName: 'Address Line 1',
				name: 'address1',
				type: 'string',
				default: '',
				placeholder: 'Enter address line 1',
			},
			{
				displayName: 'Address Line 2',
				name: 'address2',
				type: 'string',
				default: '',
				placeholder: 'Enter address line 2 (optional)',
			},
			{
				displayName: 'City',
				name: 'location',
				type: 'string',
				default: '',
				placeholder: 'Enter city',
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				default: '',
				placeholder: 'Enter email',
			},
			{
				displayName: 'Mobile',
				name: 'mobile',
				type: 'string',
				default: '',
				placeholder: 'Enter mobile',
			},
			{
				displayName: 'Postal Code',
				name: 'postalCode',
				type: 'string',
				default: '',
				placeholder: 'Enter postal code',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
			},
			{
				displayName: 'TAX Number',
				name: 'tax',
				type: 'string',
				default: '',
				placeholder: 'Enter TAX Number',
			},
		],
	},

	{
		displayName: 'Address Fields',
		name: 'addressFields',
		type: 'collection',
		placeholder: 'Add Address Field',
		default: {},
		displayOptions: {
			show: { operation: ['addAddress'] },
		},
		options: [
			{
				displayName: 'Address Line 1',
				name: 'address1',
				type: 'string',
				default: '',
				placeholder: 'Enter address line 1',
			},
			{
				displayName: 'Address Line 2',
				name: 'address2',
				type: 'string',
				default: '',
				placeholder: 'Enter address line 2 (optional)',
			},
			{
				displayName: 'City',
				name: 'location',
				type: 'string',
				default: '',
				placeholder: 'Enter city',
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				default: '',
				placeholder: 'Enter email',
			},
			{
				displayName: 'Mobile',
				name: 'mobile',
				type: 'string',
				default: '',
				placeholder: 'Enter mobile',
			},
			{
				displayName: 'Postal Code',
				name: 'postalcode',
				type: 'string',
				default: '',
				placeholder: 'Enter postal code',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'string',
				default: '',
			},
			{
				displayName: 'TAX Number',
				name: 'tax',
				type: 'string',
				default: '',
				placeholder: 'Enter TAX Number',
			},
		],
	},

	{
		displayName: 'Search Type',
		name: 'searchType',
		type: 'options',
		options: [
			{ name: 'Search by Name', value: 'name' },
			{ name: 'Search by Limit', value: 'limit' },
		],
		default: 'limit',
		displayOptions: {
			show: {
				operation: ['getAllContacts'],
			},
		},
	},

	{
		displayName: 'Search Term',
		name: 'searchTerm',
		type: 'string',
		default: '',
		placeholder: 'Enter name to search',
		displayOptions: {
			show: {
				operation: ['getAllContacts'],
				searchType: ['name'],
			},
		},
	},

	{
		displayName: 'Limit (Per Page)',
		name: 'perPage',
		type: 'number',
		default: 5,
		displayOptions: {
			show: {
				operation: ['getAllContacts'],
				searchType: ['name', 'limit'],
			},
		},
	},
];
