import type { INodeProperties } from 'n8n-workflow';

export const contactOperations: INodeProperties[] = [
	{
		displayName: 'Operation',
		noDataExpression: true,
		name: 'operation',
		type: 'options',
		options: [
			{ name: 'Add Address (Existing Contact)', value: 'addAddress', action: 'Add address to a contact' },
			{ name: 'Create Contact', value: 'createContact', action: 'Create a contact' },
			{ name: 'Get All Contacts', value: 'getAllContacts', action: 'Get all contacts' },
			{ name: 'Get Contact', value: 'getContact', action: 'Get a contact' },
			{ name: 'Update Address (Existing Contact)', value: 'updateAddress', action: 'Update address of a contact' },
			{ name: 'Update Contact', value: 'updateContact', action: 'Update a contact' },
		],
		default: 'createContact',
		displayOptions: {
			show: { resource: ['contact'] },
		},
		description: 'Choose the operation',
	},

	{
		displayName: 'Contact ID',
		name: 'contactId',
		type: 'string',
		default: '',
		required: true,
		displayOptions: {
			show: { operation: ['getContact', 'updateContact', 'addAddress', 'updateAddress'] },
		},
		description: 'The ID of the contact to work with',
	},

	{
		displayName: 'Contact Name',
		name: 'contactName',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: { operation: ['createContact'] },
		},
	},

	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['createContact'],
			},
		},
		// eslint-disable-next-line n8n-nodes-base/node-param-collection-type-unsorted-items
		options: [
			{ displayName: 'Email', name: 'email', type: 'string', default: '', placeholder: '' },
			{
				displayName: 'Mobile Country Code',
				name: 'mobile_country_code',
				type: 'options',
				// eslint-disable-next-line n8n-nodes-base/node-param-options-type-unsorted-items
				options: [
					{ name: '🇮🇳 India (+91)', value: '+91' },
					{ name: '🇺🇸 USA (+1)', value: '+1' },
					{ name: '🇬🇧 UK (+44)', value: '+44' },
					{ name: '🇸🇬 Singapore (+65)', value: '+65' },
					{ name: '🇦🇪 UAE (+971)', value: '+971' },
				],
				default: '+91',
				description: 'Select the country code for the mobile number',
			},
			{ displayName: 'Mobile', name: 'mobile', type: 'string', default: '', placeholder: '' },
			{ displayName: 'GSTIN', name: 'gstin', type: 'string', default: '', placeholder: '' },
			{
				displayName: 'Business Name',
				name: 'business_name',
				type: 'string',
				default: '',
				placeholder: '',
			},
			{
				displayName: 'Billing Address 1',
				name: 'billing_address1',
				type: 'string',
				default: '',
				placeholder: '',
			},
			{
				displayName: 'Billing Address 2',
				name: 'billing_address2',
				type: 'string',
				default: '',
				placeholder: '',
			},
			{ displayName: 'City', name: 'location', type: 'string', default: '', placeholder: '' },
			{
				displayName: 'State',
				name: 'state',
				type: 'options',
				options: [
					{ value: 'ANDAMAN AND NICOBAR ISLANDS', name: 'ANDAMAN AND NICOBAR ISLANDS' },
					{ value: 'ANDHRA PRADESH', name: 'ANDHRA PRADESH' },
					{ value: 'ARUNACHAL PRADESH', name: 'ARUNACHAL PRADESH' },
					{ value: 'ASSAM', name: 'ASSAM' },
					{ value: 'BIHAR', name: 'BIHAR' },
					{ value: 'CHANDIGARH', name: 'CHANDIGARH' },
					{ value: 'CHHATTISGARH', name: 'CHHATTISGARH' },
					{ value: 'DADRA AND NAGAR HAVELI', name: 'DADRA AND NAGAR HAVELI' },
					{ value: 'DAMAN AND DIU', name: 'DAMAN AND DIU' },
					{ value: 'DELHI', name: 'DELHI' },
					{ value: 'GOA', name: 'GOA' },
					{ value: 'GUJARAT', name: 'GUJARAT' },
					{ value: 'HARYANA', name: 'HARYANA' },
					{ value: 'HIMACHAL PRADESH', name: 'HIMACHAL PRADESH' },
					{ value: 'INTERNATIONAL', name: 'INTERNATIONAL' },
					{ value: 'JAMMU AND KASHMIR', name: 'JAMMU AND KASHMIR' },
					{ value: 'JHARKHAND', name: 'JHARKHAND' },
					{ value: 'KARNATAKA', name: 'KARNATAKA' },
					{ value: 'KERALA', name: 'KERALA' },
					{ value: 'LADAKH', name: 'LADAKH' },
					{ value: 'LAKSHADWEEP', name: 'LAKSHADWEEP' },
					{ value: 'MADHYA PRADESH', name: 'MADHYA PRADESH' },
					{ value: 'MAHARASHTRA', name: 'MAHARASHTRA' },
					{ value: 'MANIPUR', name: 'MANIPUR' },
					{ value: 'MEGHALAYA', name: 'MEGHALAYA' },
					{ value: 'MIZORAM', name: 'MIZORAM' },
					{ value: 'NAGALAND', name: 'NAGALAND' },
					{ value: 'ODISHA', name: 'ODISHA' },
					{ value: 'OTHER TERRITORY', name: 'OTHER TERRITORY' },
					{ value: 'PUDUCHERRY', name: 'PUDUCHERRY' },
					{ value: 'PUNJAB', name: 'PUNJAB' },
					{ value: 'RAJASTHAN', name: 'RAJASTHAN' },
					{ value: 'SIKKIM', name: 'SIKKIM' },
					{ value: 'TAMIL NADU', name: 'TAMIL NADU' },
					{ value: 'TELANGANA', name: 'TELANGANA' },
					{ value: 'TRIPURA', name: 'TRIPURA' },
					{ value: 'UTTAR PRADESH', name: 'UTTAR PRADESH' },
					{ value: 'UTTARAKHAND', name: 'UTTARAKHAND' },
					{ value: 'WEST BENGAL', name: 'WEST BENGAL' }
				],
				default: 'TAMIL NADU',
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'options',
				options: [
					{ name: 'AFGHANISTAN', value: 'AFGHANISTAN' },
					{ name: 'ALBANIA', value: 'ALBANIA' },
					{ name: 'ALGERIA', value: 'ALGERIA' },
					{ name: 'AMERICAN SAMOA', value: 'AMERICAN SAMOA' },
					{ name: 'ANDORRA', value: 'ANDORRA' },
					{ name: 'ANGOLA', value: 'ANGOLA' },
					{ name: 'ANGUILLA', value: 'ANGUILLA' },
					{ name: 'ANTIGUA AND BARBUDA', value: 'ANTIGUA AND BARBUDA' },
					{ name: 'ARGENTINA', value: 'ARGENTINA' },
					{ name: 'ARMENIA', value: 'ARMENIA' },
					{ name: 'ARUBA', value: 'ARUBA' },
					{ name: 'AUSTRALIA', value: 'AUSTRALIA' },
					{ name: 'AUSTRIA', value: 'AUSTRIA' },
					{ name: 'AZERBAIJAN', value: 'AZERBAIJAN' },
					{ name: 'BAHAMAS', value: 'BAHAMAS' },
					{ name: 'BAHRAIN', value: 'BAHRAIN' },
					{ name: 'BANGLADESH', value: 'BANGLADESH' },
					{ name: 'BARBADOS', value: 'BARBADOS' },
					{ name: 'BELARUS', value: 'BELARUS' },
					{ name: 'BELGIUM', value: 'BELGIUM' },
					{ name: 'BELIZE', value: 'BELIZE' },
					{ name: 'BENIN', value: 'BENIN' },
					{ name: 'BERMUDA', value: 'BERMUDA' },
					{ name: 'BHUTAN', value: 'BHUTAN' },
					{ name: 'BOLIVIA', value: 'BOLIVIA' },
					{ name: 'BOSNIA AND HERZEGOVINA', value: 'BOSNIA AND HERZEGOVINA' },
					{ name: 'BOTSWANA', value: 'BOTSWANA' },
					{ name: 'BOUVET ISLAND', value: 'BOUVET ISLAND' },
					{ name: 'BRAZIL', value: 'BRAZIL' },
					{ name: 'BRITISH INDIAN OCEAN TERRITORY', value: 'BRITISH INDIAN OCEAN TERRITORY' },
					{ name: 'BRUNEI DARUSSALAM', value: 'BRUNEI DARUSSALAM' },
					{ name: 'BULGARIA', value: 'BULGARIA' },
					{ name: 'BURKINA FASO', value: 'BURKINA FASO' },
					{ name: 'BURUNDI', value: 'BURUNDI' },
					{ name: 'CAMBODIA', value: 'CAMBODIA' },
					{ name: 'CAMEROON', value: 'CAMEROON' },
					{ name: 'CANADA', value: 'CANADA' },
					{ name: 'CAPE VERDE', value: 'CAPE VERDE' },
					{ name: 'CAYMAN ISLANDS', value: 'CAYMAN ISLANDS' },
					{ name: 'CENTRAL AFRICAN REPUBLIC', value: 'CENTRAL AFRICAN REPUBLIC' },
					{ name: 'CHAD', value: 'CHAD' },
					{ name: 'CHILE', value: 'CHILE' },
					{ name: 'CHINA', value: 'CHINA' },
					{ name: 'CHRISTMAS ISLAND', value: 'CHRISTMAS ISLAND' },
					{ name: 'COCOS (KEELING) ISLANDS', value: 'COCOS (KEELING) ISLANDS' },
					{ name: 'COLOMBIA', value: 'COLOMBIA' },
					{ name: 'COMOROS', value: 'COMOROS' },
					{ name: 'CONGO', value: 'CONGO' },
					{ name: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', value: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE' },
					{ name: 'COOK ISLANDS', value: 'COOK ISLANDS' },
					{ name: 'COSTA RICA', value: 'COSTA RICA' },
					{ name: 'COTE D`IVOIRE', value: 'COTE D`IVOIRE' },
					{ name: 'CROATIA', value: 'CROATIA' },
					{ name: 'CUBA', value: 'CUBA' },
					{ name: 'CYPRUS', value: 'CYPRUS' },
					{ name: 'CZECH REPUBLIC', value: 'CZECH REPUBLIC' },
					{ name: 'DENMARK', value: 'DENMARK' },
					{ name: 'DJIBOUTI', value: 'DJIBOUTI' },
					{ name: 'DOMINICA', value: 'DOMINICA' },
					{ name: 'DOMINICAN REPUBLIC', value: 'DOMINICAN REPUBLIC' },
					{ name: 'EAST TIMOR', value: 'EAST TIMOR' },
					{ name: 'ECUADOR', value: 'ECUADOR' },
					{ name: 'EGYPT', value: 'EGYPT' },
					{ name: 'EL SALVADOR', value: 'EL SALVADOR' },
					{ name: 'EQUATORIAL GUINEA', value: 'EQUATORIAL GUINEA' },
					{ name: 'ERITREA', value: 'ERITREA' },
					{ name: 'ESTONIA', value: 'ESTONIA' },
					{ name: 'ETHIOPIA', value: 'ETHIOPIA' },
					{ name: 'FALKLAND ISLANDS (MALVINAS)', value: 'FALKLAND ISLANDS (MALVINAS)' },
					{ name: 'FAROE ISLANDS', value: 'FAROE ISLANDS' },
					{ name: 'FIJI', value: 'FIJI' },
					{ name: 'FINLAND', value: 'FINLAND' },
					{ name: 'FRANCE', value: 'FRANCE' },
					{ name: 'FRENCH GUIANA', value: 'FRENCH GUIANA' },
					{ name: 'FRENCH POLYNESIA', value: 'FRENCH POLYNESIA' },
					{ name: 'FRENCH SOUTHERN TERRITORIES', value: 'FRENCH SOUTHERN TERRITORIES' },
					{ name: 'GABON', value: 'GABON' },
					{ name: 'GAMBIA', value: 'GAMBIA' },
					{ name: 'GEORGIA', value: 'GEORGIA' },
					{ name: 'GERMANY', value: 'GERMANY' },
					{ name: 'GHANA', value: 'GHANA' },
					{ name: 'GIBRALTAR', value: 'GIBRALTAR' },
					{ name: 'GREECE', value: 'GREECE' },
					{ name: 'GREENLAND', value: 'GREENLAND' },
					{ name: 'GRENADA', value: 'GRENADA' },
					{ name: 'GUADELOUPE', value: 'GUADELOUPE' },
					{ name: 'GUAM', value: 'GUAM' },
					{ name: 'GUATEMALA', value: 'GUATEMALA' },
					{ name: 'GUINEA', value: 'GUINEA' },
					{ name: 'GUINEA-BISSAU', value: 'GUINEA-BISSAU' },
					{ name: 'GUYANA', value: 'GUYANA' },
					{ name: 'HAITI', value: 'HAITI' },
					{ name: 'HEARD ISLAND AND MCDONALD ISLANDS', value: 'HEARD ISLAND AND MCDONALD ISLANDS' },
					{ name: 'HOLY SEE (VATICAN CITY STATE)', value: 'HOLY SEE (VATICAN CITY STATE)' },
					{ name: 'HONDURAS', value: 'HONDURAS' },
					{ name: 'HONG KONG', value: 'HONG KONG' },
					{ name: 'HUNGARY', value: 'HUNGARY' },
					{ name: 'ICELAND', value: 'ICELAND' },
					{ name: 'INDIA', value: 'INDIA' },
					{ name: 'INDONESIA', value: 'INDONESIA' },
					{ name: 'IRAN (ISLAMIC REPUBLIC OF)', value: 'IRAN (ISLAMIC REPUBLIC OF)' },
					{ name: 'IRAQ', value: 'IRAQ' },
					{ name: 'IRELAND', value: 'IRELAND' },
					{ name: 'ISRAEL', value: 'ISRAEL' },
					{ name: 'ITALY', value: 'ITALY' },
					{ name: 'JAMAICA', value: 'JAMAICA' },
					{ name: 'JAPAN', value: 'JAPAN' },
					{ name: 'JORDAN', value: 'JORDAN' },
					{ name: 'KAZAKHSTAN', value: 'KAZAKHSTAN' },
					{ name: 'KENYA', value: 'KENYA' },
					{ name: 'KIRIBATI', value: 'KIRIBATI' },
					{ name: 'KOREA, DEMOCRATIC PEOPLE`S REPUBLIC OF', value: 'KOREA, DEMOCRATIC PEOPLE`S REPUBLIC OF' },
					{ name: 'KOREA, REPUBLIC OF', value: 'KOREA, REPUBLIC OF' },
					{ name: 'KUWAIT', value: 'KUWAIT' },
					{ name: 'KYRGYZSTAN', value: 'KYRGYZSTAN' },
					{ name: 'LAO PEOPLE`S DEMOCRATIC REPUBLIC', value: 'LAO PEOPLE`S DEMOCRATIC REPUBLIC' },
					{ name: 'LATVIA', value: 'LATVIA' },
					{ name: 'LEBANON', value: 'LEBANON' },
					{ name: 'LESOTHO', value: 'LESOTHO' },
					{ name: 'LIBERIA', value: 'LIBERIA' },
					{ name: 'LIBYAN ARAB JAMAHIRIYA', value: 'LIBYAN ARAB JAMAHIRIYA' },
					{ name: 'LIECHTENSTEIN', value: 'LIECHTENSTEIN' },
					{ name: 'LITHUANIA', value: 'LITHUANIA' },
					{ name: 'LUXEMBOURG', value: 'LUXEMBOURG' },
					{ name: 'MACAO', value: 'MACAO' },
					{ name: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', value: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF' },
					{ name: 'MADAGASCAR', value: 'MADAGASCAR' },
					{ name: 'MALAWI', value: 'MALAWI' },
					{ name: 'MALAYSIA', value: 'MALAYSIA' },
					{ name: 'MALDIVES', value: 'MALDIVES' },
					{ name: 'MALI', value: 'MALI' },
					{ name: 'MALTA', value: 'MALTA' },
					{ name: 'MARSHALL ISLANDS', value: 'MARSHALL ISLANDS' },
					{ name: 'MARTINIQUE', value: 'MARTINIQUE' },
					{ name: 'MAURITANIA', value: 'MAURITANIA' },
					{ name: 'MAURITIUS', value: 'MAURITIUS' },
					{ name: 'MAYOTTE', value: 'MAYOTTE' },
					{ name: 'MEXICO', value: 'MEXICO' },
					{ name: 'MICRONESIA, FEDERATED STATES OF', value: 'MICRONESIA, FEDERATED STATES OF' },
					{ name: 'MOLDOVA, REPUBLIC OF', value: 'MOLDOVA, REPUBLIC OF' },
					{ name: 'MONACO', value: 'MONACO' },
					{ name: 'MONGOLIA', value: 'MONGOLIA' },
					{ name: 'MONTSERRAT', value: 'MONTSERRAT' },
					{ name: 'MOROCCO', value: 'MOROCCO' },
					{ name: 'MOZAMBIQUE', value: 'MOZAMBIQUE' },
					{ name: 'MYANMAR', value: 'MYANMAR' },
					{ name: 'NAMIBIA', value: 'NAMIBIA' },
					{ name: 'NAURU', value: 'NAURU' },
					{ name: 'NEPAL', value: 'NEPAL' },
					{ name: 'NETHERLANDS', value: 'NETHERLANDS' },
					{ name: 'NETHERLANDS ANTILLES', value: 'NETHERLANDS ANTILLES' },
					{ name: 'NEW CALEDONIA', value: 'NEW CALEDONIA' },
					{ name: 'NEW ZEALAND', value: 'NEW ZEALAND' },
					{ name: 'NICARAGUA', value: 'NICARAGUA' },
					{ name: 'NIGER', value: 'NIGER' },
					{ name: 'NIGERIA', value: 'NIGERIA' },
					{ name: 'NIUE', value: 'NIUE' },
					{ name: 'NORFOLK ISLAND', value: 'NORFOLK ISLAND' },
					{ name: 'NORTHERN MARIANA ISLANDS', value: 'NORTHERN MARIANA ISLANDS' },
					{ name: 'NORWAY', value: 'NORWAY' },
					{ name: 'OMAN', value: 'OMAN' },
					{ name: 'PAKISTAN', value: 'PAKISTAN' },
					{ name: 'PALAU', value: 'PALAU' },
					{ name: 'PALESTINIAN TERRITORY, OCCUPIED', value: 'PALESTINIAN TERRITORY, OCCUPIED' },
					{ name: 'PANAMA', value: 'PANAMA' },
					{ name: 'PAPUA NEW GUINEA', value: 'PAPUA NEW GUINEA' },
					{ name: 'PARAGUAY', value: 'PARAGUAY' },
					{ name: 'PERU', value: 'PERU' },
					{ name: 'PHILIPPINES', value: 'PHILIPPINES' },
					{ name: 'PITCAIRN', value: 'PITCAIRN' },
					{ name: 'POLAND', value: 'POLAND' },
					{ name: 'PORTUGAL', value: 'PORTUGAL' },
					{ name: 'PUERTO RICO', value: 'PUERTO RICO' },
					{ name: 'QATAR', value: 'QATAR' },
					{ name: 'REUNION', value: 'REUNION' },
					{ name: 'ROMANIA', value: 'ROMANIA' },
					{ name: 'RUSSIAN FEDERATION', value: 'RUSSIAN FEDERATION' },
					{ name: 'RWANDA', value: 'RWANDA' },
					{ name: 'SAINT HELENA', value: 'SAINT HELENA' },
					{ name: 'SAINT KITTS AND NEVIS', value: 'SAINT KITTS AND NEVIS' },
					{ name: 'SAINT LUCIA', value: 'SAINT LUCIA' },
					{ name: 'SAINT PIERRE AND MIQUELON', value: 'SAINT PIERRE AND MIQUELON' },
					{ name: 'SAINT VINCENT AND THE GRENADINES', value: 'SAINT VINCENT AND THE GRENADINES' },
					{ name: 'SAMOA', value: 'SAMOA' },
					{ name: 'SAN MARINO', value: 'SAN MARINO' },
					{ name: 'SAO TOME AND PRINCIPE', value: 'SAO TOME AND PRINCIPE' },
					{ name: 'SAUDI ARABIA', value: 'SAUDI ARABIA' },
					{ name: 'SENEGAL', value: 'SENEGAL' },
					{ name: 'SEYCHELLES', value: 'SEYCHELLES' },
					{ name: 'SIERRA LEONE', value: 'SIERRA LEONE' },
					{ name: 'SINGAPORE', value: 'SINGAPORE' },
					{ name: 'SLOVAKIA', value: 'SLOVAKIA' },
					{ name: 'SLOVENIA', value: 'SLOVENIA' },
					{ name: 'SOLOMON ISLANDS', value: 'SOLOMON ISLANDS' },
					{ name: 'SOMALIA', value: 'SOMALIA' },
					{ name: 'SOUTH AFRICA', value: 'SOUTH AFRICA' },
					{ name: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', value: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' },
					{ name: 'SPAIN', value: 'SPAIN' },
					{ name: 'SRI LANKA', value: 'SRI LANKA' },
					{ name: 'SUDAN', value: 'SUDAN' },
					{ name: 'SURINAME', value: 'SURINAME' },
					{ name: 'SVALBARD AND JAN MAYEN', value: 'SVALBARD AND JAN MAYEN' },
					{ name: 'SWAZILAND', value: 'SWAZILAND' },
					{ name: 'SWEDEN', value: 'SWEDEN' },
					{ name: 'SWITZERLAND', value: 'SWITZERLAND' },
					{ name: 'SYRIAN ARAB REPUBLIC', value: 'SYRIAN ARAB REPUBLIC' },
					{ name: 'TAIWAN, PROVINCE OF CHINA', value: 'TAIWAN, PROVINCE OF CHINA' },
					{ name: 'TAJIKISTAN', value: 'TAJIKISTAN' },
					{ name: 'TANZANIA, UNITED REPUBLIC OF', value: 'TANZANIA, UNITED REPUBLIC OF' },
					{ name: 'THAILAND', value: 'THAILAND' },
					{ name: 'TIMOR-LESTE', value: 'TIMOR-LESTE' },
					{ name: 'TOGO', value: 'TOGO' },
					{ name: 'TOKELAU', value: 'TOKELAU' },
					{ name: 'TONGA', value: 'TONGA' },
					{ name: 'TRINIDAD AND TOBAGO', value: 'TRINIDAD AND TOBAGO' },
					{ name: 'TUNISIA', value: 'TUNISIA' },
					{ name: 'TURKEY', value: 'TURKEY' },
					{ name: 'TURKMENISTAN', value: 'TURKMENISTAN' },
					{ name: 'TURKS AND CAICOS ISLANDS', value: 'TURKS AND CAICOS ISLANDS' },
					{ name: 'TUVALU', value: 'TUVALU' },
					{ name: 'UGANDA', value: 'UGANDA' },
					{ name: 'UKRAINE', value: 'UKRAINE' },
					{ name: 'UNITED ARAB EMIRATES', value: 'UNITED ARAB EMIRATES' },
					{ name: 'UNITED KINGDOM', value: 'UNITED KINGDOM' },
					{ name: 'UNITED STATES', value: 'UNITED STATES' },
					{ name: 'UNITED STATES MINOR OUTLYING ISLANDS', value: 'UNITED STATES MINOR OUTLYING ISLANDS' },
					{ name: 'URUGUAY', value: 'URUGUAY' },
					{ name: 'UZBEKISTAN', value: 'UZBEKISTAN' },
					{ name: 'VANUATU', value: 'VANUATU' },
					{ name: 'VENEZUELA', value: 'VENEZUELA' },
					{ name: 'VIET NAM', value: 'VIET NAM' },
					{ name: 'VIRGIN ISLANDS, BRITISH', value: 'VIRGIN ISLANDS, BRITISH' },
					{ name: 'VIRGIN ISLANDS, U.S.', value: 'VIRGIN ISLANDS, U.S.' },
					{ name: 'WALLIS AND FUTUNA', value: 'WALLIS AND FUTUNA' },
					{ name: 'WESTERN SAHARA', value: 'WESTERN SAHARA' },
					{ name: 'YEMEN', value: 'YEMEN' },
					{ name: 'ZAMBIA', value: 'ZAMBIA' },
					{ name: 'ZIMBABWE', value: 'ZIMBABWE' }
				],
				default: 'INDIA',
			},
			{
				displayName: 'Email',
				name: 'address_email',
				type: 'string',
				default: '',
				placeholder: 'Enter email',
			},
			{
				displayName: 'GSTIN',
				name: 'address_gstin',
				type: 'string',
				default: '',
				placeholder: 'Enter GST',
			},
			{
				displayName: 'Mobile',
				name: 'address_mobile',
				type: 'string',
				default: '',
				placeholder: 'Enter mobile',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Inactive', value: 'inactive' },
				],
				default: 'active',
			},
		],
	},

	{
		displayName: 'Additional Fields',
		name: 'contactAdditionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				operation: ['updateContact'],
			},
		},
		// eslint-disable-next-line n8n-nodes-base/node-param-collection-type-unsorted-items
		options: [
			{ displayName: 'Email', name: 'email', type: 'string', default: '', placeholder: '' },
			{
				displayName: 'Mobile Country Code',
				name: 'mobile_country_code',
				type: 'options',
				// eslint-disable-next-line n8n-nodes-base/node-param-options-type-unsorted-items
				options: [
					{ name: '🇮🇳 India (+91)', value: '+91' },
					{ name: '🇺🇸 USA (+1)', value: '+1' },
					{ name: '🇬🇧 UK (+44)', value: '+44' },
					{ name: '🇸🇬 Singapore (+65)', value: '+65' },
					{ name: '🇦🇪 UAE (+971)', value: '+971' },
				],
				default: '+91',
				description: 'Select the country code for the mobile number',
			},
			{ displayName: 'Mobile', name: 'mobile', type: 'string', default: '', placeholder: '' },
			{ displayName: 'GSTIN', name: 'gstin', type: 'string', default: '', placeholder: '' },
			{
				displayName: 'Business Name',
				name: 'business_name',
				type: 'string',
				default: '',
				placeholder: '',
			},
			{
				displayName: 'Status',
				name: 'status',
				type: 'options',
				options: [
					{ name: 'Active', value: 'active' },
					{ name: 'Inactive', value: 'inactive' },
				],
				default: 'active',
			},
		],
	},

	{
		displayName: 'Address Type',
		name: 'addressType',
		type: 'options',
		options: [
			{ name: 'Billing Address', value: 'billing' },
			{ name: 'Shipping Address', value: 'shipping' },
			{ name: 'Both (Billing & Shipping)', value: 'both' },
		],
		default: 'billing',
		displayOptions: {
			show: { operation: ['addAddress'] },
		},
		description: 'Type of address to add (can add to both billing and shipping at the same time)',
	},

	{
		displayName: 'Address Type',
		name: 'addressType',
		type: 'options',
		options: [
			{ name: 'Billing Address', value: 'billing' },
			{ name: 'Shipping Address', value: 'shipping' },
		],
		default: 'billing',
		displayOptions: {
			show: { operation: ['updateAddress'] },
		},
		description: 'Type of address to update (one type at a time)',
	},

	{
		displayName: 'Address Name or ID',
		name: 'addressSelector',
		type: 'options',
		default: '',
		displayOptions: {
			show: { operation: ['updateAddress'] },
		},
		typeOptions: {
			loadOptionsMethod: 'getAddressOptions',
			loadOptionsDependsOn: ['contactId', 'addressType'],
		},
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
	},

	{
		displayName: 'Address Line 1',
		name: 'address1',
		type: 'string',
		default: '',
		displayOptions: {
			show: { operation: ['updateAddress'] },
		},
		placeholder: 'Enter address line 1',
	},

	{
		displayName: 'Address Line 2',
		name: 'address2',
		type: 'string',
		default: '',
		displayOptions: {
			show: { operation: ['updateAddress'] },
		},
		placeholder: 'Enter address line 2 (optional)',
	},

	{
		displayName: 'City',
		name: 'city',
		type: 'string',
		default: '',
		displayOptions: {
			show: { operation: ['updateAddress'] },
		},
		placeholder: 'Enter city',
	},

	{
		displayName: 'State',
		name: 'state',
		type: 'options',
		options: [
			{ value: 'ANDAMAN AND NICOBAR ISLANDS', name: 'ANDAMAN AND NICOBAR ISLANDS' },
			{ value: 'ANDHRA PRADESH', name: 'ANDHRA PRADESH' },
			{ value: 'ARUNACHAL PRADESH', name: 'ARUNACHAL PRADESH' },
			{ value: 'ASSAM', name: 'ASSAM' },
			{ value: 'BIHAR', name: 'BIHAR' },
			{ value: 'CHANDIGARH', name: 'CHANDIGARH' },
			{ value: 'CHHATTISGARH', name: 'CHHATTISGARH' },
			{ value: 'DADRA AND NAGAR HAVELI', name: 'DADRA AND NAGAR HAVELI' },
			{ value: 'DAMAN AND DIU', name: 'DAMAN AND DIU' },
			{ value: 'DELHI', name: 'DELHI' },
			{ value: 'GOA', name: 'GOA' },
			{ value: 'GUJARAT', name: 'GUJARAT' },
			{ value: 'HARYANA', name: 'HARYANA' },
			{ value: 'HIMACHAL PRADESH', name: 'HIMACHAL PRADESH' },
			{ value: 'INTERNATIONAL', name: 'INTERNATIONAL' },
			{ value: 'JAMMU AND KASHMIR', name: 'JAMMU AND KASHMIR' },
			{ value: 'JHARKHAND', name: 'JHARKHAND' },
			{ value: 'KARNATAKA', name: 'KARNATAKA' },
			{ value: 'KERALA', name: 'KERALA' },
			{ value: 'LADAKH', name: 'LADAKH' },
			{ value: 'LAKSHADWEEP', name: 'LAKSHADWEEP' },
			{ value: 'MADHYA PRADESH', name: 'MADHYA PRADESH' },
			{ value: 'MAHARASHTRA', name: 'MAHARASHTRA' },
			{ value: 'MANIPUR', name: 'MANIPUR' },
			{ value: 'MEGHALAYA', name: 'MEGHALAYA' },
			{ value: 'MIZORAM', name: 'MIZORAM' },
			{ value: 'NAGALAND', name: 'NAGALAND' },
			{ value: 'ODISHA', name: 'ODISHA' },
			{ value: 'OTHER TERRITORY', name: 'OTHER TERRITORY' },
			{ value: 'PUDUCHERRY', name: 'PUDUCHERRY' },
			{ value: 'PUNJAB', name: 'PUNJAB' },
			{ value: 'RAJASTHAN', name: 'RAJASTHAN' },
			{ value: 'SIKKIM', name: 'SIKKIM' },
			{ value: 'TAMIL NADU', name: 'TAMIL NADU' },
			{ value: 'TELANGANA', name: 'TELANGANA' },
			{ value: 'TRIPURA', name: 'TRIPURA' },
			{ value: 'UTTAR PRADESH', name: 'UTTAR PRADESH' },
			{ value: 'UTTARAKHAND', name: 'UTTARAKHAND' },
			{ value: 'WEST BENGAL', name: 'WEST BENGAL' }
		],
		default: 'TAMIL NADU',
		displayOptions: {
			show: { operation: ['updateAddress'] },
		},
	},

	{
		displayName: 'Country',
		name: 'country',
		type: 'options',
		options: [
			{ name: 'AFGHANISTAN', value: 'AFGHANISTAN' },
			{ name: 'ALBANIA', value: 'ALBANIA' },
			{ name: 'ALGERIA', value: 'ALGERIA' },
			{ name: 'AMERICAN SAMOA', value: 'AMERICAN SAMOA' },
			{ name: 'ANDORRA', value: 'ANDORRA' },
			{ name: 'ANGOLA', value: 'ANGOLA' },
			{ name: 'ANGUILLA', value: 'ANGUILLA' },
			{ name: 'ANTIGUA AND BARBUDA', value: 'ANTIGUA AND BARBUDA' },
			{ name: 'ARGENTINA', value: 'ARGENTINA' },
			{ name: 'ARMENIA', value: 'ARMENIA' },
			{ name: 'ARUBA', value: 'ARUBA' },
			{ name: 'AUSTRALIA', value: 'AUSTRALIA' },
			{ name: 'AUSTRIA', value: 'AUSTRIA' },
			{ name: 'AZERBAIJAN', value: 'AZERBAIJAN' },
			{ name: 'BAHAMAS', value: 'BAHAMAS' },
			{ name: 'BAHRAIN', value: 'BAHRAIN' },
			{ name: 'BANGLADESH', value: 'BANGLADESH' },
			{ name: 'BARBADOS', value: 'BARBADOS' },
			{ name: 'BELARUS', value: 'BELARUS' },
			{ name: 'BELGIUM', value: 'BELGIUM' },
			{ name: 'BELIZE', value: 'BELIZE' },
			{ name: 'BENIN', value: 'BENIN' },
			{ name: 'BERMUDA', value: 'BERMUDA' },
			{ name: 'BHUTAN', value: 'BHUTAN' },
			{ name: 'BOLIVIA', value: 'BOLIVIA' },
			{ name: 'BOSNIA AND HERZEGOVINA', value: 'BOSNIA AND HERZEGOVINA' },
			{ name: 'BOTSWANA', value: 'BOTSWANA' },
			{ name: 'BOUVET ISLAND', value: 'BOUVET ISLAND' },
			{ name: 'BRAZIL', value: 'BRAZIL' },
			{ name: 'BRITISH INDIAN OCEAN TERRITORY', value: 'BRITISH INDIAN OCEAN TERRITORY' },
			{ name: 'BRUNEI DARUSSALAM', value: 'BRUNEI DARUSSALAM' },
			{ name: 'BULGARIA', value: 'BULGARIA' },
			{ name: 'BURKINA FASO', value: 'BURKINA FASO' },
			{ name: 'BURUNDI', value: 'BURUNDI' },
			{ name: 'CAMBODIA', value: 'CAMBODIA' },
			{ name: 'CAMEROON', value: 'CAMEROON' },
			{ name: 'CANADA', value: 'CANADA' },
			{ name: 'CAPE VERDE', value: 'CAPE VERDE' },
			{ name: 'CAYMAN ISLANDS', value: 'CAYMAN ISLANDS' },
			{ name: 'CENTRAL AFRICAN REPUBLIC', value: 'CENTRAL AFRICAN REPUBLIC' },
			{ name: 'CHAD', value: 'CHAD' },
			{ name: 'CHILE', value: 'CHILE' },
			{ name: 'CHINA', value: 'CHINA' },
			{ name: 'CHRISTMAS ISLAND', value: 'CHRISTMAS ISLAND' },
			{ name: 'COCOS (KEELING) ISLANDS', value: 'COCOS (KEELING) ISLANDS' },
			{ name: 'COLOMBIA', value: 'COLOMBIA' },
			{ name: 'COMOROS', value: 'COMOROS' },
			{ name: 'CONGO', value: 'CONGO' },
			{ name: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', value: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE' },
			{ name: 'COOK ISLANDS', value: 'COOK ISLANDS' },
			{ name: 'COSTA RICA', value: 'COSTA RICA' },
			{ name: 'COTE D`IVOIRE', value: 'COTE D`IVOIRE' },
			{ name: 'CROATIA', value: 'CROATIA' },
			{ name: 'CUBA', value: 'CUBA' },
			{ name: 'CYPRUS', value: 'CYPRUS' },
			{ name: 'CZECH REPUBLIC', value: 'CZECH REPUBLIC' },
			{ name: 'DENMARK', value: 'DENMARK' },
			{ name: 'DJIBOUTI', value: 'DJIBOUTI' },
			{ name: 'DOMINICA', value: 'DOMINICA' },
			{ name: 'DOMINICAN REPUBLIC', value: 'DOMINICAN REPUBLIC' },
			{ name: 'EAST TIMOR', value: 'EAST TIMOR' },
			{ name: 'ECUADOR', value: 'ECUADOR' },
			{ name: 'EGYPT', value: 'EGYPT' },
			{ name: 'EL SALVADOR', value: 'EL SALVADOR' },
			{ name: 'EQUATORIAL GUINEA', value: 'EQUATORIAL GUINEA' },
			{ name: 'ERITREA', value: 'ERITREA' },
			{ name: 'ESTONIA', value: 'ESTONIA' },
			{ name: 'ETHIOPIA', value: 'ETHIOPIA' },
			{ name: 'FALKLAND ISLANDS (MALVINAS)', value: 'FALKLAND ISLANDS (MALVINAS)' },
			{ name: 'FAROE ISLANDS', value: 'FAROE ISLANDS' },
			{ name: 'FIJI', value: 'FIJI' },
			{ name: 'FINLAND', value: 'FINLAND' },
			{ name: 'FRANCE', value: 'FRANCE' },
			{ name: 'FRENCH GUIANA', value: 'FRENCH GUIANA' },
			{ name: 'FRENCH POLYNESIA', value: 'FRENCH POLYNESIA' },
			{ name: 'FRENCH SOUTHERN TERRITORIES', value: 'FRENCH SOUTHERN TERRITORIES' },
			{ name: 'GABON', value: 'GABON' },
			{ name: 'GAMBIA', value: 'GAMBIA' },
			{ name: 'GEORGIA', value: 'GEORGIA' },
			{ name: 'GERMANY', value: 'GERMANY' },
			{ name: 'GHANA', value: 'GHANA' },
			{ name: 'GIBRALTAR', value: 'GIBRALTAR' },
			{ name: 'GREECE', value: 'GREECE' },
			{ name: 'GREENLAND', value: 'GREENLAND' },
			{ name: 'GRENADA', value: 'GRENADA' },
			{ name: 'GUADELOUPE', value: 'GUADELOUPE' },
			{ name: 'GUAM', value: 'GUAM' },
			{ name: 'GUATEMALA', value: 'GUATEMALA' },
			{ name: 'GUINEA', value: 'GUINEA' },
			{ name: 'GUINEA-BISSAU', value: 'GUINEA-BISSAU' },
			{ name: 'GUYANA', value: 'GUYANA' },
			{ name: 'HAITI', value: 'HAITI' },
			{ name: 'HEARD ISLAND AND MCDONALD ISLANDS', value: 'HEARD ISLAND AND MCDONALD ISLANDS' },
			{ name: 'HOLY SEE (VATICAN CITY STATE)', value: 'HOLY SEE (VATICAN CITY STATE)' },
			{ name: 'HONDURAS', value: 'HONDURAS' },
			{ name: 'HONG KONG', value: 'HONG KONG' },
			{ name: 'HUNGARY', value: 'HUNGARY' },
			{ name: 'ICELAND', value: 'ICELAND' },
			{ name: 'INDIA', value: 'INDIA' },
			{ name: 'INDONESIA', value: 'INDONESIA' },
			{ name: 'IRAN (ISLAMIC REPUBLIC OF)', value: 'IRAN (ISLAMIC REPUBLIC OF)' },
			{ name: 'IRAQ', value: 'IRAQ' },
			{ name: 'IRELAND', value: 'IRELAND' },
			{ name: 'ISRAEL', value: 'ISRAEL' },
			{ name: 'ITALY', value: 'ITALY' },
			{ name: 'JAMAICA', value: 'JAMAICA' },
			{ name: 'JAPAN', value: 'JAPAN' },
			{ name: 'JORDAN', value: 'JORDAN' },
			{ name: 'KAZAKHSTAN', value: 'KAZAKHSTAN' },
			{ name: 'KENYA', value: 'KENYA' },
			{ name: 'KIRIBATI', value: 'KIRIBATI' },
			{ name: 'KOREA, DEMOCRATIC PEOPLE`S REPUBLIC OF', value: 'KOREA, DEMOCRATIC PEOPLE`S REPUBLIC OF' },
			{ name: 'KOREA, REPUBLIC OF', value: 'KOREA, REPUBLIC OF' },
			{ name: 'KUWAIT', value: 'KUWAIT' },
			{ name: 'KYRGYZSTAN', value: 'KYRGYZSTAN' },
			{ name: 'LAO PEOPLE`S DEMOCRATIC REPUBLIC', value: 'LAO PEOPLE`S DEMOCRATIC REPUBLIC' },
			{ name: 'LATVIA', value: 'LATVIA' },
			{ name: 'LEBANON', value: 'LEBANON' },
			{ name: 'LESOTHO', value: 'LESOTHO' },
			{ name: 'LIBERIA', value: 'LIBERIA' },
			{ name: 'LIBYAN ARAB JAMAHIRIYA', value: 'LIBYAN ARAB JAMAHIRIYA' },
			{ name: 'LIECHTENSTEIN', value: 'LIECHTENSTEIN' },
			{ name: 'LITHUANIA', value: 'LITHUANIA' },
			{ name: 'LUXEMBOURG', value: 'LUXEMBOURG' },
			{ name: 'MACAO', value: 'MACAO' },
			{ name: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', value: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF' },
			{ name: 'MADAGASCAR', value: 'MADAGASCAR' },
			{ name: 'MALAWI', value: 'MALAWI' },
			{ name: 'MALAYSIA', value: 'MALAYSIA' },
			{ name: 'MALDIVES', value: 'MALDIVES' },
			{ name: 'MALI', value: 'MALI' },
			{ name: 'MALTA', value: 'MALTA' },
			{ name: 'MARSHALL ISLANDS', value: 'MARSHALL ISLANDS' },
			{ name: 'MARTINIQUE', value: 'MARTINIQUE' },
			{ name: 'MAURITANIA', value: 'MAURITANIA' },
			{ name: 'MAURITIUS', value: 'MAURITIUS' },
			{ name: 'MAYOTTE', value: 'MAYOTTE' },
			{ name: 'MEXICO', value: 'MEXICO' },
			{ name: 'MICRONESIA, FEDERATED STATES OF', value: 'MICRONESIA, FEDERATED STATES OF' },
			{ name: 'MOLDOVA, REPUBLIC OF', value: 'MOLDOVA, REPUBLIC OF' },
			{ name: 'MONACO', value: 'MONACO' },
			{ name: 'MONGOLIA', value: 'MONGOLIA' },
			{ name: 'MONTSERRAT', value: 'MONTSERRAT' },
			{ name: 'MOROCCO', value: 'MOROCCO' },
			{ name: 'MOZAMBIQUE', value: 'MOZAMBIQUE' },
			{ name: 'MYANMAR', value: 'MYANMAR' },
			{ name: 'NAMIBIA', value: 'NAMIBIA' },
			{ name: 'NAURU', value: 'NAURU' },
			{ name: 'NEPAL', value: 'NEPAL' },
			{ name: 'NETHERLANDS', value: 'NETHERLANDS' },
			{ name: 'NETHERLANDS ANTILLES', value: 'NETHERLANDS ANTILLES' },
			{ name: 'NEW CALEDONIA', value: 'NEW CALEDONIA' },
			{ name: 'NEW ZEALAND', value: 'NEW ZEALAND' },
			{ name: 'NICARAGUA', value: 'NICARAGUA' },
			{ name: 'NIGER', value: 'NIGER' },
			{ name: 'NIGERIA', value: 'NIGERIA' },
			{ name: 'NIUE', value: 'NIUE' },
			{ name: 'NORFOLK ISLAND', value: 'NORFOLK ISLAND' },
			{ name: 'NORTHERN MARIANA ISLANDS', value: 'NORTHERN MARIANA ISLANDS' },
			{ name: 'NORWAY', value: 'NORWAY' },
			{ name: 'OMAN', value: 'OMAN' },
			{ name: 'PAKISTAN', value: 'PAKISTAN' },
			{ name: 'PALAU', value: 'PALAU' },
			{ name: 'PALESTINIAN TERRITORY, OCCUPIED', value: 'PALESTINIAN TERRITORY, OCCUPIED' },
			{ name: 'PANAMA', value: 'PANAMA' },
			{ name: 'PAPUA NEW GUINEA', value: 'PAPUA NEW GUINEA' },
			{ name: 'PARAGUAY', value: 'PARAGUAY' },
			{ name: 'PERU', value: 'PERU' },
			{ name: 'PHILIPPINES', value: 'PHILIPPINES' },
			{ name: 'PITCAIRN', value: 'PITCAIRN' },
			{ name: 'POLAND', value: 'POLAND' },
			{ name: 'PORTUGAL', value: 'PORTUGAL' },
			{ name: 'PUERTO RICO', value: 'PUERTO RICO' },
			{ name: 'QATAR', value: 'QATAR' },
			{ name: 'REUNION', value: 'REUNION' },
			{ name: 'ROMANIA', value: 'ROMANIA' },
			{ name: 'RUSSIAN FEDERATION', value: 'RUSSIAN FEDERATION' },
			{ name: 'RWANDA', value: 'RWANDA' },
			{ name: 'SAINT HELENA', value: 'SAINT HELENA' },
			{ name: 'SAINT KITTS AND NEVIS', value: 'SAINT KITTS AND NEVIS' },
			{ name: 'SAINT LUCIA', value: 'SAINT LUCIA' },
			{ name: 'SAINT PIERRE AND MIQUELON', value: 'SAINT PIERRE AND MIQUELON' },
			{ name: 'SAINT VINCENT AND THE GRENADINES', value: 'SAINT VINCENT AND THE GRENADINES' },
			{ name: 'SAMOA', value: 'SAMOA' },
			{ name: 'SAN MARINO', value: 'SAN MARINO' },
			{ name: 'SAO TOME AND PRINCIPE', value: 'SAO TOME AND PRINCIPE' },
			{ name: 'SAUDI ARABIA', value: 'SAUDI ARABIA' },
			{ name: 'SENEGAL', value: 'SENEGAL' },
			{ name: 'SEYCHELLES', value: 'SEYCHELLES' },
			{ name: 'SIERRA LEONE', value: 'SIERRA LEONE' },
			{ name: 'SINGAPORE', value: 'SINGAPORE' },
			{ name: 'SLOVAKIA', value: 'SLOVAKIA' },
			{ name: 'SLOVENIA', value: 'SLOVENIA' },
			{ name: 'SOLOMON ISLANDS', value: 'SOLOMON ISLANDS' },
			{ name: 'SOMALIA', value: 'SOMALIA' },
			{ name: 'SOUTH AFRICA', value: 'SOUTH AFRICA' },
			{ name: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', value: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' },
			{ name: 'SPAIN', value: 'SPAIN' },
			{ name: 'SRI LANKA', value: 'SRI LANKA' },
			{ name: 'SUDAN', value: 'SUDAN' },
			{ name: 'SURINAME', value: 'SURINAME' },
			{ name: 'SVALBARD AND JAN MAYEN', value: 'SVALBARD AND JAN MAYEN' },
			{ name: 'SWAZILAND', value: 'SWAZILAND' },
			{ name: 'SWEDEN', value: 'SWEDEN' },
			{ name: 'SWITZERLAND', value: 'SWITZERLAND' },
			{ name: 'SYRIAN ARAB REPUBLIC', value: 'SYRIAN ARAB REPUBLIC' },
			{ name: 'TAIWAN, PROVINCE OF CHINA', value: 'TAIWAN, PROVINCE OF CHINA' },
			{ name: 'TAJIKISTAN', value: 'TAJIKISTAN' },
			{ name: 'TANZANIA, UNITED REPUBLIC OF', value: 'TANZANIA, UNITED REPUBLIC OF' },
			{ name: 'THAILAND', value: 'THAILAND' },
			{ name: 'TIMOR-LESTE', value: 'TIMOR-LESTE' },
			{ name: 'TOGO', value: 'TOGO' },
			{ name: 'TOKELAU', value: 'TOKELAU' },
			{ name: 'TONGA', value: 'TONGA' },
			{ name: 'TRINIDAD AND TOBAGO', value: 'TRINIDAD AND TOBAGO' },
			{ name: 'TUNISIA', value: 'TUNISIA' },
			{ name: 'TURKEY', value: 'TURKEY' },
			{ name: 'TURKMENISTAN', value: 'TURKMENISTAN' },
			{ name: 'TURKS AND CAICOS ISLANDS', value: 'TURKS AND CAICOS ISLANDS' },
			{ name: 'TUVALU', value: 'TUVALU' },
			{ name: 'UGANDA', value: 'UGANDA' },
			{ name: 'UKRAINE', value: 'UKRAINE' },
			{ name: 'UNITED ARAB EMIRATES', value: 'UNITED ARAB EMIRATES' },
			{ name: 'UNITED KINGDOM', value: 'UNITED KINGDOM' },
			{ name: 'UNITED STATES', value: 'UNITED STATES' },
			{ name: 'UNITED STATES MINOR OUTLYING ISLANDS', value: 'UNITED STATES MINOR OUTLYING ISLANDS' },
			{ name: 'URUGUAY', value: 'URUGUAY' },
			{ name: 'UZBEKISTAN', value: 'UZBEKISTAN' },
			{ name: 'VANUATU', value: 'VANUATU' },
			{ name: 'VENEZUELA', value: 'VENEZUELA' },
			{ name: 'VIET NAM', value: 'VIET NAM' },
			{ name: 'VIRGIN ISLANDS, BRITISH', value: 'VIRGIN ISLANDS, BRITISH' },
			{ name: 'VIRGIN ISLANDS, U.S.', value: 'VIRGIN ISLANDS, U.S.' },
			{ name: 'WALLIS AND FUTUNA', value: 'WALLIS AND FUTUNA' },
			{ name: 'WESTERN SAHARA', value: 'WESTERN SAHARA' },
			{ name: 'YEMEN', value: 'YEMEN' },
			{ name: 'ZAMBIA', value: 'ZAMBIA' },
			{ name: 'ZIMBABWE', value: 'ZIMBABWE' }
		],
		default: 'INDIA',
		displayOptions: {
			show: { operation: ['updateAddress'] },
		},
	},
	{
		displayName: 'Email',
		name: 'update_address_email',
		type: 'string',
		default: '',
		placeholder: 'Enter email',
		displayOptions: {
			show: { operation: ['updateAddress'] },
		},
	},
	{
		displayName: 'GSTIN',
		name: 'update_address_gstin',
		type: 'string',
		default: '',
		placeholder: 'Enter GST',
		displayOptions: {
			show: { operation: ['updateAddress'] },
		},
	},
	{
		displayName: 'Mobile',
		name: 'update_address_mobile',
		type: 'string',
		default: '',
		placeholder: 'Enter mobile',
		displayOptions: {
			show: { operation: ['updateAddress'] },
		},
	},

	{
		displayName: 'Pincode',
		name: 'pincode',
		type: 'string',
		default: '',
		displayOptions: {
			show: { operation: ['updateAddress'] },
		},
		placeholder: 'Enter pincode',
	},

	{
		displayName: 'Address Fields',
		name: 'addressFields',
		type: 'collection',
		placeholder: 'Add Address Field',
		default: {},
		displayOptions: {
			show: { operation: ['addAddress'] },
		},
		options: [
			{
				displayName: 'Address Line 1',
				name: 'address1',
				type: 'string',
				default: '',
				placeholder: 'Enter address line 1',
			},
			{
				displayName: 'Address Line 2',
				name: 'address2',
				type: 'string',
				default: '',
				placeholder: 'Enter address line 2 (optional)',
			},
			{
				displayName: 'City',
				name: 'location',
				type: 'string',
				default: '',
				placeholder: 'Enter city',
			},
			{
				displayName: 'Country',
				name: 'country',
				type: 'options',
				options: [
					{ name: 'AFGHANISTAN', value: 'AFGHANISTAN' },
					{ name: 'ALBANIA', value: 'ALBANIA' },
					{ name: 'ALGERIA', value: 'ALGERIA' },
					{ name: 'AMERICAN SAMOA', value: 'AMERICAN SAMOA' },
					{ name: 'ANDORRA', value: 'ANDORRA' },
					{ name: 'ANGOLA', value: 'ANGOLA' },
					{ name: 'ANGUILLA', value: 'ANGUILLA' },
					{ name: 'ANTIGUA AND BARBUDA', value: 'ANTIGUA AND BARBUDA' },
					{ name: 'ARGENTINA', value: 'ARGENTINA' },
					{ name: 'ARMENIA', value: 'ARMENIA' },
					{ name: 'ARUBA', value: 'ARUBA' },
					{ name: 'AUSTRALIA', value: 'AUSTRALIA' },
					{ name: 'AUSTRIA', value: 'AUSTRIA' },
					{ name: 'AZERBAIJAN', value: 'AZERBAIJAN' },
					{ name: 'BAHAMAS', value: 'BAHAMAS' },
					{ name: 'BAHRAIN', value: 'BAHRAIN' },
					{ name: 'BANGLADESH', value: 'BANGLADESH' },
					{ name: 'BARBADOS', value: 'BARBADOS' },
					{ name: 'BELARUS', value: 'BELARUS' },
					{ name: 'BELGIUM', value: 'BELGIUM' },
					{ name: 'BELIZE', value: 'BELIZE' },
					{ name: 'BENIN', value: 'BENIN' },
					{ name: 'BERMUDA', value: 'BERMUDA' },
					{ name: 'BHUTAN', value: 'BHUTAN' },
					{ name: 'BOLIVIA', value: 'BOLIVIA' },
					{ name: 'BOSNIA AND HERZEGOVINA', value: 'BOSNIA AND HERZEGOVINA' },
					{ name: 'BOTSWANA', value: 'BOTSWANA' },
					{ name: 'BOUVET ISLAND', value: 'BOUVET ISLAND' },
					{ name: 'BRAZIL', value: 'BRAZIL' },
					{ name: 'BRITISH INDIAN OCEAN TERRITORY', value: 'BRITISH INDIAN OCEAN TERRITORY' },
					{ name: 'BRUNEI DARUSSALAM', value: 'BRUNEI DARUSSALAM' },
					{ name: 'BULGARIA', value: 'BULGARIA' },
					{ name: 'BURKINA FASO', value: 'BURKINA FASO' },
					{ name: 'BURUNDI', value: 'BURUNDI' },
					{ name: 'CAMBODIA', value: 'CAMBODIA' },
					{ name: 'CAMEROON', value: 'CAMEROON' },
					{ name: 'CANADA', value: 'CANADA' },
					{ name: 'CAPE VERDE', value: 'CAPE VERDE' },
					{ name: 'CAYMAN ISLANDS', value: 'CAYMAN ISLANDS' },
					{ name: 'CENTRAL AFRICAN REPUBLIC', value: 'CENTRAL AFRICAN REPUBLIC' },
					{ name: 'CHAD', value: 'CHAD' },
					{ name: 'CHILE', value: 'CHILE' },
					{ name: 'CHINA', value: 'CHINA' },
					{ name: 'CHRISTMAS ISLAND', value: 'CHRISTMAS ISLAND' },
					{ name: 'COCOS (KEELING) ISLANDS', value: 'COCOS (KEELING) ISLANDS' },
					{ name: 'COLOMBIA', value: 'COLOMBIA' },
					{ name: 'COMOROS', value: 'COMOROS' },
					{ name: 'CONGO', value: 'CONGO' },
					{ name: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', value: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE' },
					{ name: 'COOK ISLANDS', value: 'COOK ISLANDS' },
					{ name: 'COSTA RICA', value: 'COSTA RICA' },
					{ name: 'COTE D`IVOIRE', value: 'COTE D`IVOIRE' },
					{ name: 'CROATIA', value: 'CROATIA' },
					{ name: 'CUBA', value: 'CUBA' },
					{ name: 'CYPRUS', value: 'CYPRUS' },
					{ name: 'CZECH REPUBLIC', value: 'CZECH REPUBLIC' },
					{ name: 'DENMARK', value: 'DENMARK' },
					{ name: 'DJIBOUTI', value: 'DJIBOUTI' },
					{ name: 'DOMINICA', value: 'DOMINICA' },
					{ name: 'DOMINICAN REPUBLIC', value: 'DOMINICAN REPUBLIC' },
					{ name: 'EAST TIMOR', value: 'EAST TIMOR' },
					{ name: 'ECUADOR', value: 'ECUADOR' },
					{ name: 'EGYPT', value: 'EGYPT' },
					{ name: 'EL SALVADOR', value: 'EL SALVADOR' },
					{ name: 'EQUATORIAL GUINEA', value: 'EQUATORIAL GUINEA' },
					{ name: 'ERITREA', value: 'ERITREA' },
					{ name: 'ESTONIA', value: 'ESTONIA' },
					{ name: 'ETHIOPIA', value: 'ETHIOPIA' },
					{ name: 'FALKLAND ISLANDS (MALVINAS)', value: 'FALKLAND ISLANDS (MALVINAS)' },
					{ name: 'FAROE ISLANDS', value: 'FAROE ISLANDS' },
					{ name: 'FIJI', value: 'FIJI' },
					{ name: 'FINLAND', value: 'FINLAND' },
					{ name: 'FRANCE', value: 'FRANCE' },
					{ name: 'FRENCH GUIANA', value: 'FRENCH GUIANA' },
					{ name: 'FRENCH POLYNESIA', value: 'FRENCH POLYNESIA' },
					{ name: 'FRENCH SOUTHERN TERRITORIES', value: 'FRENCH SOUTHERN TERRITORIES' },
					{ name: 'GABON', value: 'GABON' },
					{ name: 'GAMBIA', value: 'GAMBIA' },
					{ name: 'GEORGIA', value: 'GEORGIA' },
					{ name: 'GERMANY', value: 'GERMANY' },
					{ name: 'GHANA', value: 'GHANA' },
					{ name: 'GIBRALTAR', value: 'GIBRALTAR' },
					{ name: 'GREECE', value: 'GREECE' },
					{ name: 'GREENLAND', value: 'GREENLAND' },
					{ name: 'GRENADA', value: 'GRENADA' },
					{ name: 'GUADELOUPE', value: 'GUADELOUPE' },
					{ name: 'GUAM', value: 'GUAM' },
					{ name: 'GUATEMALA', value: 'GUATEMALA' },
					{ name: 'GUINEA', value: 'GUINEA' },
					{ name: 'GUINEA-BISSAU', value: 'GUINEA-BISSAU' },
					{ name: 'GUYANA', value: 'GUYANA' },
					{ name: 'HAITI', value: 'HAITI' },
					{ name: 'HEARD ISLAND AND MCDONALD ISLANDS', value: 'HEARD ISLAND AND MCDONALD ISLANDS' },
					{ name: 'HOLY SEE (VATICAN CITY STATE)', value: 'HOLY SEE (VATICAN CITY STATE)' },
					{ name: 'HONDURAS', value: 'HONDURAS' },
					{ name: 'HONG KONG', value: 'HONG KONG' },
					{ name: 'HUNGARY', value: 'HUNGARY' },
					{ name: 'ICELAND', value: 'ICELAND' },
					{ name: 'INDIA', value: 'INDIA' },
					{ name: 'INDONESIA', value: 'INDONESIA' },
					{ name: 'IRAN (ISLAMIC REPUBLIC OF)', value: 'IRAN (ISLAMIC REPUBLIC OF)' },
					{ name: 'IRAQ', value: 'IRAQ' },
					{ name: 'IRELAND', value: 'IRELAND' },
					{ name: 'ISRAEL', value: 'ISRAEL' },
					{ name: 'ITALY', value: 'ITALY' },
					{ name: 'JAMAICA', value: 'JAMAICA' },
					{ name: 'JAPAN', value: 'JAPAN' },
					{ name: 'JORDAN', value: 'JORDAN' },
					{ name: 'KAZAKHSTAN', value: 'KAZAKHSTAN' },
					{ name: 'KENYA', value: 'KENYA' },
					{ name: 'KIRIBATI', value: 'KIRIBATI' },
					{ name: 'KOREA, DEMOCRATIC PEOPLE`S REPUBLIC OF', value: 'KOREA, DEMOCRATIC PEOPLE`S REPUBLIC OF' },
					{ name: 'KOREA, REPUBLIC OF', value: 'KOREA, REPUBLIC OF' },
					{ name: 'KUWAIT', value: 'KUWAIT' },
					{ name: 'KYRGYZSTAN', value: 'KYRGYZSTAN' },
					{ name: 'LAO PEOPLE`S DEMOCRATIC REPUBLIC', value: 'LAO PEOPLE`S DEMOCRATIC REPUBLIC' },
					{ name: 'LATVIA', value: 'LATVIA' },
					{ name: 'LEBANON', value: 'LEBANON' },
					{ name: 'LESOTHO', value: 'LESOTHO' },
					{ name: 'LIBERIA', value: 'LIBERIA' },
					{ name: 'LIBYAN ARAB JAMAHIRIYA', value: 'LIBYAN ARAB JAMAHIRIYA' },
					{ name: 'LIECHTENSTEIN', value: 'LIECHTENSTEIN' },
					{ name: 'LITHUANIA', value: 'LITHUANIA' },
					{ name: 'LUXEMBOURG', value: 'LUXEMBOURG' },
					{ name: 'MACAO', value: 'MACAO' },
					{ name: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', value: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF' },
					{ name: 'MADAGASCAR', value: 'MADAGASCAR' },
					{ name: 'MALAWI', value: 'MALAWI' },
					{ name: 'MALAYSIA', value: 'MALAYSIA' },
					{ name: 'MALDIVES', value: 'MALDIVES' },
					{ name: 'MALI', value: 'MALI' },
					{ name: 'MALTA', value: 'MALTA' },
					{ name: 'MARSHALL ISLANDS', value: 'MARSHALL ISLANDS' },
					{ name: 'MARTINIQUE', value: 'MARTINIQUE' },
					{ name: 'MAURITANIA', value: 'MAURITANIA' },
					{ name: 'MAURITIUS', value: 'MAURITIUS' },
					{ name: 'MAYOTTE', value: 'MAYOTTE' },
					{ name: 'MEXICO', value: 'MEXICO' },
					{ name: 'MICRONESIA, FEDERATED STATES OF', value: 'MICRONESIA, FEDERATED STATES OF' },
					{ name: 'MOLDOVA, REPUBLIC OF', value: 'MOLDOVA, REPUBLIC OF' },
					{ name: 'MONACO', value: 'MONACO' },
					{ name: 'MONGOLIA', value: 'MONGOLIA' },
					{ name: 'MONTSERRAT', value: 'MONTSERRAT' },
					{ name: 'MOROCCO', value: 'MOROCCO' },
					{ name: 'MOZAMBIQUE', value: 'MOZAMBIQUE' },
					{ name: 'MYANMAR', value: 'MYANMAR' },
					{ name: 'NAMIBIA', value: 'NAMIBIA' },
					{ name: 'NAURU', value: 'NAURU' },
					{ name: 'NEPAL', value: 'NEPAL' },
					{ name: 'NETHERLANDS', value: 'NETHERLANDS' },
					{ name: 'NETHERLANDS ANTILLES', value: 'NETHERLANDS ANTILLES' },
					{ name: 'NEW CALEDONIA', value: 'NEW CALEDONIA' },
					{ name: 'NEW ZEALAND', value: 'NEW ZEALAND' },
					{ name: 'NICARAGUA', value: 'NICARAGUA' },
					{ name: 'NIGER', value: 'NIGER' },
					{ name: 'NIGERIA', value: 'NIGERIA' },
					{ name: 'NIUE', value: 'NIUE' },
					{ name: 'NORFOLK ISLAND', value: 'NORFOLK ISLAND' },
					{ name: 'NORTHERN MARIANA ISLANDS', value: 'NORTHERN MARIANA ISLANDS' },
					{ name: 'NORWAY', value: 'NORWAY' },
					{ name: 'OMAN', value: 'OMAN' },
					{ name: 'PAKISTAN', value: 'PAKISTAN' },
					{ name: 'PALAU', value: 'PALAU' },
					{ name: 'PALESTINIAN TERRITORY, OCCUPIED', value: 'PALESTINIAN TERRITORY, OCCUPIED' },
					{ name: 'PANAMA', value: 'PANAMA' },
					{ name: 'PAPUA NEW GUINEA', value: 'PAPUA NEW GUINEA' },
					{ name: 'PARAGUAY', value: 'PARAGUAY' },
					{ name: 'PERU', value: 'PERU' },
					{ name: 'PHILIPPINES', value: 'PHILIPPINES' },
					{ name: 'PITCAIRN', value: 'PITCAIRN' },
					{ name: 'POLAND', value: 'POLAND' },
					{ name: 'PORTUGAL', value: 'PORTUGAL' },
					{ name: 'PUERTO RICO', value: 'PUERTO RICO' },
					{ name: 'QATAR', value: 'QATAR' },
					{ name: 'REUNION', value: 'REUNION' },
					{ name: 'ROMANIA', value: 'ROMANIA' },
					{ name: 'RUSSIAN FEDERATION', value: 'RUSSIAN FEDERATION' },
					{ name: 'RWANDA', value: 'RWANDA' },
					{ name: 'SAINT HELENA', value: 'SAINT HELENA' },
					{ name: 'SAINT KITTS AND NEVIS', value: 'SAINT KITTS AND NEVIS' },
					{ name: 'SAINT LUCIA', value: 'SAINT LUCIA' },
					{ name: 'SAINT PIERRE AND MIQUELON', value: 'SAINT PIERRE AND MIQUELON' },
					{ name: 'SAINT VINCENT AND THE GRENADINES', value: 'SAINT VINCENT AND THE GRENADINES' },
					{ name: 'SAMOA', value: 'SAMOA' },
					{ name: 'SAN MARINO', value: 'SAN MARINO' },
					{ name: 'SAO TOME AND PRINCIPE', value: 'SAO TOME AND PRINCIPE' },
					{ name: 'SAUDI ARABIA', value: 'SAUDI ARABIA' },
					{ name: 'SENEGAL', value: 'SENEGAL' },
					{ name: 'SEYCHELLES', value: 'SEYCHELLES' },
					{ name: 'SIERRA LEONE', value: 'SIERRA LEONE' },
					{ name: 'SINGAPORE', value: 'SINGAPORE' },
					{ name: 'SLOVAKIA', value: 'SLOVAKIA' },
					{ name: 'SLOVENIA', value: 'SLOVENIA' },
					{ name: 'SOLOMON ISLANDS', value: 'SOLOMON ISLANDS' },
					{ name: 'SOMALIA', value: 'SOMALIA' },
					{ name: 'SOUTH AFRICA', value: 'SOUTH AFRICA' },
					{ name: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', value: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' },
					{ name: 'SPAIN', value: 'SPAIN' },
					{ name: 'SRI LANKA', value: 'SRI LANKA' },
					{ name: 'SUDAN', value: 'SUDAN' },
					{ name: 'SURINAME', value: 'SURINAME' },
					{ name: 'SVALBARD AND JAN MAYEN', value: 'SVALBARD AND JAN MAYEN' },
					{ name: 'SWAZILAND', value: 'SWAZILAND' },
					{ name: 'SWEDEN', value: 'SWEDEN' },
					{ name: 'SWITZERLAND', value: 'SWITZERLAND' },
					{ name: 'SYRIAN ARAB REPUBLIC', value: 'SYRIAN ARAB REPUBLIC' },
					{ name: 'TAIWAN, PROVINCE OF CHINA', value: 'TAIWAN, PROVINCE OF CHINA' },
					{ name: 'TAJIKISTAN', value: 'TAJIKISTAN' },
					{ name: 'TANZANIA, UNITED REPUBLIC OF', value: 'TANZANIA, UNITED REPUBLIC OF' },
					{ name: 'THAILAND', value: 'THAILAND' },
					{ name: 'TIMOR-LESTE', value: 'TIMOR-LESTE' },
					{ name: 'TOGO', value: 'TOGO' },
					{ name: 'TOKELAU', value: 'TOKELAU' },
					{ name: 'TONGA', value: 'TONGA' },
					{ name: 'TRINIDAD AND TOBAGO', value: 'TRINIDAD AND TOBAGO' },
					{ name: 'TUNISIA', value: 'TUNISIA' },
					{ name: 'TURKEY', value: 'TURKEY' },
					{ name: 'TURKMENISTAN', value: 'TURKMENISTAN' },
					{ name: 'TURKS AND CAICOS ISLANDS', value: 'TURKS AND CAICOS ISLANDS' },
					{ name: 'TUVALU', value: 'TUVALU' },
					{ name: 'UGANDA', value: 'UGANDA' },
					{ name: 'UKRAINE', value: 'UKRAINE' },
					{ name: 'UNITED ARAB EMIRATES', value: 'UNITED ARAB EMIRATES' },
					{ name: 'UNITED KINGDOM', value: 'UNITED KINGDOM' },
					{ name: 'UNITED STATES', value: 'UNITED STATES' },
					{ name: 'UNITED STATES MINOR OUTLYING ISLANDS', value: 'UNITED STATES MINOR OUTLYING ISLANDS' },
					{ name: 'URUGUAY', value: 'URUGUAY' },
					{ name: 'UZBEKISTAN', value: 'UZBEKISTAN' },
					{ name: 'VANUATU', value: 'VANUATU' },
					{ name: 'VENEZUELA', value: 'VENEZUELA' },
					{ name: 'VIET NAM', value: 'VIET NAM' },
					{ name: 'VIRGIN ISLANDS, BRITISH', value: 'VIRGIN ISLANDS, BRITISH' },
					{ name: 'VIRGIN ISLANDS, U.S.', value: 'VIRGIN ISLANDS, U.S.' },
					{ name: 'WALLIS AND FUTUNA', value: 'WALLIS AND FUTUNA' },
					{ name: 'WESTERN SAHARA', value: 'WESTERN SAHARA' },
					{ name: 'YEMEN', value: 'YEMEN' },
					{ name: 'ZAMBIA', value: 'ZAMBIA' },
					{ name: 'ZIMBABWE', value: 'ZIMBABWE' }
				],
				default: 'INDIA',
			},
			{
				displayName: 'Email',
				name: 'email',
				type: 'string',
				default: '',
				placeholder: 'Enter email',
			},
			{
				displayName: 'GSTIN',
				name: 'gstin',
				type: 'string',
				default: '',
				placeholder: 'Enter GST',
			},
			{
				displayName: 'Mobile',
				name: 'mobile',
				type: 'string',
				default: '',
				placeholder: 'Enter mobile',
			},
			{
				displayName: 'Pincode',
				name: 'pincode',
				type: 'string',
				default: '',
				placeholder: 'Enter pincode',
			},
			{
				displayName: 'State',
				name: 'state',
				type: 'options',
				options: [
					{ value: 'ANDAMAN AND NICOBAR ISLANDS', name: 'ANDAMAN AND NICOBAR ISLANDS' },
					{ value: 'ANDHRA PRADESH', name: 'ANDHRA PRADESH' },
					{ value: 'ARUNACHAL PRADESH', name: 'ARUNACHAL PRADESH' },
					{ value: 'ASSAM', name: 'ASSAM' },
					{ value: 'BIHAR', name: 'BIHAR' },
					{ value: 'CHANDIGARH', name: 'CHANDIGARH' },
					{ value: 'CHHATTISGARH', name: 'CHHATTISGARH' },
					{ value: 'DADRA AND NAGAR HAVELI', name: 'DADRA AND NAGAR HAVELI' },
					{ value: 'DAMAN AND DIU', name: 'DAMAN AND DIU' },
					{ value: 'DELHI', name: 'DELHI' },
					{ value: 'GOA', name: 'GOA' },
					{ value: 'GUJARAT', name: 'GUJARAT' },
					{ value: 'HARYANA', name: 'HARYANA' },
					{ value: 'HIMACHAL PRADESH', name: 'HIMACHAL PRADESH' },
					{ value: 'INTERNATIONAL', name: 'INTERNATIONAL' },
					{ value: 'JAMMU AND KASHMIR', name: 'JAMMU AND KASHMIR' },
					{ value: 'JHARKHAND', name: 'JHARKHAND' },
					{ value: 'KARNATAKA', name: 'KARNATAKA' },
					{ value: 'KERALA', name: 'KERALA' },
					{ value: 'LADAKH', name: 'LADAKH' },
					{ value: 'LAKSHADWEEP', name: 'LAKSHADWEEP' },
					{ value: 'MADHYA PRADESH', name: 'MADHYA PRADESH' },
					{ value: 'MAHARASHTRA', name: 'MAHARASHTRA' },
					{ value: 'MANIPUR', name: 'MANIPUR' },
					{ value: 'MEGHALAYA', name: 'MEGHALAYA' },
					{ value: 'MIZORAM', name: 'MIZORAM' },
					{ value: 'NAGALAND', name: 'NAGALAND' },
					{ value: 'ODISHA', name: 'ODISHA' },
					{ value: 'OTHER TERRITORY', name: 'OTHER TERRITORY' },
					{ value: 'PUDUCHERRY', name: 'PUDUCHERRY' },
					{ value: 'PUNJAB', name: 'PUNJAB' },
					{ value: 'RAJASTHAN', name: 'RAJASTHAN' },
					{ value: 'SIKKIM', name: 'SIKKIM' },
					{ value: 'TAMIL NADU', name: 'TAMIL NADU' },
					{ value: 'TELANGANA', name: 'TELANGANA' },
					{ value: 'TRIPURA', name: 'TRIPURA' },
					{ value: 'UTTAR PRADESH', name: 'UTTAR PRADESH' },
					{ value: 'UTTARAKHAND', name: 'UTTARAKHAND' },
					{ value: 'WEST BENGAL', name: 'WEST BENGAL' }
				],
				default: 'TAMIL NADU',
			},
		],
	},

	{
		displayName: 'Search Type',
		name: 'searchType',
		type: 'options',
		options: [
			{ name: 'Search by Name', value: 'name' },
			{ name: 'Search by Limit', value: 'limit' },
		],
		default: 'limit',
		displayOptions: {
			show: {
				operation: ['getAllContacts'],
			},
		},
	},

	{
		displayName: 'Search Term',
		name: 'searchTerm',
		type: 'string',
		default: '',
		placeholder: 'Enter name to search',
		displayOptions: {
			show: {
				operation: ['getAllContacts'],
				searchType: ['name'],
			},
		},
	},

	{
		displayName: 'Limit (Per Page)',
		name: 'perPage',
		type: 'number',
		default: 5,
		displayOptions: {
			show: {
				operation: ['getAllContacts'],
				searchType: ['name', 'limit'],
			},
		},
	},
];
