import { INodeProperties } from 'n8n-workflow';

export const createInvoiceOperation: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: {
      show: {
        resource: ['invoice'],
      },
    },
    options: [
      {
        name: 'Create Invoice',
        value: 'createInvoice',
        action: 'Create a new invoice',
      },
    ],
    default: 'createInvoice',
  },
  {
    displayName: 'Contact',
    name: 'contact',
    type: 'collection',
    placeholder: 'Add Contact Field',
    default: {},
    required: true,
    options: [
      {
        displayName: 'Business Country',
        name: 'business_country',
        type: 'options',
        options: [
          { name: 'AFGHANISTAN', value: 'AFGHANISTAN' },
          { name: 'ALBANIA', value: 'ALBANIA' },
          { name: 'ALGERIA', value: 'ALGERIA' },
          { name: 'AMERICAN SAMOA', value: 'AMERICAN SAMOA' },
          { name: 'ANDORRA', value: 'ANDORRA' },
          { name: 'ANGOLA', value: 'ANGOLA' },
          { name: 'ANGUILLA', value: 'ANGUILLA' },
          { name: 'ANTIGUA AND BARBUDA', value: 'ANTIGUA AND BARBUDA' },
          { name: 'ARGENTINA', value: 'ARGENTINA' },
          { name: 'ARMENIA', value: 'ARMENIA' },
          { name: 'ARUBA', value: 'ARUBA' },
          { name: 'AUSTRALIA', value: 'AUSTRALIA' },
          { name: 'AUSTRIA', value: 'AUSTRIA' },
          { name: 'AZERBAIJAN', value: 'AZERBAIJAN' },
          { name: 'BAHAMAS', value: 'BAHAMAS' },
          { name: 'BAHRAIN', value: 'BAHRAIN' },
          { name: 'BANGLADESH', value: 'BANGLADESH' },
          { name: 'BARBADOS', value: 'BARBADOS' },
          { name: 'BELARUS', value: 'BELARUS' },
          { name: 'BELGIUM', value: 'BELGIUM' },
          { name: 'BELIZE', value: 'BELIZE' },
          { name: 'BENIN', value: 'BENIN' },
          { name: 'BERMUDA', value: 'BERMUDA' },
          { name: 'BHUTAN', value: 'BHUTAN' },
          { name: 'BOLIVIA', value: 'BOLIVIA' },
          { name: 'BOSNIA AND HERZEGOVINA', value: 'BOSNIA AND HERZEGOVINA' },
          { name: 'BOTSWANA', value: 'BOTSWANA' },
          { name: 'BOUVET ISLAND', value: 'BOUVET ISLAND' },
          { name: 'BRAZIL', value: 'BRAZIL' },
          { name: 'BRITISH INDIAN OCEAN TERRITORY', value: 'BRITISH INDIAN OCEAN TERRITORY' },
          { name: 'BRUNEI DARUSSALAM', value: 'BRUNEI DARUSSALAM' },
          { name: 'BULGARIA', value: 'BULGARIA' },
          { name: 'BURKINA FASO', value: 'BURKINA FASO' },
          { name: 'BURUNDI', value: 'BURUNDI' },
          { name: 'CAMBODIA', value: 'CAMBODIA' },
          { name: 'CAMEROON', value: 'CAMEROON' },
          { name: 'CANADA', value: 'CANADA' },
          { name: 'CAPE VERDE', value: 'CAPE VERDE' },
          { name: 'CAYMAN ISLANDS', value: 'CAYMAN ISLANDS' },
          { name: 'CENTRAL AFRICAN REPUBLIC', value: 'CENTRAL AFRICAN REPUBLIC' },
          { name: 'CHAD', value: 'CHAD' },
          { name: 'CHILE', value: 'CHILE' },
          { name: 'CHINA', value: 'CHINA' },
          { name: 'CHRISTMAS ISLAND', value: 'CHRISTMAS ISLAND' },
          { name: 'COCOS (KEELING) ISLANDS', value: 'COCOS (KEELING) ISLANDS' },
          { name: 'COLOMBIA', value: 'COLOMBIA' },
          { name: 'COMOROS', value: 'COMOROS' },
          { name: 'CONGO', value: 'CONGO' },
          { name: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE', value: 'CONGO, THE DEMOCRATIC REPUBLIC OF THE' },
          { name: 'COOK ISLANDS', value: 'COOK ISLANDS' },
          { name: 'COSTA RICA', value: 'COSTA RICA' },
          { name: 'COTE D`IVOIRE', value: 'COTE D`IVOIRE' },
          { name: 'CROATIA', value: 'CROATIA' },
          { name: 'CUBA', value: 'CUBA' },
          { name: 'CYPRUS', value: 'CYPRUS' },
          { name: 'CZECH REPUBLIC', value: 'CZECH REPUBLIC' },
          { name: 'DENMARK', value: 'DENMARK' },
          { name: 'DJIBOUTI', value: 'DJIBOUTI' },
          { name: 'DOMINICA', value: 'DOMINICA' },
          { name: 'DOMINICAN REPUBLIC', value: 'DOMINICAN REPUBLIC' },
          { name: 'EAST TIMOR', value: 'EAST TIMOR' },
          { name: 'ECUADOR', value: 'ECUADOR' },
          { name: 'EGYPT', value: 'EGYPT' },
          { name: 'EL SALVADOR', value: 'EL SALVADOR' },
          { name: 'EQUATORIAL GUINEA', value: 'EQUATORIAL GUINEA' },
          { name: 'ERITREA', value: 'ERITREA' },
          { name: 'ESTONIA', value: 'ESTONIA' },
          { name: 'ETHIOPIA', value: 'ETHIOPIA' },
          { name: 'FALKLAND ISLANDS (MALVINAS)', value: 'FALKLAND ISLANDS (MALVINAS)' },
          { name: 'FAROE ISLANDS', value: 'FAROE ISLANDS' },
          { name: 'FIJI', value: 'FIJI' },
          { name: 'FINLAND', value: 'FINLAND' },
          { name: 'FRANCE', value: 'FRANCE' },
          { name: 'FRENCH GUIANA', value: 'FRENCH GUIANA' },
          { name: 'FRENCH POLYNESIA', value: 'FRENCH POLYNESIA' },
          { name: 'FRENCH SOUTHERN TERRITORIES', value: 'FRENCH SOUTHERN TERRITORIES' },
          { name: 'GABON', value: 'GABON' },
          { name: 'GAMBIA', value: 'GAMBIA' },
          { name: 'GEORGIA', value: 'GEORGIA' },
          { name: 'GERMANY', value: 'GERMANY' },
          { name: 'GHANA', value: 'GHANA' },
          { name: 'GIBRALTAR', value: 'GIBRALTAR' },
          { name: 'GREECE', value: 'GREECE' },
          { name: 'GREENLAND', value: 'GREENLAND' },
          { name: 'GRENADA', value: 'GRENADA' },
          { name: 'GUADELOUPE', value: 'GUADELOUPE' },
          { name: 'GUAM', value: 'GUAM' },
          { name: 'GUATEMALA', value: 'GUATEMALA' },
          { name: 'GUINEA', value: 'GUINEA' },
          { name: 'GUINEA-BISSAU', value: 'GUINEA-BISSAU' },
          { name: 'GUYANA', value: 'GUYANA' },
          { name: 'HAITI', value: 'HAITI' },
          { name: 'HEARD ISLAND AND MCDONALD ISLANDS', value: 'HEARD ISLAND AND MCDONALD ISLANDS' },
          { name: 'HOLY SEE (VATICAN CITY STATE)', value: 'HOLY SEE (VATICAN CITY STATE)' },
          { name: 'HONDURAS', value: 'HONDURAS' },
          { name: 'HONG KONG', value: 'HONG KONG' },
          { name: 'HUNGARY', value: 'HUNGARY' },
          { name: 'ICELAND', value: 'ICELAND' },
          { name: 'INDIA', value: 'INDIA' },
          { name: 'INDONESIA', value: 'INDONESIA' },
          { name: 'IRAN (ISLAMIC REPUBLIC OF)', value: 'IRAN (ISLAMIC REPUBLIC OF)' },
          { name: 'IRAQ', value: 'IRAQ' },
          { name: 'IRELAND', value: 'IRELAND' },
          { name: 'ISRAEL', value: 'ISRAEL' },
          { name: 'ITALY', value: 'ITALY' },
          { name: 'JAMAICA', value: 'JAMAICA' },
          { name: 'JAPAN', value: 'JAPAN' },
          { name: 'JORDAN', value: 'JORDAN' },
          { name: 'KAZAKHSTAN', value: 'KAZAKHSTAN' },
          { name: 'KENYA', value: 'KENYA' },
          { name: 'KIRIBATI', value: 'KIRIBATI' },
          { name: 'KOREA, DEMOCRATIC PEOPLE`S REPUBLIC OF', value: 'KOREA, DEMOCRATIC PEOPLE`S REPUBLIC OF' },
          { name: 'KOREA, REPUBLIC OF', value: 'KOREA, REPUBLIC OF' },
          { name: 'KUWAIT', value: 'KUWAIT' },
          { name: 'KYRGYZSTAN', value: 'KYRGYZSTAN' },
          { name: 'LAO PEOPLE`S DEMOCRATIC REPUBLIC', value: 'LAO PEOPLE`S DEMOCRATIC REPUBLIC' },
          { name: 'LATVIA', value: 'LATVIA' },
          { name: 'LEBANON', value: 'LEBANON' },
          { name: 'LESOTHO', value: 'LESOTHO' },
          { name: 'LIBERIA', value: 'LIBERIA' },
          { name: 'LIBYAN ARAB JAMAHIRIYA', value: 'LIBYAN ARAB JAMAHIRIYA' },
          { name: 'LIECHTENSTEIN', value: 'LIECHTENSTEIN' },
          { name: 'LITHUANIA', value: 'LITHUANIA' },
          { name: 'LUXEMBOURG', value: 'LUXEMBOURG' },
          { name: 'MACAO', value: 'MACAO' },
          { name: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF', value: 'MACEDONIA, THE FORMER YUGOSLAV REPUBLIC OF' },
          { name: 'MADAGASCAR', value: 'MADAGASCAR' },
          { name: 'MALAWI', value: 'MALAWI' },
          { name: 'MALAYSIA', value: 'MALAYSIA' },
          { name: 'MALDIVES', value: 'MALDIVES' },
          { name: 'MALI', value: 'MALI' },
          { name: 'MALTA', value: 'MALTA' },
          { name: 'MARSHALL ISLANDS', value: 'MARSHALL ISLANDS' },
          { name: 'MARTINIQUE', value: 'MARTINIQUE' },
          { name: 'MAURITANIA', value: 'MAURITANIA' },
          { name: 'MAURITIUS', value: 'MAURITIUS' },
          { name: 'MAYOTTE', value: 'MAYOTTE' },
          { name: 'MEXICO', value: 'MEXICO' },
          { name: 'MICRONESIA, FEDERATED STATES OF', value: 'MICRONESIA, FEDERATED STATES OF' },
          { name: 'MOLDOVA, REPUBLIC OF', value: 'MOLDOVA, REPUBLIC OF' },
          { name: 'MONACO', value: 'MONACO' },
          { name: 'MONGOLIA', value: 'MONGOLIA' },
          { name: 'MONTSERRAT', value: 'MONTSERRAT' },
          { name: 'MOROCCO', value: 'MOROCCO' },
          { name: 'MOZAMBIQUE', value: 'MOZAMBIQUE' },
          { name: 'MYANMAR', value: 'MYANMAR' },
          { name: 'NAMIBIA', value: 'NAMIBIA' },
          { name: 'NAURU', value: 'NAURU' },
          { name: 'NEPAL', value: 'NEPAL' },
          { name: 'NETHERLANDS', value: 'NETHERLANDS' },
          { name: 'NETHERLANDS ANTILLES', value: 'NETHERLANDS ANTILLES' },
          { name: 'NEW CALEDONIA', value: 'NEW CALEDONIA' },
          { name: 'NEW ZEALAND', value: 'NEW ZEALAND' },
          { name: 'NICARAGUA', value: 'NICARAGUA' },
          { name: 'NIGER', value: 'NIGER' },
          { name: 'NIGERIA', value: 'NIGERIA' },
          { name: 'NIUE', value: 'NIUE' },
          { name: 'NORFOLK ISLAND', value: 'NORFOLK ISLAND' },
          { name: 'NORTHERN MARIANA ISLANDS', value: 'NORTHERN MARIANA ISLANDS' },
          { name: 'NORWAY', value: 'NORWAY' },
          { name: 'OMAN', value: 'OMAN' },
          { name: 'PAKISTAN', value: 'PAKISTAN' },
          { name: 'PALAU', value: 'PALAU' },
          { name: 'PALESTINIAN TERRITORY, OCCUPIED', value: 'PALESTINIAN TERRITORY, OCCUPIED' },
          { name: 'PANAMA', value: 'PANAMA' },
          { name: 'PAPUA NEW GUINEA', value: 'PAPUA NEW GUINEA' },
          { name: 'PARAGUAY', value: 'PARAGUAY' },
          { name: 'PERU', value: 'PERU' },
          { name: 'PHILIPPINES', value: 'PHILIPPINES' },
          { name: 'PITCAIRN', value: 'PITCAIRN' },
          { name: 'POLAND', value: 'POLAND' },
          { name: 'PORTUGAL', value: 'PORTUGAL' },
          { name: 'PUERTO RICO', value: 'PUERTO RICO' },
          { name: 'QATAR', value: 'QATAR' },
          { name: 'REUNION', value: 'REUNION' },
          { name: 'ROMANIA', value: 'ROMANIA' },
          { name: 'RUSSIAN FEDERATION', value: 'RUSSIAN FEDERATION' },
          { name: 'RWANDA', value: 'RWANDA' },
          { name: 'SAINT HELENA', value: 'SAINT HELENA' },
          { name: 'SAINT KITTS AND NEVIS', value: 'SAINT KITTS AND NEVIS' },
          { name: 'SAINT LUCIA', value: 'SAINT LUCIA' },
          { name: 'SAINT PIERRE AND MIQUELON', value: 'SAINT PIERRE AND MIQUELON' },
          { name: 'SAINT VINCENT AND THE GRENADINES', value: 'SAINT VINCENT AND THE GRENADINES' },
          { name: 'SAMOA', value: 'SAMOA' },
          { name: 'SAN MARINO', value: 'SAN MARINO' },
          { name: 'SAO TOME AND PRINCIPE', value: 'SAO TOME AND PRINCIPE' },
          { name: 'SAUDI ARABIA', value: 'SAUDI ARABIA' },
          { name: 'SENEGAL', value: 'SENEGAL' },
          { name: 'SEYCHELLES', value: 'SEYCHELLES' },
          { name: 'SIERRA LEONE', value: 'SIERRA LEONE' },
          { name: 'SINGAPORE', value: 'SINGAPORE' },
          { name: 'SLOVAKIA', value: 'SLOVAKIA' },
          { name: 'SLOVENIA', value: 'SLOVENIA' },
          { name: 'SOLOMON ISLANDS', value: 'SOLOMON ISLANDS' },
          { name: 'SOMALIA', value: 'SOMALIA' },
          { name: 'SOUTH AFRICA', value: 'SOUTH AFRICA' },
          { name: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS', value: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' },
          { name: 'SPAIN', value: 'SPAIN' },
          { name: 'SRI LANKA', value: 'SRI LANKA' },
          { name: 'SUDAN', value: 'SUDAN' },
          { name: 'SURINAME', value: 'SURINAME' },
          { name: 'SVALBARD AND JAN MAYEN', value: 'SVALBARD AND JAN MAYEN' },
          { name: 'SWAZILAND', value: 'SWAZILAND' },
          { name: 'SWEDEN', value: 'SWEDEN' },
          { name: 'SWITZERLAND', value: 'SWITZERLAND' },
          { name: 'SYRIAN ARAB REPUBLIC', value: 'SYRIAN ARAB REPUBLIC' },
          { name: 'TAIWAN, PROVINCE OF CHINA', value: 'TAIWAN, PROVINCE OF CHINA' },
          { name: 'TAJIKISTAN', value: 'TAJIKISTAN' },
          { name: 'TANZANIA, UNITED REPUBLIC OF', value: 'TANZANIA, UNITED REPUBLIC OF' },
          { name: 'THAILAND', value: 'THAILAND' },
          { name: 'TIMOR-LESTE', value: 'TIMOR-LESTE' },
          { name: 'TOGO', value: 'TOGO' },
          { name: 'TOKELAU', value: 'TOKELAU' },
          { name: 'TONGA', value: 'TONGA' },
          { name: 'TRINIDAD AND TOBAGO', value: 'TRINIDAD AND TOBAGO' },
          { name: 'TUNISIA', value: 'TUNISIA' },
          { name: 'TURKEY', value: 'TURKEY' },
          { name: 'TURKMENISTAN', value: 'TURKMENISTAN' },
          { name: 'TURKS AND CAICOS ISLANDS', value: 'TURKS AND CAICOS ISLANDS' },
          { name: 'TUVALU', value: 'TUVALU' },
          { name: 'UGANDA', value: 'UGANDA' },
          { name: 'UKRAINE', value: 'UKRAINE' },
          { name: 'UNITED ARAB EMIRATES', value: 'UNITED ARAB EMIRATES' },
          { name: 'UNITED KINGDOM', value: 'UNITED KINGDOM' },
          { name: 'UNITED STATES', value: 'UNITED STATES' },
          { name: 'UNITED STATES MINOR OUTLYING ISLANDS', value: 'UNITED STATES MINOR OUTLYING ISLANDS' },
          { name: 'URUGUAY', value: 'URUGUAY' },
          { name: 'UZBEKISTAN', value: 'UZBEKISTAN' },
          { name: 'VANUATU', value: 'VANUATU' },
          { name: 'VENEZUELA', value: 'VENEZUELA' },
          { name: 'VIET NAM', value: 'VIET NAM' },
          { name: 'VIRGIN ISLANDS, BRITISH', value: 'VIRGIN ISLANDS, BRITISH' },
          { name: 'VIRGIN ISLANDS, U.S.', value: 'VIRGIN ISLANDS, U.S.' },
          { name: 'WALLIS AND FUTUNA', value: 'WALLIS AND FUTUNA' },
          { name: 'WESTERN SAHARA', value: 'WESTERN SAHARA' },
          { name: 'YEMEN', value: 'YEMEN' },
          { name: 'ZAMBIA', value: 'ZAMBIA' },
          { name: 'ZIMBABWE', value: 'ZIMBABWE' }
        ],
        default: 'INDIA',
      },
      { displayName: 'Business Name', name: 'business_name', type: 'string', default: '' },
      { displayName: 'Country Code', name: 'country_code', type: 'string', default: '' },
      { displayName: 'Email', name: 'email', type: 'string', default: '', placeholder: 'name@email.com' },
			{ displayName: 'GSTIN', name: 'gstin', type: 'string', default: '', placeholder: 'Enter GSTIN' },
      { displayName: 'ID', name: 'id', type: 'number', default: 0 },
      { displayName: 'Mobile', name: 'mobile', type: 'string', default: '' },
      { displayName: 'Name', name: 'name', type: 'string', default: '' },
      {
        displayName: 'Place of Supply',
        name: 'place_of_supply',
        type: 'options',
        options: [
          { value: 'ANDAMAN AND NICOBAR ISLANDS', name: 'ANDAMAN AND NICOBAR ISLANDS' },
          { value: 'ANDHRA PRADESH', name: 'ANDHRA PRADESH' },
          { value: 'ARUNACHAL PRADESH', name: 'ARUNACHAL PRADESH' },
          { value: 'ASSAM', name: 'ASSAM' },
          { value: 'BIHAR', name: 'BIHAR' },
          { value: 'CHANDIGARH', name: 'CHANDIGARH' },
          { value: 'CHHATTISGARH', name: 'CHHATTISGARH' },
          { value: 'DADRA AND NAGAR HAVELI', name: 'DADRA AND NAGAR HAVELI' },
          { value: 'DAMAN AND DIU', name: 'DAMAN AND DIU' },
          { value: 'DELHI', name: 'DELHI' },
          { value: 'GOA', name: 'GOA' },
          { value: 'GUJARAT', name: 'GUJARAT' },
          { value: 'HARYANA', name: 'HARYANA' },
          { value: 'HIMACHAL PRADESH', name: 'HIMACHAL PRADESH' },
          { value: 'INTERNATIONAL', name: 'INTERNATIONAL' },
          { value: 'JAMMU AND KASHMIR', name: 'JAMMU AND KASHMIR' },
          { value: 'JHARKHAND', name: 'JHARKHAND' },
          { value: 'KARNATAKA', name: 'KARNATAKA' },
          { value: 'KERALA', name: 'KERALA' },
          { value: 'LADAKH', name: 'LADAKH' },
          { value: 'LAKSHADWEEP', name: 'LAKSHADWEEP' },
          { value: 'MADHYA PRADESH', name: 'MADHYA PRADESH' },
          { value: 'MAHARASHTRA', name: 'MAHARASHTRA' },
          { value: 'MANIPUR', name: 'MANIPUR' },
          { value: 'MEGHALAYA', name: 'MEGHALAYA' },
          { value: 'MIZORAM', name: 'MIZORAM' },
          { value: 'NAGALAND', name: 'NAGALAND' },
          { value: 'ODISHA', name: 'ODISHA' },
          { value: 'OTHER TERRITORY', name: 'OTHER TERRITORY' },
          { value: 'PUDUCHERRY', name: 'PUDUCHERRY' },
          { value: 'PUNJAB', name: 'PUNJAB' },
          { value: 'RAJASTHAN', name: 'RAJASTHAN' },
          { value: 'SIKKIM', name: 'SIKKIM' },
          { value: 'TAMIL NADU', name: 'TAMIL NADU' },
          { value: 'TELANGANA', name: 'TELANGANA' },
          { value: 'TRIPURA', name: 'TRIPURA' },
          { value: 'UTTAR PRADESH', name: 'UTTAR PRADESH' },
          { value: 'UTTARAKHAND', name: 'UTTARAKHAND' },
          { value: 'WEST BENGAL', name: 'WEST BENGAL' }
        ],
        default: 'TAMIL NADU',
      },
    ],
    displayOptions: {
      show: {
        resource: ['invoice'],
        operation: ['createInvoice'],
      },
    },
  },
  {
    displayName: 'Items',
    name: 'items',
    type: 'fixedCollection',
    placeholder: 'Add Item',
    default: {},
    required: true,
    typeOptions: {
      multipleValues: true,
    },
    options: [
      {
        displayName: 'Item',
        name: 'item',
        values: [
          { displayName: 'Description', name: 'description', type: 'string', default: '' },
          { displayName: 'Discount', name: 'discount', type: 'number', default: 0 },
          {
            displayName: 'GST Rate',
            name: 'gst_rate',
            type: 'options',
            options: [
              { name: '0.1%', value: '0.1%' },
              { name: '0.25%', value: '0.25%' },
              { name: '0%', value: '0%' },
              { name: '1.5%', value: '1.5%' },
              { name: '1%', value: '1%' },
              { name: '12%', value: '12%' },
              { name: '18%', value: '18%' },
              { name: '28%', value: '28%' },
              { name: '3%', value: '3%' },
              { name: '5%', value: '5%' },
              { name: '7.5%', value: '7.5%' },
              { name: 'Exempted Supply', value: 'Exempted Supply' },
              { name: 'Nil-Rated', value: 'Nil-Rated' },
              { name: 'Non-GST Supply', value: 'Non-GST Supply' },
              { name: 'Zero-Rated', value: 'Zero-Rated' },
            ],
            default: '5%',
          },
          { displayName: 'Item ID', name: 'pid', type: 'number', default: 1 },
          { displayName: 'Item Name', name: 'item_name', type: 'string', default: '' },
          { displayName: 'Item Type', name: 'item_type', type: 'number', default: 0 },
          { displayName: 'Non Taxable Per Item', name: 'non_taxable_per_item', type: 'number', default: 0 },
          { displayName: 'Price Type', name: 'price_type', type: 'string', default: '' },
          { displayName: 'Quantity', name: 'quantity', type: 'number', default: 1 },
          { displayName: 'Rate', name: 'rate', type: 'number', default: 0 },
          { displayName: 'SAC/HSN Code', name: 'item_code', type: 'string', default: '' },
          { displayName: 'Taxable Per Item', name: 'taxable_per_item', type: 'number', default: 0 },
          { displayName: 'Units', name: 'units', type: 'string', default: '' },
          { displayName: 'Variant ID', name: 'variant_id', type: 'number', default: 1 },
        ],
      },
    ],
    displayOptions: {
      show: {
        resource: ['invoice'],
        operation: ['createInvoice'],
      },
    },
  },
  {
    displayName: 'Seller Branch ID',
    name: 'seller_branch_id',
    type: 'string',
    default: '',
    required: true,
    displayOptions: {
      show: {
        resource: ['invoice'],
        operation: ['createInvoice'],
      },
    },
  },
  {
    displayName: 'Additional Fields',
    name: 'additionalFields',
    type: 'collection',
    placeholder: 'Add Field',
    default: {},
    options: [
      {
        displayName: 'Bank ID', name: 'bank_id', type: 'string', default: '' },
      {
        displayName: 'Billing Address',
        name: 'billing_address',
        type: 'fixedCollection',
        typeOptions: { multipleValues: false },
        default: {},
        options: [
          {
            displayName: 'Billing',
            name: 'billing',
            values: [
              { displayName: 'Bill Addr1', name: 'bill_addr1', type: 'string', default: '' },
              { displayName: 'Bill Addr2', name: 'bill_addr2', type: 'string', default: '' },
              { displayName: 'Bill City', name: 'bill_city', type: 'string', default: '' },
              { displayName: 'Bill State', name: 'bill_state', type: 'string', default: '' },
              { displayName: 'Bill Country', name: 'bill_country', type: 'string', default: '' },
              { displayName: 'Bill Pincode', name: 'bill_pincode', type: 'string', default: '' },
            ],
          },
        ],
      },
      {
        displayName: 'Billings Currency', name: 'billings_currency', type: 'string', default: '' },
      {
        displayName: 'Currency Info',
        name: 'currency_info',
        type: 'collection',
        default: {},
        options: [
          { displayName: 'Name', name: 'name', type: 'string', default: '' },
          { displayName: 'Exchange Time', name: 'exchange_time', type: 'string', default: '' },
          { displayName: 'Exchange Rate', name: 'exchange_rate', type: 'string', default: '' },
        ],
      },
      {
        displayName: 'Invoice Date', name: 'invoice_date', type: 'string', default: '' },
      {
        displayName: 'Invoice Number', name: 'invoice_number', type: 'string', default: '' },
      {
        displayName: 'Notification', name: 'notification', type: 'string', default: '' },
      {
        displayName: 'Payment Link', name: 'payment_link', type: 'string', default: '' },
      {
        displayName: 'Shipping Address',
        name: 'shipping_address',
        type: 'fixedCollection',
        typeOptions: { multipleValues: false },
        default: {},
        options: [
          {
            displayName: 'Shipping',
            name: 'shipping',
            values: [
              { displayName: 'Ship Addr1', name: 'ship_addr1', type: 'string', default: '' },
              { displayName: 'Ship Addr2', name: 'ship_addr2', type: 'string', default: '' },
              { displayName: 'Ship City', name: 'ship_city', type: 'string', default: '' },
              { displayName: 'Ship State', name: 'ship_state', type: 'string', default: '' },
              { displayName: 'Ship Country', name: 'ship_country', type: 'string', default: '' },
              { displayName: 'Ship Pincode', name: 'ship_pincode', type: 'string', default: '' },
            ],
          },
        ],
      },
      {
        displayName: 'Terms Conditions', name: 'terms_conditions', type: 'string', default: 'This invoice is issued subject to the following terms and conditions. All goods and services provided herein are governed by the contractual agreement between the buyer and seller. The buyer agrees to inspect the goods upon delivery and must notify the seller of any discrepancies or defects within 7 days of receipt. No returns or exchanges will be entertained after this period unless otherwise agreed in writing. Payment must be made in full within the stipulated credit period as mentioned in the invoice; failure to comply may result in interest being charged on overdue accounts at the rate of 2% per month. Title to the goods shall remain with the seller until full payment has been received.' },
      {
        displayName: 'Validity Date', name: 'validity_date', type: 'string', default: '' },
    ],
    displayOptions: {
      show: {
        resource: ['invoice'],
        operation: ['createInvoice'],
      },
    },
  },
];
