import { INodeProperties } from 'n8n-workflow';

export const purchaseOperations: INodeProperties[] = [
	// Operation dropdown for Purchase resource
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['purchase'],
			},
		},
		options: [
			{
				name: 'Create Purchase Invoice',
				value: 'createPurchaseInvoice',
				action: 'Create a purchase invoice',
			},
			{
				name: 'Create Purchase Order',
				value: 'createPurchaseOrder',
				action: 'Create a purchase order',
			},
			{
				name: 'Create Voucher',
				value: 'createVoucher',
				action: 'Create a voucher',
			},
			{
				name: 'List Purchase Invoices',
				value: 'listPurchaseInvoices',
				action: 'List all purchase invoices',
			},
			{
				name: 'List Purchase Orders',
				value: 'listPurchaseOrders',
				action: 'List all purchase orders',
			},
			{
				name: 'List Vouchers',
				value: 'listVouchers',
				action: 'List all vouchers',
			},
			{
				name: 'View Purchase Invoice',
				value: 'viewPurchaseInvoice',
				action: 'View a purchase invoice',
			},
			{
				name: 'View Purchase Order',
				value: 'viewPurchaseOrder',
				action: 'View a purchase order',
			},
			{
				name: 'View Voucher',
				value: 'viewVoucher',
				action: 'View a voucher',
			},
		],
		default: 'createPurchaseInvoice',
	},
	{
		displayName: 'Voucher Type',
		name: 'voucher_type',
		type: 'options',
		options: [
			{ name: 'Payment Voucher', value: '2' },
			{ name: 'Expense Voucher', value: '1' },
			{ name: 'Salary Voucher', value: '3' },
		],
		default: '1',
		required: true,
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
			},
		},
	},
	{
		displayName: 'Branch ID',
		name: 'branch_id',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
			},
		},
		default: '',
	},
	{
		displayName: 'Payment Date',
		name: 'payment_date',
		type: 'dateTime',
		typeOptions: { dateOnly: true, showTime: false },
		default: '',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
			},
		},
	},
	{
		displayName: 'Currency', name: 'currency', type: 'options',
		options: [
			{ name: 'AED - UAE Dirham', value: 'AED' },
			{ name: 'AFN - Afghan Afghani', value: 'AFN' },
			{ name: 'ALL - Albanian Lek', value: 'ALL' },
			{ name: 'AMD - Armenian Dram', value: 'AMD' },
			{ name: 'ANG - Netherlands Antillean Guilder', value: 'ANG' },
			{ name: 'AOA - Angolan Kwanza', value: 'AOA' },
			{ name: 'ARS - Argentine Peso', value: 'ARS' },
			{ name: 'AUD - Australian Dollar', value: 'AUD' },
			{ name: 'AWG - Aruban Florin', value: 'AWG' },
			{ name: 'AZN - Azerbaijani Manat', value: 'AZN' },
			{ name: 'BAM - Bosnia and Herzegovina Convertible Mark', value: 'BAM' },
			{ name: 'BBD - Barbadian Dollar', value: 'BBD' },
			{ name: 'BDT - Bangladeshi Taka', value: 'BDT' },
			{ name: 'BGN - Bulgarian Lev', value: 'BGN' },
			{ name: 'BHD - Bahraini Dinar', value: 'BHD' },
			{ name: 'BIF - Burundian Franc', value: 'BIF' },
			{ name: 'BMD - Bermudian Dollar', value: 'BMD' },
			{ name: 'BND - Brunei Dollar', value: 'BND' },
			{ name: 'BOB - Bolivian Boliviano', value: 'BOB' },
			{ name: 'BRL - Brazilian Real', value: 'BRL' },
			{ name: 'BSD - Bahamian Dollar', value: 'BSD' },
			{ name: 'BTN - Bhutanese Ngultrum', value: 'BTN' },
			{ name: 'BWP - Botswana Pula', value: 'BWP' },
			{ name: 'BYN - Belarusian Ruble', value: 'BYN' },
			{ name: 'BZD - Belize Dollar', value: 'BZD' },
			{ name: 'CAD - Canadian Dollar', value: 'CAD' },
			{ name: 'CDF - Congolese Franc', value: 'CDF' },
			{ name: 'CHF - Swiss Franc', value: 'CHF' },
			{ name: 'CLF - Unidad De Fomento', value: 'CLF' },
			{ name: 'CLP - Chilean Peso', value: 'CLP' },
			{ name: 'CNY - Chinese Yuan', value: 'CNY' },
			{ name: 'COP - Colombian Peso', value: 'COP' },
			{ name: 'CRC - Costa Rican Colon', value: 'CRC' },
			{ name: 'CUC - Cuban Convertible Peso', value: 'CUC' },
			{ name: 'CUP - Cuban Peso', value: 'CUP' },
			{ name: 'CVE - Cape Verdean Escudo', value: 'CVE' },
			{ name: 'CZK - Czech Koruna', value: 'CZK' },
			{ name: 'DJF - Djiboutian Franc', value: 'DJF' },
			{ name: 'DKK - Danish Krone', value: 'DKK' },
			{ name: 'DOP - Dominican Peso', value: 'DOP' },
			{ name: 'DZD - Algerian Dinar', value: 'DZD' },
			{ name: 'EGP - Egyptian Pound', value: 'EGP' },
			{ name: 'ERN - Eritrean Nakfa', value: 'ERN' },
			{ name: 'ETB - Ethiopian Birr', value: 'ETB' },
			{ name: 'EUR - Euro', value: 'EUR' },
			{ name: 'FJD - Fijian Dollar', value: 'FJD' },
			{ name: 'FKP - Falkland Islands Pound', value: 'FKP' },
			{ name: 'GBP - British Pound', value: 'GBP' },
			{ name: 'GEL - Georgian Lari', value: 'GEL' },
			{ name: 'GHS - Ghanaian Cedi', value: 'GHS' },
			{ name: 'GIP - Gibraltar Pound', value: 'GIP' },
			{ name: 'GMD - Gambian Dalasi', value: 'GMD' },
			{ name: 'GNF - Guinean Franc', value: 'GNF' },
			{ name: 'GTQ - Guatemalan Quetzal', value: 'GTQ' },
			{ name: 'GYD - Guyanese Dollar', value: 'GYD' },
			{ name: 'HKD - Hong Kong Dollar', value: 'HKD' },
			{ name: 'HNL - Honduran Lempira', value: 'HNL' },
			{ name: 'HRK - Croatian Kuna', value: 'HRK' },
			{ name: 'HTG - Haitian Gourde', value: 'HTG' },
			{ name: 'HUF - Hungarian Forint', value: 'HUF' },
			{ name: 'IDR - Indonesian Rupiah', value: 'IDR' },
			{ name: 'ILS - Israeli New Shekel', value: 'ILS' },
			{ name: 'INR - Indian Rupee', value: 'INR' },
			{ name: 'IQD - Iraqi Dinar', value: 'IQD' },
			{ name: 'IRR - Iranian Rial', value: 'IRR' },
			{ name: 'ISK - Icelandic Króna', value: 'ISK' },
			{ name: 'JMD - Jamaican Dollar', value: 'JMD' },
			{ name: 'JOD - Jordanian Dinar', value: 'JOD' },
			{ name: 'JPY - Japanese Yen', value: 'JPY' },
			{ name: 'KES - Kenyan Shilling', value: 'KES' },
			{ name: 'KGS - Kyrgyzstani Som', value: 'KGS' },
			{ name: 'KHR - Cambodian Riel', value: 'KHR' },
			{ name: 'KMF - Comorian Franc', value: 'KMF' },
			{ name: 'KPW - North Korean Won', value: 'KPW' },
			{ name: 'KRW - South Korean Won', value: 'KRW' },
			{ name: 'KWD - Kuwaiti Dinar', value: 'KWD' },
			{ name: 'KYD - Cayman Islands Dollar', value: 'KYD' },
			{ name: 'KZT - Kazakhstani Tenge', value: 'KZT' },
			{ name: 'LAK - Lao Kip', value: 'LAK' },
			{ name: 'LBP - Lebanese Pound', value: 'LBP' },
			{ name: 'LKR - Sri Lankan Rupee', value: 'LKR' },
			{ name: 'LRD - Liberian Dollar', value: 'LRD' },
			{ name: 'LSL - Lesotho Loti', value: 'LSL' },
			{ name: 'LYD - Libyan Dinar', value: 'LYD' },
			{ name: 'MAD - Moroccan Dirham', value: 'MAD' },
			{ name: 'MDL - Moldovan Leu', value: 'MDL' },
			{ name: 'MGA - Malagasy Ariary', value: 'MGA' },
			{ name: 'MKD - Macedonian Denar', value: 'MKD' },
			{ name: 'MMK - Myanmar Kyat', value: 'MMK' },
			{ name: 'MNT - Mongolian Tugrik', value: 'MNT' },
			{ name: 'MOP - Macanese Pataca', value: 'MOP' },
			{ name: 'MRU - Mauritanian Ouguiya', value: 'MRU' },
			{ name: 'MUR - Mauritian Rupee', value: 'MUR' },
			{ name: 'MVR - Maldivian Rufiyaa', value: 'MVR' },
			{ name: 'MWK - Malawian Kwacha', value: 'MWK' },
			{ name: 'MXN - Mexican Peso', value: 'MXN' },
			{ name: 'MYR - Malaysian Ringgit', value: 'MYR' },
			{ name: 'MZN - Mozambican Metical', value: 'MZN' },
			{ name: 'NAD - Namibian Dollar', value: 'NAD' },
			{ name: 'NGN - Nigerian Naira', value: 'NGN' },
			{ name: 'NIO - Nicaraguan Cordoba', value: 'NIO' },
			{ name: 'NOK - Norwegian Krone', value: 'NOK' },
			{ name: 'NPR - Nepalese Rupee', value: 'NPR' },
			{ name: 'NZD - New Zealand Dollar', value: 'NZD' },
			{ name: 'OMR - Omani Rial', value: 'OMR' },
			{ name: 'PAB - Panamanian Balboa', value: 'PAB' },
			{ name: 'PEN - Peruvian Sol', value: 'PEN' },
			{ name: 'PGK - Papua New Guinean Kina', value: 'PGK' },
			{ name: 'PHP - Philippine Peso', value: 'PHP' },
			{ name: 'PKR - Pakistani Rupee', value: 'PKR' },
			{ name: 'PLN - Polish Zloty', value: 'PLN' },
			{ name: 'PYG - Paraguayan Guarani', value: 'PYG' },
			{ name: 'QAR - Qatari Riyal', value: 'QAR' },
			{ name: 'RON - Romanian Leu', value: 'RON' },
			{ name: 'RSD - Serbian Dinar', value: 'RSD' },
			{ name: 'RUB - Russian Ruble', value: 'RUB' },
			{ name: 'RWF - Rwandan Franc', value: 'RWF' },
			{ name: 'SAR - Saudi Riyal', value: 'SAR' },
			{ name: 'SBD - Solomon Islands Dollar', value: 'SBD' },
			{ name: 'SCR - Seychellois Rupee', value: 'SCR' },
			{ name: 'SDG - Sudanese Pound', value: 'SDG' },
			{ name: 'SEK - Swedish Krona', value: 'SEK' },
			{ name: 'SGD - Singapore Dollar', value: 'SGD' },
			{ name: 'SHP - Saint Helena Pound', value: 'SHP' },
			{ name: 'SLL - Sierra Leonean Leone', value: 'SLL' },
			{ name: 'SOS - Somali Shilling', value: 'SOS' },
			{ name: 'SRD - Surinamese Dollar', value: 'SRD' },
			{ name: 'SSP - South Sudanese Pound', value: 'SSP' },
			{ name: 'STN - São Tomé and Príncipe Dobra', value: 'STN' },
			{ name: 'SVC - Salvadoran Colón', value: 'SVC' },
			{ name: 'SYP - Syrian Pound', value: 'SYP' },
			{ name: 'SZL - Swazi Lilangeni', value: 'SZL' },
			{ name: 'THB - Thai Baht', value: 'THB' },
			{ name: 'TJS - Tajikistani Somoni', value: 'TJS' },
			{ name: 'TMT - Turkmenistani Manat', value: 'TMT' },
			{ name: 'TND - Tunisian Dinar', value: 'TND' },
			{ name: 'TOP - Tongan Paʻanga', value: 'TOP' },
			{ name: 'TRY - Turkish Lira', value: 'TRY' },
			{ name: 'TTD - Trinidad and Tobago Dollar', value: 'TTD' },
			{ name: 'TWD - Taiwan Dollar', value: 'TWD' },
			{ name: 'TZS - Tanzanian Shilling', value: 'TZS' },
			{ name: 'UAH - Ukrainian Hryvnia', value: 'UAH' },
			{ name: 'UGX - Ugandan Shilling', value: 'UGX' },
			{ name: 'USD - US Dollar', value: 'USD' },
			{ name: 'UYU - Uruguayan Peso', value: 'UYU' },
			{ name: 'UZS - Uzbekistani Som', value: 'UZS' },
			{ name: 'VES - Venezuelan Bolivar', value: 'VES' },
			{ name: 'VND - Vietnamese Dong', value: 'VND' },
			{ name: 'VUV - Vanuatu Vatu', value: 'VUV' },
			{ name: 'WST - Samoan Tala', value: 'WST' },
			{ name: 'XAF - CFA Franc BEAC', value: 'XAF' },
			{ name: 'XCD - East Caribbean Dollar', value: 'XCD' },
			{ name: 'XOF - CFA Franc BCEAO', value: 'XOF' },
			{ name: 'XPF - CFP Franc', value: 'XPF' },
			{ name: 'YER - Yemeni Rial', value: 'YER' },
			{ name: 'ZAR - South African Rand', value: 'ZAR' },
			{ name: 'ZMW - Zambian Kwacha', value: 'ZMW' },
			{ name: 'ZWL - Zimbabwean Dollar', value: 'ZWL' },
		],
		default: 'INR',
		required: true,
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
			},
		},
	},
	{
		displayName: 'Payment Method Name or ID',
		name: 'payment_mode',
		type: 'options',
		default: '',
		typeOptions: {
			loadOptionsMethod: 'getPaymentMethods',
		},
		required: true,
		placeholder: 'Select Payment Method',
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
			},
		},
	},
	{
		displayName: 'Expense Type',
		name: 'expense_type',
		type: 'options',
		options: [
			{ name: 'Single Account', value: 'single' },
			{ name: 'Multiple Accounts', value: 'multiple' },
		],
		default: 'single',
		required: true,
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				voucher_type: ['1'],
			},
		},
	},
	{
		displayName: 'Account Name or ID',
		name: 'expense_head',
		type: 'options',
		typeOptions: {
			loadOptionsMethod: 'getCoaAccounts',
		},
		default: '',
		placeholder: 'Select Account Type',
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				expense_type: ['single'],
			},
		},
	},
	{
		displayName: 'Amount',
		name: 'amount',
		type: 'number',
		default: 0,
		required: true,
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				expense_type: ['single'],
			},
		},
	},
	{
		displayName: 'Tax Rate',
		name: 'tax_rate',
		type: 'options',
		options: [
			{ name: '0.1%', value: '0.1' },
			{ name: '0.25%', value: '0.25' },
			{ name: '0%', value: '0' },
			{ name: '1.5%', value: '1.5' },
			{ name: '1%', value: '1' },
			{ name: '12%', value: '12' },
			{ name: '18%', value: '18' },
			{ name: '28%', value: '28' },
			{ name: '3%', value: '3' },
			{ name: '5%', value: '5' },
			{ name: '7.5%', value: '7.5' },
			{ name: 'Exempted Supply', value: 'Exempted Supply' },
			{ name: 'Nil-Rated', value: 'Nil-Rated' },
			{ name: 'Non-GST Supply', value: 'Non-GST Supply' },
			{ name: 'Zero-Rated', value: 'Zero-Rated' },
		],
		default: '5',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				expense_type: ['single'],
			},
		},
	},
	{
    displayName: 'Multiple Accounts',
    name: 'multiple_accounts',
    type: 'fixedCollection',
    placeholder: 'Add Accounts',
    default: {},
    required: true,
    typeOptions: {
      multipleValues: true,
    },
    options: [
      {
        displayName: 'Account',
        name: 'expense_head',
        values: [
          {
						displayName: 'Account Name or ID', name: 'expense_head', type: 'options', typeOptions: {
							loadOptionsMethod: 'getCoaAccounts',
						},
						default: '',
						placeholder: 'Select Account Type',
						description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>'
					},
					{
						displayName: 'Amount',
						name: 'amount',
						type: 'number',
						default: 0,
					},
					{
						displayName: 'Tax',
						name: 'tax',
						type: 'options',
						options: [
              { name: '0.1%', value: '0.1' },
              { name: '0.25%', value: '0.25' },
              { name: '0%', value: '0' },
              { name: '1.5%', value: '1.5' },
              { name: '1%', value: '1' },
              { name: '12%', value: '12' },
              { name: '18%', value: '18' },
              { name: '28%', value: '28' },
              { name: '3%', value: '3' },
              { name: '5%', value: '5' },
              { name: '7.5%', value: '7.5' },
              { name: 'Exempted Supply', value: 'Exempted Supply' },
              { name: 'Nil-Rated', value: 'Nil-Rated' },
              { name: 'Non-GST Supply', value: 'Non-GST Supply' },
              { name: 'Zero-Rated', value: 'Zero-Rated' },
            ],
            default: '5',
					}
        ],
      },
    ],
    displayOptions: {
      show: {
        resource: ['purchase'],
        operation: ['createVoucher'],
        expense_type: ['multiple'],
      },
    },
  },
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
			},
		},
		options: [

			{
				displayName: 'Contact ID',
				name: 'contact_id',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Payment Status',
				name: 'payment_status',
				type: 'options',
				options: [
					{ name: 'Paid', value: 1 },
					{ name: 'Unpaid', value: 0 },
				],
				default: 0,
			},

			{
				displayName: 'Reverse Charge',
				name: 'reverse_charge',
				type: 'options',
				options: [
					{ name: 'Yes', value: 1 },
					{ name: 'No', value: 0 },
				],
				default: 0,
			},
			{
				displayName: 'Claim ITC',
				name: 'tax_credit_type',
				type: 'options',
				options: [
					{ name: 'Yes', value: 1 },
					{ name: 'No', value: 0 },
				],
				default: 0,
			},
		],
	},
];
