import { INodeProperties } from 'n8n-workflow';

export const purchaseOperations: INodeProperties[] = [
	// Operation dropdown for Purchase resource
	{
		displayName: 'Operation',
		name: 'operation',
		type: 'options',
		noDataExpression: true,
		displayOptions: {
			show: {
				resource: ['purchase'],
			},
		},
		options: [
			{
				name: 'Create Purchase Invoice',
				value: 'createPurchaseInvoice',
				action: 'Create a purchase invoice',
			},
			// {
			// 	name: 'Create Purchase Order',
			// 	value: 'createPurchaseOrder',
			// 	action: 'Create a purchase order',
			// },
			{
				name: 'Create Voucher',
				value: 'createVoucher',
				action: 'Create a voucher',
			},
			{
				name: 'List Purchase Invoices',
				value: 'listPurchaseInvoices',
				action: 'List all purchase invoices',
			},
			// {
			// 	name: 'List Purchase Orders',
			// 	value: 'listPurchaseOrders',
			// 	action: 'List all purchase orders',
			// },
			{
				name: 'List Vouchers',
				value: 'listVouchers',
				action: 'List all vouchers',
			},
			{
				name: 'View Purchase Invoice',
				value: 'viewPurchaseInvoice',
				action: 'View a purchase invoice',
			},
			// {
			// 	name: 'View Purchase Order',
			// 	value: 'viewPurchaseOrder',
			// 	action: 'View a purchase order',
			// },
			{
				name: 'View Voucher',
				value: 'viewVoucher',
				action: 'View a voucher',
			},
		],
		default: 'createPurchaseInvoice',
	},

	//Create Operations

	// Purchase Invoice
	{
		displayName: 'Purchase Number',
		name: 'purchase_number',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
			},
		},
	},
	{
		displayName: 'Purchase Invoice Date',
		name: 'pur_inv_date',
		type: 'dateTime',
		required: true,
		typeOptions: { dateOnly: true, showTime: false },
		default: '',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
			},
		},
	},
	{
		displayName: 'Purchase Order ID',
		name: 'purchase_order_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
			},
		},
	},
	{
		displayName: 'Purchase Due Date',
		name: 'due_date',
		type: 'dateTime',
		required: true,
		typeOptions: { dateOnly: true, showTime: false },
		default: '',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
			},
		},
	},
	{
		displayName: 'Tax Type',
		name: 'tax_id1_type',
		type: 'options',
		required: true,
		options: [
			{ name: 'No GST', value: '0' },
			{ name: 'SGST/CGST', value: '1' },
			{ name: 'IGST', value: '2' },
		],
		default: '0',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
			},
		},
	},
	{
		displayName: 'Contact ID',
		name: 'contact_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
			},
		},
	},
  {
    displayName: 'Business Branch ID',
    name: 'business_branch_id',
    type: 'string',
    default: '',
    required: true,
    displayOptions: {
      show: {
        resource: ['purchase'],
        operation: ['createPurchaseInvoice'],
      },
    },
  },
	{
		displayName: 'Seller Tax ID',
		name: 'seller_tax_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
			},
		},
	},
	{
		displayName: 'Notes',
		name: 'notes',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
			},
		},
	},
	{
		displayName: 'Same Address for Billing and Shipping',
		name: 'same_address',
		type: 'boolean',
		default: true,
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
			},
		},
	},
	{
		displayName: 'Billing Address',
		name: 'billing_address',
		type: 'collection',
		typeOptions: { multipleValues: false },
		required: true,
		default: {},
		options: [
			{ displayName: 'Billing Address Line 1', name: 'bill_addr1', type: 'string', default: '' },
			{ displayName: 'Billing Address Line 2', name: 'bill_addr2', type: 'string', default: '' },
			{ displayName: 'Billing City', name: 'bill_city', type: 'string', default: '' },
			{ displayName: 'Billing Company Name', name: 'bill_company_name', type: 'string', default: '' },
			{ displayName: 'Billing Country', name: 'bill_country', type: 'string', default: '' },
			{ displayName: 'Billing Pincode', name: 'bill_pincode', type: 'string', default: '' },
			{ displayName: 'Billing State', name: 'bill_state', type: 'string', default: '' },
		],
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
			},
		},
	},
	{
		displayName: 'Shipping Address',
		name: 'shipping_address',
		type: 'collection',
		typeOptions: { multipleValues: false },
		required: true,
		default: {},
		options: [
			{ displayName: 'Shipping Address Line 1', name: 'ship_addr1', type: 'string', default: '' },
			{ displayName: 'Shipping Address Line 2', name: 'ship_addr2', type: 'string', default: '' },
			{ displayName: 'Shipping City', name: 'ship_city', type: 'string', default: '' },
			{ displayName: 'Shipping Company Name', name: 'ship_company_name', type: 'string', default: '' },
			{ displayName: 'Shipping Country', name: 'ship_country', type: 'string', default: '' },
			{ displayName: 'Shipping Pincode', name: 'ship_pincode', type: 'string', default: '' },
			{ displayName: 'Shipping State', name: 'ship_state', type: 'string', default: '' },
		],
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
				same_address: [false],
			},
		},
	},

	{
    displayName: 'Items',
    name: 'items',
    type: 'fixedCollection',
    placeholder: 'Add Item',
    default: {},
    required: true,
    typeOptions: {
      multipleValues: true,
    },
    options: [
      {
        displayName: 'Item',
        name: 'item',
        values: [
					{
						displayName: 'Cess Type',
						name: 'cess_type',
						type: 'options',
						options: [
							{ name: 'Percentage', value: 'percentage' },
							{ name: 'Flat Value', value: 'flat_value' },
						],
						default: 'percentage',
					},
					{
						displayName: 'Cess Value',
						name: 'cess_per',
						type: 'number',
						default: '',
						placeholder: 'Enter Cess Value',
						description: 'For percentage: Enter value between 1-100. For flat: Enter absolute value.',
					},
          { displayName: 'Description', name: 'item_description', type: 'string', default: '' },
          { displayName: 'Discount', name: 'item_discount', type: 'number', default: 0 },
					{
						displayName: 'Expense Name or ID',
						name: 'coa_id',
						type: 'options',
						typeOptions: {
							loadOptionsMethod: 'getCoaAccounts',
						},
						default: '',
						placeholder: 'Select Expense Type',
						description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
					},
          {
            displayName: 'GST Rate',
            name: 'gst_rate',
            type: 'options',
						required: true,
            options: [
              { name: '0.1%', value: '0.1' },
              { name: '0.25%', value: '0.25' },
              { name: '0%', value: '0' },
              { name: '1.5%', value: '1.5' },
              { name: '1%', value: '1' },
              { name: '12%', value: '12' },
              { name: '18%', value: '18' },
              { name: '28%', value: '28' },
              { name: '3%', value: '3' },
              { name: '5%', value: '5' },
              { name: '7.5%', value: '7.5' },
              { name: 'Exempted Supply', value: 'Exempted Supply' },
              { name: 'Nil-Rated', value: 'Nil-Rated' },
              { name: 'Non-GST Supply', value: 'Non-GST Supply' },
              { name: 'Zero-Rated', value: 'Zero-Rated' },
            ],
            default: '5',
          },
          { displayName: 'HSN/SAC Code', name: 'item_code', type: 'string', default: '' },
          { displayName: 'Item ID', name: 'pid', type: 'string', default: '', required: true },
          { displayName: 'Item Name', name: 'item_name', type: 'string', default: '', required: true },
          { displayName: 'Item Type', name: 'item_type', required: true, type: 'options', options: [
            { name: 'Goods', value: '1' },
            { name: 'Service', value: '2' },
          ], default: '1' },
          { displayName: 'Non Taxable Amount', name: 'non_taxable_amount', type: 'number', default: 0 },
          { displayName: 'Price Type', name: 'price_type', required: true, type: 'options', options: [
            { name: 'Inclusive of GST', value: 0 },
            { name: 'Exclusive of GST', value: 1 },
          ], default: 0 },
          { displayName: 'Quantity', name: 'quantity', type: 'number', default: 1, required: true },
          { displayName: 'Rate', name: 'rate', type: 'number', default: 0, required: true },
					{ displayName: 'SKU', name: 'sku', type: 'string', default: '' },
          { displayName: 'Taxable Amount', name: 'taxable_amount', type: 'number', default: 0 },
          { displayName: 'Variant ID', name: 'vid', type: 'string', default: '', required: true },
        ],
      },
    ],
    displayOptions: {
      show: {
        resource: ['purchase'],
        operation: ['createPurchaseInvoice'],
      },
    },
  },

	// Additional Fields for Purchase Invoice
	{
		displayName: 'Additional Fields',
		name: 'additional_fields',
		type: 'collection',
		typeOptions: { multipleValues: false },
		default: {},
		options: [
			{
				displayName: 'Bill No',
				name: 'bill_number',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Claim ITC',
				name: 'tax_credit_type',
				type: 'options',
				options: [
					{ name: 'Yes', value: 1 },
					{ name: 'No', value: 0 },
				],
				default: 0,
			},
			{
				displayName: 'Currency Info',
				name: 'currency_info',
				type: 'collection',
				default: {},
				options: [
					{displayName: 'Converted Amount', name: 'converted_amount', type: 'number', default: 0},
					{displayName: 'Currency Default Rate', name: 'currency_default_rate', type: 'number', default: 0},
					{displayName: 'Currency Rate', name: 'currency_rate', type: 'number', default: 0},
					{ displayName: 'From Currency', name: 'from', type: 'options',
						options: [
							{ name: 'AED - UAE Dirham', value: 'AED' },
							{ name: 'AFN - Afghan Afghani', value: 'AFN' },
							{ name: 'ALL - Albanian Lek', value: 'ALL' },
							{ name: 'AMD - Armenian Dram', value: 'AMD' },
							{ name: 'ANG - Netherlands Antillean Guilder', value: 'ANG' },
							{ name: 'AOA - Angolan Kwanza', value: 'AOA' },
							{ name: 'ARS - Argentine Peso', value: 'ARS' },
							{ name: 'AUD - Australian Dollar', value: 'AUD' },
							{ name: 'AWG - Aruban Florin', value: 'AWG' },
							{ name: 'AZN - Azerbaijani Manat', value: 'AZN' },
							{ name: 'BAM - Bosnia and Herzegovina Convertible Mark', value: 'BAM' },
							{ name: 'BBD - Barbadian Dollar', value: 'BBD' },
							{ name: 'BDT - Bangladeshi Taka', value: 'BDT' },
							{ name: 'BGN - Bulgarian Lev', value: 'BGN' },
							{ name: 'BHD - Bahraini Dinar', value: 'BHD' },
							{ name: 'BIF - Burundian Franc', value: 'BIF' },
							{ name: 'BMD - Bermudian Dollar', value: 'BMD' },
							{ name: 'BND - Brunei Dollar', value: 'BND' },
							{ name: 'BOB - Bolivian Boliviano', value: 'BOB' },
							{ name: 'BRL - Brazilian Real', value: 'BRL' },
							{ name: 'BSD - Bahamian Dollar', value: 'BSD' },
							{ name: 'BTN - Bhutanese Ngultrum', value: 'BTN' },
							{ name: 'BWP - Botswana Pula', value: 'BWP' },
							{ name: 'BYN - Belarusian Ruble', value: 'BYN' },
							{ name: 'BZD - Belize Dollar', value: 'BZD' },
							{ name: 'CAD - Canadian Dollar', value: 'CAD' },
							{ name: 'CDF - Congolese Franc', value: 'CDF' },
							{ name: 'CHF - Swiss Franc', value: 'CHF' },
							{ name: 'CLF - Unidad De Fomento', value: 'CLF' },
							{ name: 'CLP - Chilean Peso', value: 'CLP' },
							{ name: 'CNY - Chinese Yuan', value: 'CNY' },
							{ name: 'COP - Colombian Peso', value: 'COP' },
							{ name: 'CRC - Costa Rican Colon', value: 'CRC' },
							{ name: 'CUC - Cuban Convertible Peso', value: 'CUC' },
							{ name: 'CUP - Cuban Peso', value: 'CUP' },
							{ name: 'CVE - Cape Verdean Escudo', value: 'CVE' },
							{ name: 'CZK - Czech Koruna', value: 'CZK' },
							{ name: 'DJF - Djiboutian Franc', value: 'DJF' },
							{ name: 'DKK - Danish Krone', value: 'DKK' },
							{ name: 'DOP - Dominican Peso', value: 'DOP' },
							{ name: 'DZD - Algerian Dinar', value: 'DZD' },
							{ name: 'EGP - Egyptian Pound', value: 'EGP' },
							{ name: 'ERN - Eritrean Nakfa', value: 'ERN' },
							{ name: 'ETB - Ethiopian Birr', value: 'ETB' },
							{ name: 'EUR - Euro', value: 'EUR' },
							{ name: 'FJD - Fijian Dollar', value: 'FJD' },
							{ name: 'FKP - Falkland Islands Pound', value: 'FKP' },
							{ name: 'GBP - British Pound', value: 'GBP' },
							{ name: 'GEL - Georgian Lari', value: 'GEL' },
							{ name: 'GHS - Ghanaian Cedi', value: 'GHS' },
							{ name: 'GIP - Gibraltar Pound', value: 'GIP' },
							{ name: 'GMD - Gambian Dalasi', value: 'GMD' },
							{ name: 'GNF - Guinean Franc', value: 'GNF' },
							{ name: 'GTQ - Guatemalan Quetzal', value: 'GTQ' },
							{ name: 'GYD - Guyanese Dollar', value: 'GYD' },
							{ name: 'HKD - Hong Kong Dollar', value: 'HKD' },
							{ name: 'HNL - Honduran Lempira', value: 'HNL' },
							{ name: 'HRK - Croatian Kuna', value: 'HRK' },
							{ name: 'HTG - Haitian Gourde', value: 'HTG' },
							{ name: 'HUF - Hungarian Forint', value: 'HUF' },
							{ name: 'IDR - Indonesian Rupiah', value: 'IDR' },
							{ name: 'ILS - Israeli New Shekel', value: 'ILS' },
							{ name: 'INR - Indian Rupee', value: 'INR' },
							{ name: 'IQD - Iraqi Dinar', value: 'IQD' },
							{ name: 'IRR - Iranian Rial', value: 'IRR' },
							{ name: 'ISK - Icelandic Króna', value: 'ISK' },
							{ name: 'JMD - Jamaican Dollar', value: 'JMD' },
							{ name: 'JOD - Jordanian Dinar', value: 'JOD' },
							{ name: 'JPY - Japanese Yen', value: 'JPY' },
							{ name: 'KES - Kenyan Shilling', value: 'KES' },
							{ name: 'KGS - Kyrgyzstani Som', value: 'KGS' },
							{ name: 'KHR - Cambodian Riel', value: 'KHR' },
							{ name: 'KMF - Comorian Franc', value: 'KMF' },
							{ name: 'KPW - North Korean Won', value: 'KPW' },
							{ name: 'KRW - South Korean Won', value: 'KRW' },
							{ name: 'KWD - Kuwaiti Dinar', value: 'KWD' },
							{ name: 'KYD - Cayman Islands Dollar', value: 'KYD' },
							{ name: 'KZT - Kazakhstani Tenge', value: 'KZT' },
							{ name: 'LAK - Lao Kip', value: 'LAK' },
							{ name: 'LBP - Lebanese Pound', value: 'LBP' },
							{ name: 'LKR - Sri Lankan Rupee', value: 'LKR' },
							{ name: 'LRD - Liberian Dollar', value: 'LRD' },
							{ name: 'LSL - Lesotho Loti', value: 'LSL' },
							{ name: 'LYD - Libyan Dinar', value: 'LYD' },
							{ name: 'MAD - Moroccan Dirham', value: 'MAD' },
							{ name: 'MDL - Moldovan Leu', value: 'MDL' },
							{ name: 'MGA - Malagasy Ariary', value: 'MGA' },
							{ name: 'MKD - Macedonian Denar', value: 'MKD' },
							{ name: 'MMK - Myanmar Kyat', value: 'MMK' },
							{ name: 'MNT - Mongolian Tugrik', value: 'MNT' },
							{ name: 'MOP - Macanese Pataca', value: 'MOP' },
							{ name: 'MRU - Mauritanian Ouguiya', value: 'MRU' },
							{ name: 'MUR - Mauritian Rupee', value: 'MUR' },
							{ name: 'MVR - Maldivian Rufiyaa', value: 'MVR' },
							{ name: 'MWK - Malawian Kwacha', value: 'MWK' },
							{ name: 'MXN - Mexican Peso', value: 'MXN' },
							{ name: 'MYR - Malaysian Ringgit', value: 'MYR' },
							{ name: 'MZN - Mozambican Metical', value: 'MZN' },
							{ name: 'NAD - Namibian Dollar', value: 'NAD' },
							{ name: 'NGN - Nigerian Naira', value: 'NGN' },
							{ name: 'NIO - Nicaraguan Cordoba', value: 'NIO' },
							{ name: 'NOK - Norwegian Krone', value: 'NOK' },
							{ name: 'NPR - Nepalese Rupee', value: 'NPR' },
							{ name: 'NZD - New Zealand Dollar', value: 'NZD' },
							{ name: 'OMR - Omani Rial', value: 'OMR' },
							{ name: 'PAB - Panamanian Balboa', value: 'PAB' },
							{ name: 'PEN - Peruvian Sol', value: 'PEN' },
							{ name: 'PGK - Papua New Guinean Kina', value: 'PGK' },
							{ name: 'PHP - Philippine Peso', value: 'PHP' },
							{ name: 'PKR - Pakistani Rupee', value: 'PKR' },
							{ name: 'PLN - Polish Zloty', value: 'PLN' },
							{ name: 'PYG - Paraguayan Guarani', value: 'PYG' },
							{ name: 'QAR - Qatari Riyal', value: 'QAR' },
							{ name: 'RON - Romanian Leu', value: 'RON' },
							{ name: 'RSD - Serbian Dinar', value: 'RSD' },
							{ name: 'RUB - Russian Ruble', value: 'RUB' },
							{ name: 'RWF - Rwandan Franc', value: 'RWF' },
							{ name: 'SAR - Saudi Riyal', value: 'SAR' },
							{ name: 'SBD - Solomon Islands Dollar', value: 'SBD' },
							{ name: 'SCR - Seychellois Rupee', value: 'SCR' },
							{ name: 'SDG - Sudanese Pound', value: 'SDG' },
							{ name: 'SEK - Swedish Krona', value: 'SEK' },
							{ name: 'SGD - Singapore Dollar', value: 'SGD' },
							{ name: 'SHP - Saint Helena Pound', value: 'SHP' },
							{ name: 'SLL - Sierra Leonean Leone', value: 'SLL' },
							{ name: 'SOS - Somali Shilling', value: 'SOS' },
							{ name: 'SRD - Surinamese Dollar', value: 'SRD' },
							{ name: 'SSP - South Sudanese Pound', value: 'SSP' },
							{ name: 'STN - São Tomé and Príncipe Dobra', value: 'STN' },
							{ name: 'SVC - Salvadoran Colón', value: 'SVC' },
							{ name: 'SYP - Syrian Pound', value: 'SYP' },
							{ name: 'SZL - Swazi Lilangeni', value: 'SZL' },
							{ name: 'THB - Thai Baht', value: 'THB' },
							{ name: 'TJS - Tajikistani Somoni', value: 'TJS' },
							{ name: 'TMT - Turkmenistani Manat', value: 'TMT' },
							{ name: 'TND - Tunisian Dinar', value: 'TND' },
							{ name: 'TOP - Tongan Paʻanga', value: 'TOP' },
							{ name: 'TRY - Turkish Lira', value: 'TRY' },
							{ name: 'TTD - Trinidad and Tobago Dollar', value: 'TTD' },
							{ name: 'TWD - Taiwan Dollar', value: 'TWD' },
							{ name: 'TZS - Tanzanian Shilling', value: 'TZS' },
							{ name: 'UAH - Ukrainian Hryvnia', value: 'UAH' },
							{ name: 'UGX - Ugandan Shilling', value: 'UGX' },
							{ name: 'USD - US Dollar', value: 'USD' },
							{ name: 'UYU - Uruguayan Peso', value: 'UYU' },
							{ name: 'UZS - Uzbekistani Som', value: 'UZS' },
							{ name: 'VES - Venezuelan Bolivar', value: 'VES' },
							{ name: 'VND - Vietnamese Dong', value: 'VND' },
							{ name: 'VUV - Vanuatu Vatu', value: 'VUV' },
							{ name: 'WST - Samoan Tala', value: 'WST' },
							{ name: 'XAF - CFA Franc BEAC', value: 'XAF' },
							{ name: 'XCD - East Caribbean Dollar', value: 'XCD' },
							{ name: 'XOF - CFA Franc BCEAO', value: 'XOF' },
							{ name: 'XPF - CFP Franc', value: 'XPF' },
							{ name: 'YER - Yemeni Rial', value: 'YER' },
							{ name: 'ZAR - South African Rand', value: 'ZAR' },
							{ name: 'ZMW - Zambian Kwacha', value: 'ZMW' },
							{ name: 'ZWL - Zimbabwean Dollar', value: 'ZWL' },
						],
						default: 'INR'
					},
					{ displayName: 'To Currency', name: 'to', type: 'options',
						options: [
							{ name: 'AED - UAE Dirham', value: 'AED' },
							{ name: 'AFN - Afghan Afghani', value: 'AFN' },
							{ name: 'ALL - Albanian Lek', value: 'ALL' },
							{ name: 'AMD - Armenian Dram', value: 'AMD' },
							{ name: 'ANG - Netherlands Antillean Guilder', value: 'ANG' },
							{ name: 'AOA - Angolan Kwanza', value: 'AOA' },
							{ name: 'ARS - Argentine Peso', value: 'ARS' },
							{ name: 'AUD - Australian Dollar', value: 'AUD' },
							{ name: 'AWG - Aruban Florin', value: 'AWG' },
							{ name: 'AZN - Azerbaijani Manat', value: 'AZN' },
							{ name: 'BAM - Bosnia and Herzegovina Convertible Mark', value: 'BAM' },
							{ name: 'BBD - Barbadian Dollar', value: 'BBD' },
							{ name: 'BDT - Bangladeshi Taka', value: 'BDT' },
							{ name: 'BGN - Bulgarian Lev', value: 'BGN' },
							{ name: 'BHD - Bahraini Dinar', value: 'BHD' },
							{ name: 'BIF - Burundian Franc', value: 'BIF' },
							{ name: 'BMD - Bermudian Dollar', value: 'BMD' },
							{ name: 'BND - Brunei Dollar', value: 'BND' },
							{ name: 'BOB - Bolivian Boliviano', value: 'BOB' },
							{ name: 'BRL - Brazilian Real', value: 'BRL' },
							{ name: 'BSD - Bahamian Dollar', value: 'BSD' },
							{ name: 'BTN - Bhutanese Ngultrum', value: 'BTN' },
							{ name: 'BWP - Botswana Pula', value: 'BWP' },
							{ name: 'BYN - Belarusian Ruble', value: 'BYN' },
							{ name: 'BZD - Belize Dollar', value: 'BZD' },
							{ name: 'CAD - Canadian Dollar', value: 'CAD' },
							{ name: 'CDF - Congolese Franc', value: 'CDF' },
							{ name: 'CHF - Swiss Franc', value: 'CHF' },
							{ name: 'CLF - Unidad De Fomento', value: 'CLF' },
							{ name: 'CLP - Chilean Peso', value: 'CLP' },
							{ name: 'CNY - Chinese Yuan', value: 'CNY' },
							{ name: 'COP - Colombian Peso', value: 'COP' },
							{ name: 'CRC - Costa Rican Colon', value: 'CRC' },
							{ name: 'CUC - Cuban Convertible Peso', value: 'CUC' },
							{ name: 'CUP - Cuban Peso', value: 'CUP' },
							{ name: 'CVE - Cape Verdean Escudo', value: 'CVE' },
							{ name: 'CZK - Czech Koruna', value: 'CZK' },
							{ name: 'DJF - Djiboutian Franc', value: 'DJF' },
							{ name: 'DKK - Danish Krone', value: 'DKK' },
							{ name: 'DOP - Dominican Peso', value: 'DOP' },
							{ name: 'DZD - Algerian Dinar', value: 'DZD' },
							{ name: 'EGP - Egyptian Pound', value: 'EGP' },
							{ name: 'ERN - Eritrean Nakfa', value: 'ERN' },
							{ name: 'ETB - Ethiopian Birr', value: 'ETB' },
							{ name: 'EUR - Euro', value: 'EUR' },
							{ name: 'FJD - Fijian Dollar', value: 'FJD' },
							{ name: 'FKP - Falkland Islands Pound', value: 'FKP' },
							{ name: 'GBP - British Pound', value: 'GBP' },
							{ name: 'GEL - Georgian Lari', value: 'GEL' },
							{ name: 'GHS - Ghanaian Cedi', value: 'GHS' },
							{ name: 'GIP - Gibraltar Pound', value: 'GIP' },
							{ name: 'GMD - Gambian Dalasi', value: 'GMD' },
							{ name: 'GNF - Guinean Franc', value: 'GNF' },
							{ name: 'GTQ - Guatemalan Quetzal', value: 'GTQ' },
							{ name: 'GYD - Guyanese Dollar', value: 'GYD' },
							{ name: 'HKD - Hong Kong Dollar', value: 'HKD' },
							{ name: 'HNL - Honduran Lempira', value: 'HNL' },
							{ name: 'HRK - Croatian Kuna', value: 'HRK' },
							{ name: 'HTG - Haitian Gourde', value: 'HTG' },
							{ name: 'HUF - Hungarian Forint', value: 'HUF' },
							{ name: 'IDR - Indonesian Rupiah', value: 'IDR' },
							{ name: 'ILS - Israeli New Shekel', value: 'ILS' },
							{ name: 'INR - Indian Rupee', value: 'INR' },
							{ name: 'IQD - Iraqi Dinar', value: 'IQD' },
							{ name: 'IRR - Iranian Rial', value: 'IRR' },
							{ name: 'ISK - Icelandic Króna', value: 'ISK' },
							{ name: 'JMD - Jamaican Dollar', value: 'JMD' },
							{ name: 'JOD - Jordanian Dinar', value: 'JOD' },
							{ name: 'JPY - Japanese Yen', value: 'JPY' },
							{ name: 'KES - Kenyan Shilling', value: 'KES' },
							{ name: 'KGS - Kyrgyzstani Som', value: 'KGS' },
							{ name: 'KHR - Cambodian Riel', value: 'KHR' },
							{ name: 'KMF - Comorian Franc', value: 'KMF' },
							{ name: 'KPW - North Korean Won', value: 'KPW' },
							{ name: 'KRW - South Korean Won', value: 'KRW' },
							{ name: 'KWD - Kuwaiti Dinar', value: 'KWD' },
							{ name: 'KYD - Cayman Islands Dollar', value: 'KYD' },
							{ name: 'KZT - Kazakhstani Tenge', value: 'KZT' },
							{ name: 'LAK - Lao Kip', value: 'LAK' },
							{ name: 'LBP - Lebanese Pound', value: 'LBP' },
							{ name: 'LKR - Sri Lankan Rupee', value: 'LKR' },
							{ name: 'LRD - Liberian Dollar', value: 'LRD' },
							{ name: 'LSL - Lesotho Loti', value: 'LSL' },
							{ name: 'LYD - Libyan Dinar', value: 'LYD' },
							{ name: 'MAD - Moroccan Dirham', value: 'MAD' },
							{ name: 'MDL - Moldovan Leu', value: 'MDL' },
							{ name: 'MGA - Malagasy Ariary', value: 'MGA' },
							{ name: 'MKD - Macedonian Denar', value: 'MKD' },
							{ name: 'MMK - Myanmar Kyat', value: 'MMK' },
							{ name: 'MNT - Mongolian Tugrik', value: 'MNT' },
							{ name: 'MOP - Macanese Pataca', value: 'MOP' },
							{ name: 'MRU - Mauritanian Ouguiya', value: 'MRU' },
							{ name: 'MUR - Mauritian Rupee', value: 'MUR' },
							{ name: 'MVR - Maldivian Rufiyaa', value: 'MVR' },
							{ name: 'MWK - Malawian Kwacha', value: 'MWK' },
							{ name: 'MXN - Mexican Peso', value: 'MXN' },
							{ name: 'MYR - Malaysian Ringgit', value: 'MYR' },
							{ name: 'MZN - Mozambican Metical', value: 'MZN' },
							{ name: 'NAD - Namibian Dollar', value: 'NAD' },
							{ name: 'NGN - Nigerian Naira', value: 'NGN' },
							{ name: 'NIO - Nicaraguan Cordoba', value: 'NIO' },
							{ name: 'NOK - Norwegian Krone', value: 'NOK' },
							{ name: 'NPR - Nepalese Rupee', value: 'NPR' },
							{ name: 'NZD - New Zealand Dollar', value: 'NZD' },
							{ name: 'OMR - Omani Rial', value: 'OMR' },
							{ name: 'PAB - Panamanian Balboa', value: 'PAB' },
							{ name: 'PEN - Peruvian Sol', value: 'PEN' },
							{ name: 'PGK - Papua New Guinean Kina', value: 'PGK' },
							{ name: 'PHP - Philippine Peso', value: 'PHP' },
							{ name: 'PKR - Pakistani Rupee', value: 'PKR' },
							{ name: 'PLN - Polish Zloty', value: 'PLN' },
							{ name: 'PYG - Paraguayan Guarani', value: 'PYG' },
							{ name: 'QAR - Qatari Riyal', value: 'QAR' },
							{ name: 'RON - Romanian Leu', value: 'RON' },
							{ name: 'RSD - Serbian Dinar', value: 'RSD' },
							{ name: 'RUB - Russian Ruble', value: 'RUB' },
							{ name: 'RWF - Rwandan Franc', value: 'RWF' },
							{ name: 'SAR - Saudi Riyal', value: 'SAR' },
							{ name: 'SBD - Solomon Islands Dollar', value: 'SBD' },
							{ name: 'SCR - Seychellois Rupee', value: 'SCR' },
							{ name: 'SDG - Sudanese Pound', value: 'SDG' },
							{ name: 'SEK - Swedish Krona', value: 'SEK' },
							{ name: 'SGD - Singapore Dollar', value: 'SGD' },
							{ name: 'SHP - Saint Helena Pound', value: 'SHP' },
							{ name: 'SLL - Sierra Leonean Leone', value: 'SLL' },
							{ name: 'SOS - Somali Shilling', value: 'SOS' },
							{ name: 'SRD - Surinamese Dollar', value: 'SRD' },
							{ name: 'SSP - South Sudanese Pound', value: 'SSP' },
							{ name: 'STN - São Tomé and Príncipe Dobra', value: 'STN' },
							{ name: 'SVC - Salvadoran Colón', value: 'SVC' },
							{ name: 'SYP - Syrian Pound', value: 'SYP' },
							{ name: 'SZL - Swazi Lilangeni', value: 'SZL' },
							{ name: 'THB - Thai Baht', value: 'THB' },
							{ name: 'TJS - Tajikistani Somoni', value: 'TJS' },
							{ name: 'TMT - Turkmenistani Manat', value: 'TMT' },
							{ name: 'TND - Tunisian Dinar', value: 'TND' },
							{ name: 'TOP - Tongan Paʻanga', value: 'TOP' },
							{ name: 'TRY - Turkish Lira', value: 'TRY' },
							{ name: 'TTD - Trinidad and Tobago Dollar', value: 'TTD' },
							{ name: 'TWD - Taiwan Dollar', value: 'TWD' },
							{ name: 'TZS - Tanzanian Shilling', value: 'TZS' },
							{ name: 'UAH - Ukrainian Hryvnia', value: 'UAH' },
							{ name: 'UGX - Ugandan Shilling', value: 'UGX' },
							{ name: 'USD - US Dollar', value: 'USD' },
							{ name: 'UYU - Uruguayan Peso', value: 'UYU' },
							{ name: 'UZS - Uzbekistani Som', value: 'UZS' },
							{ name: 'VES - Venezuelan Bolivar', value: 'VES' },
							{ name: 'VND - Vietnamese Dong', value: 'VND' },
							{ name: 'VUV - Vanuatu Vatu', value: 'VUV' },
							{ name: 'WST - Samoan Tala', value: 'WST' },
							{ name: 'XAF - CFA Franc BEAC', value: 'XAF' },
							{ name: 'XCD - East Caribbean Dollar', value: 'XCD' },
							{ name: 'XOF - CFA Franc BCEAO', value: 'XOF' },
							{ name: 'XPF - CFP Franc', value: 'XPF' },
							{ name: 'YER - Yemeni Rial', value: 'YER' },
							{ name: 'ZAR - South African Rand', value: 'ZAR' },
							{ name: 'ZMW - Zambian Kwacha', value: 'ZMW' },
							{ name: 'ZWL - Zimbabwean Dollar', value: 'ZWL' },
						],
						default: 'USD'
					},
				],
			},
			{
				displayName: 'Invoice Currency', name: 'currency', type: 'options',
				options: [
					{ name: 'AED - UAE Dirham', value: 'AED' },
					{ name: 'AFN - Afghan Afghani', value: 'AFN' },
					{ name: 'ALL - Albanian Lek', value: 'ALL' },
					{ name: 'AMD - Armenian Dram', value: 'AMD' },
					{ name: 'ANG - Netherlands Antillean Guilder', value: 'ANG' },
					{ name: 'AOA - Angolan Kwanza', value: 'AOA' },
					{ name: 'ARS - Argentine Peso', value: 'ARS' },
					{ name: 'AUD - Australian Dollar', value: 'AUD' },
					{ name: 'AWG - Aruban Florin', value: 'AWG' },
					{ name: 'AZN - Azerbaijani Manat', value: 'AZN' },
					{ name: 'BAM - Bosnia and Herzegovina Convertible Mark', value: 'BAM' },
					{ name: 'BBD - Barbadian Dollar', value: 'BBD' },
					{ name: 'BDT - Bangladeshi Taka', value: 'BDT' },
					{ name: 'BGN - Bulgarian Lev', value: 'BGN' },
					{ name: 'BHD - Bahraini Dinar', value: 'BHD' },
					{ name: 'BIF - Burundian Franc', value: 'BIF' },
					{ name: 'BMD - Bermudian Dollar', value: 'BMD' },
					{ name: 'BND - Brunei Dollar', value: 'BND' },
					{ name: 'BOB - Bolivian Boliviano', value: 'BOB' },
					{ name: 'BRL - Brazilian Real', value: 'BRL' },
					{ name: 'BSD - Bahamian Dollar', value: 'BSD' },
					{ name: 'BTN - Bhutanese Ngultrum', value: 'BTN' },
					{ name: 'BWP - Botswana Pula', value: 'BWP' },
					{ name: 'BYN - Belarusian Ruble', value: 'BYN' },
					{ name: 'BZD - Belize Dollar', value: 'BZD' },
					{ name: 'CAD - Canadian Dollar', value: 'CAD' },
					{ name: 'CDF - Congolese Franc', value: 'CDF' },
					{ name: 'CHF - Swiss Franc', value: 'CHF' },
					{ name: 'CLF - Unidad De Fomento', value: 'CLF' },
					{ name: 'CLP - Chilean Peso', value: 'CLP' },
					{ name: 'CNY - Chinese Yuan', value: 'CNY' },
					{ name: 'COP - Colombian Peso', value: 'COP' },
					{ name: 'CRC - Costa Rican Colon', value: 'CRC' },
					{ name: 'CUC - Cuban Convertible Peso', value: 'CUC' },
					{ name: 'CUP - Cuban Peso', value: 'CUP' },
					{ name: 'CVE - Cape Verdean Escudo', value: 'CVE' },
					{ name: 'CZK - Czech Koruna', value: 'CZK' },
					{ name: 'DJF - Djiboutian Franc', value: 'DJF' },
					{ name: 'DKK - Danish Krone', value: 'DKK' },
					{ name: 'DOP - Dominican Peso', value: 'DOP' },
					{ name: 'DZD - Algerian Dinar', value: 'DZD' },
					{ name: 'EGP - Egyptian Pound', value: 'EGP' },
					{ name: 'ERN - Eritrean Nakfa', value: 'ERN' },
					{ name: 'ETB - Ethiopian Birr', value: 'ETB' },
					{ name: 'EUR - Euro', value: 'EUR' },
					{ name: 'FJD - Fijian Dollar', value: 'FJD' },
					{ name: 'FKP - Falkland Islands Pound', value: 'FKP' },
					{ name: 'GBP - British Pound', value: 'GBP' },
					{ name: 'GEL - Georgian Lari', value: 'GEL' },
					{ name: 'GHS - Ghanaian Cedi', value: 'GHS' },
					{ name: 'GIP - Gibraltar Pound', value: 'GIP' },
					{ name: 'GMD - Gambian Dalasi', value: 'GMD' },
					{ name: 'GNF - Guinean Franc', value: 'GNF' },
					{ name: 'GTQ - Guatemalan Quetzal', value: 'GTQ' },
					{ name: 'GYD - Guyanese Dollar', value: 'GYD' },
					{ name: 'HKD - Hong Kong Dollar', value: 'HKD' },
					{ name: 'HNL - Honduran Lempira', value: 'HNL' },
					{ name: 'HRK - Croatian Kuna', value: 'HRK' },
					{ name: 'HTG - Haitian Gourde', value: 'HTG' },
					{ name: 'HUF - Hungarian Forint', value: 'HUF' },
					{ name: 'IDR - Indonesian Rupiah', value: 'IDR' },
					{ name: 'ILS - Israeli New Shekel', value: 'ILS' },
					{ name: 'INR - Indian Rupee', value: 'INR' },
					{ name: 'IQD - Iraqi Dinar', value: 'IQD' },
					{ name: 'IRR - Iranian Rial', value: 'IRR' },
					{ name: 'ISK - Icelandic Króna', value: 'ISK' },
					{ name: 'JMD - Jamaican Dollar', value: 'JMD' },
					{ name: 'JOD - Jordanian Dinar', value: 'JOD' },
					{ name: 'JPY - Japanese Yen', value: 'JPY' },
					{ name: 'KES - Kenyan Shilling', value: 'KES' },
					{ name: 'KGS - Kyrgyzstani Som', value: 'KGS' },
					{ name: 'KHR - Cambodian Riel', value: 'KHR' },
					{ name: 'KMF - Comorian Franc', value: 'KMF' },
					{ name: 'KPW - North Korean Won', value: 'KPW' },
					{ name: 'KRW - South Korean Won', value: 'KRW' },
					{ name: 'KWD - Kuwaiti Dinar', value: 'KWD' },
					{ name: 'KYD - Cayman Islands Dollar', value: 'KYD' },
					{ name: 'KZT - Kazakhstani Tenge', value: 'KZT' },
					{ name: 'LAK - Lao Kip', value: 'LAK' },
					{ name: 'LBP - Lebanese Pound', value: 'LBP' },
					{ name: 'LKR - Sri Lankan Rupee', value: 'LKR' },
					{ name: 'LRD - Liberian Dollar', value: 'LRD' },
					{ name: 'LSL - Lesotho Loti', value: 'LSL' },
					{ name: 'LYD - Libyan Dinar', value: 'LYD' },
					{ name: 'MAD - Moroccan Dirham', value: 'MAD' },
					{ name: 'MDL - Moldovan Leu', value: 'MDL' },
					{ name: 'MGA - Malagasy Ariary', value: 'MGA' },
					{ name: 'MKD - Macedonian Denar', value: 'MKD' },
					{ name: 'MMK - Myanmar Kyat', value: 'MMK' },
					{ name: 'MNT - Mongolian Tugrik', value: 'MNT' },
					{ name: 'MOP - Macanese Pataca', value: 'MOP' },
					{ name: 'MRU - Mauritanian Ouguiya', value: 'MRU' },
					{ name: 'MUR - Mauritian Rupee', value: 'MUR' },
					{ name: 'MVR - Maldivian Rufiyaa', value: 'MVR' },
					{ name: 'MWK - Malawian Kwacha', value: 'MWK' },
					{ name: 'MXN - Mexican Peso', value: 'MXN' },
					{ name: 'MYR - Malaysian Ringgit', value: 'MYR' },
					{ name: 'MZN - Mozambican Metical', value: 'MZN' },
					{ name: 'NAD - Namibian Dollar', value: 'NAD' },
					{ name: 'NGN - Nigerian Naira', value: 'NGN' },
					{ name: 'NIO - Nicaraguan Cordoba', value: 'NIO' },
					{ name: 'NOK - Norwegian Krone', value: 'NOK' },
					{ name: 'NPR - Nepalese Rupee', value: 'NPR' },
					{ name: 'NZD - New Zealand Dollar', value: 'NZD' },
					{ name: 'OMR - Omani Rial', value: 'OMR' },
					{ name: 'PAB - Panamanian Balboa', value: 'PAB' },
					{ name: 'PEN - Peruvian Sol', value: 'PEN' },
					{ name: 'PGK - Papua New Guinean Kina', value: 'PGK' },
					{ name: 'PHP - Philippine Peso', value: 'PHP' },
					{ name: 'PKR - Pakistani Rupee', value: 'PKR' },
					{ name: 'PLN - Polish Zloty', value: 'PLN' },
					{ name: 'PYG - Paraguayan Guarani', value: 'PYG' },
					{ name: 'QAR - Qatari Riyal', value: 'QAR' },
					{ name: 'RON - Romanian Leu', value: 'RON' },
					{ name: 'RSD - Serbian Dinar', value: 'RSD' },
					{ name: 'RUB - Russian Ruble', value: 'RUB' },
					{ name: 'RWF - Rwandan Franc', value: 'RWF' },
					{ name: 'SAR - Saudi Riyal', value: 'SAR' },
					{ name: 'SBD - Solomon Islands Dollar', value: 'SBD' },
					{ name: 'SCR - Seychellois Rupee', value: 'SCR' },
					{ name: 'SDG - Sudanese Pound', value: 'SDG' },
					{ name: 'SEK - Swedish Krona', value: 'SEK' },
					{ name: 'SGD - Singapore Dollar', value: 'SGD' },
					{ name: 'SHP - Saint Helena Pound', value: 'SHP' },
					{ name: 'SLL - Sierra Leonean Leone', value: 'SLL' },
					{ name: 'SOS - Somali Shilling', value: 'SOS' },
					{ name: 'SRD - Surinamese Dollar', value: 'SRD' },
					{ name: 'SSP - South Sudanese Pound', value: 'SSP' },
					{ name: 'STN - São Tomé and Príncipe Dobra', value: 'STN' },
					{ name: 'SVC - Salvadoran Colón', value: 'SVC' },
					{ name: 'SYP - Syrian Pound', value: 'SYP' },
					{ name: 'SZL - Swazi Lilangeni', value: 'SZL' },
					{ name: 'THB - Thai Baht', value: 'THB' },
					{ name: 'TJS - Tajikistani Somoni', value: 'TJS' },
					{ name: 'TMT - Turkmenistani Manat', value: 'TMT' },
					{ name: 'TND - Tunisian Dinar', value: 'TND' },
					{ name: 'TOP - Tongan Paʻanga', value: 'TOP' },
					{ name: 'TRY - Turkish Lira', value: 'TRY' },
					{ name: 'TTD - Trinidad and Tobago Dollar', value: 'TTD' },
					{ name: 'TWD - Taiwan Dollar', value: 'TWD' },
					{ name: 'TZS - Tanzanian Shilling', value: 'TZS' },
					{ name: 'UAH - Ukrainian Hryvnia', value: 'UAH' },
					{ name: 'UGX - Ugandan Shilling', value: 'UGX' },
					{ name: 'USD - US Dollar', value: 'USD' },
					{ name: 'UYU - Uruguayan Peso', value: 'UYU' },
					{ name: 'UZS - Uzbekistani Som', value: 'UZS' },
					{ name: 'VES - Venezuelan Bolivar', value: 'VES' },
					{ name: 'VND - Vietnamese Dong', value: 'VND' },
					{ name: 'VUV - Vanuatu Vatu', value: 'VUV' },
					{ name: 'WST - Samoan Tala', value: 'WST' },
					{ name: 'XAF - CFA Franc BEAC', value: 'XAF' },
					{ name: 'XCD - East Caribbean Dollar', value: 'XCD' },
					{ name: 'XOF - CFA Franc BCEAO', value: 'XOF' },
					{ name: 'XPF - CFP Franc', value: 'XPF' },
					{ name: 'YER - Yemeni Rial', value: 'YER' },
					{ name: 'ZAR - South African Rand', value: 'ZAR' },
					{ name: 'ZMW - Zambian Kwacha', value: 'ZMW' },
					{ name: 'ZWL - Zimbabwean Dollar', value: 'ZWL' },
				],
				default: 'INR'
			},
			{
				displayName: 'Reverse Charge',
				name: 'reverse_charge',
				type: 'options',
				options: [
					{ name: 'Yes', value: 1 },
					{ name: 'No', value: 0 },
				],
				default: 0,
			},
			{
				displayName: 'Terms and Conditions',
				name: 'terms_conditions',
				type: 'string',
				default: '',
			},
		],
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
			},
		},
	},
  {
		displayName: 'Specialized Supply',
		name: 'specialized_supply',
		type: 'options',
		options: [
			{ name: 'Not Applicable', value: '0' },
			{ name: 'Import', value: '1' },
			{ name: 'Input Service Distribution', value: '2' },
			{ name: 'Composition Taxable Person', value: '3' },
		],
		default: '0',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
			},
		},
	},
	{
		displayName: 'Export Bill Number',
		name: 'export_bill_no',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
				specialized_supply: ['1'],
			},
		},
	},
	{
		displayName: 'Export Bill Date',
		name: 'export_bill_date',
		type: 'dateTime',
		typeOptions: { dateOnly: true, showTime: false },
		default: '',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
				specialized_supply: ['1'],
			},
		},
	},
	{
		displayName: 'Export Port Code',
		name: 'export_port_code',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createPurchaseInvoice'],
				specialized_supply: ['1'],
			},
		},
	},


	// Voucher Creation
	{
		displayName: 'Voucher Type',
		name: 'voucher_type',
		type: 'options',
		options: [
			{ name: 'Payment Voucher', value: '2' },
			{ name: 'Expense Voucher', value: '1' },
			{ name: 'Salary Voucher', value: '3' },
		],
		default: '1',
		required: true,
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher', 'listVouchers'],
			},
		},
	},
	{
		displayName: 'Branch ID',
		name: 'branch_id',
		type: 'string',
		required: true,
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
			},
		},
		default: '',
	},
	{
		displayName: 'Payment Date',
		name: 'payment_date',
		type: 'dateTime',
		typeOptions: { dateOnly: true, showTime: false },
		default: '',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
			},
		},
	},
	{
		displayName: 'Currency', name: 'currency', type: 'options',
		options: [
			{ name: 'AED - UAE Dirham', value: 'AED' },
			{ name: 'AFN - Afghan Afghani', value: 'AFN' },
			{ name: 'ALL - Albanian Lek', value: 'ALL' },
			{ name: 'AMD - Armenian Dram', value: 'AMD' },
			{ name: 'ANG - Netherlands Antillean Guilder', value: 'ANG' },
			{ name: 'AOA - Angolan Kwanza', value: 'AOA' },
			{ name: 'ARS - Argentine Peso', value: 'ARS' },
			{ name: 'AUD - Australian Dollar', value: 'AUD' },
			{ name: 'AWG - Aruban Florin', value: 'AWG' },
			{ name: 'AZN - Azerbaijani Manat', value: 'AZN' },
			{ name: 'BAM - Bosnia and Herzegovina Convertible Mark', value: 'BAM' },
			{ name: 'BBD - Barbadian Dollar', value: 'BBD' },
			{ name: 'BDT - Bangladeshi Taka', value: 'BDT' },
			{ name: 'BGN - Bulgarian Lev', value: 'BGN' },
			{ name: 'BHD - Bahraini Dinar', value: 'BHD' },
			{ name: 'BIF - Burundian Franc', value: 'BIF' },
			{ name: 'BMD - Bermudian Dollar', value: 'BMD' },
			{ name: 'BND - Brunei Dollar', value: 'BND' },
			{ name: 'BOB - Bolivian Boliviano', value: 'BOB' },
			{ name: 'BRL - Brazilian Real', value: 'BRL' },
			{ name: 'BSD - Bahamian Dollar', value: 'BSD' },
			{ name: 'BTN - Bhutanese Ngultrum', value: 'BTN' },
			{ name: 'BWP - Botswana Pula', value: 'BWP' },
			{ name: 'BYN - Belarusian Ruble', value: 'BYN' },
			{ name: 'BZD - Belize Dollar', value: 'BZD' },
			{ name: 'CAD - Canadian Dollar', value: 'CAD' },
			{ name: 'CDF - Congolese Franc', value: 'CDF' },
			{ name: 'CHF - Swiss Franc', value: 'CHF' },
			{ name: 'CLF - Unidad De Fomento', value: 'CLF' },
			{ name: 'CLP - Chilean Peso', value: 'CLP' },
			{ name: 'CNY - Chinese Yuan', value: 'CNY' },
			{ name: 'COP - Colombian Peso', value: 'COP' },
			{ name: 'CRC - Costa Rican Colon', value: 'CRC' },
			{ name: 'CUC - Cuban Convertible Peso', value: 'CUC' },
			{ name: 'CUP - Cuban Peso', value: 'CUP' },
			{ name: 'CVE - Cape Verdean Escudo', value: 'CVE' },
			{ name: 'CZK - Czech Koruna', value: 'CZK' },
			{ name: 'DJF - Djiboutian Franc', value: 'DJF' },
			{ name: 'DKK - Danish Krone', value: 'DKK' },
			{ name: 'DOP - Dominican Peso', value: 'DOP' },
			{ name: 'DZD - Algerian Dinar', value: 'DZD' },
			{ name: 'EGP - Egyptian Pound', value: 'EGP' },
			{ name: 'ERN - Eritrean Nakfa', value: 'ERN' },
			{ name: 'ETB - Ethiopian Birr', value: 'ETB' },
			{ name: 'EUR - Euro', value: 'EUR' },
			{ name: 'FJD - Fijian Dollar', value: 'FJD' },
			{ name: 'FKP - Falkland Islands Pound', value: 'FKP' },
			{ name: 'GBP - British Pound', value: 'GBP' },
			{ name: 'GEL - Georgian Lari', value: 'GEL' },
			{ name: 'GHS - Ghanaian Cedi', value: 'GHS' },
			{ name: 'GIP - Gibraltar Pound', value: 'GIP' },
			{ name: 'GMD - Gambian Dalasi', value: 'GMD' },
			{ name: 'GNF - Guinean Franc', value: 'GNF' },
			{ name: 'GTQ - Guatemalan Quetzal', value: 'GTQ' },
			{ name: 'GYD - Guyanese Dollar', value: 'GYD' },
			{ name: 'HKD - Hong Kong Dollar', value: 'HKD' },
			{ name: 'HNL - Honduran Lempira', value: 'HNL' },
			{ name: 'HRK - Croatian Kuna', value: 'HRK' },
			{ name: 'HTG - Haitian Gourde', value: 'HTG' },
			{ name: 'HUF - Hungarian Forint', value: 'HUF' },
			{ name: 'IDR - Indonesian Rupiah', value: 'IDR' },
			{ name: 'ILS - Israeli New Shekel', value: 'ILS' },
			{ name: 'INR - Indian Rupee', value: 'INR' },
			{ name: 'IQD - Iraqi Dinar', value: 'IQD' },
			{ name: 'IRR - Iranian Rial', value: 'IRR' },
			{ name: 'ISK - Icelandic Króna', value: 'ISK' },
			{ name: 'JMD - Jamaican Dollar', value: 'JMD' },
			{ name: 'JOD - Jordanian Dinar', value: 'JOD' },
			{ name: 'JPY - Japanese Yen', value: 'JPY' },
			{ name: 'KES - Kenyan Shilling', value: 'KES' },
			{ name: 'KGS - Kyrgyzstani Som', value: 'KGS' },
			{ name: 'KHR - Cambodian Riel', value: 'KHR' },
			{ name: 'KMF - Comorian Franc', value: 'KMF' },
			{ name: 'KPW - North Korean Won', value: 'KPW' },
			{ name: 'KRW - South Korean Won', value: 'KRW' },
			{ name: 'KWD - Kuwaiti Dinar', value: 'KWD' },
			{ name: 'KYD - Cayman Islands Dollar', value: 'KYD' },
			{ name: 'KZT - Kazakhstani Tenge', value: 'KZT' },
			{ name: 'LAK - Lao Kip', value: 'LAK' },
			{ name: 'LBP - Lebanese Pound', value: 'LBP' },
			{ name: 'LKR - Sri Lankan Rupee', value: 'LKR' },
			{ name: 'LRD - Liberian Dollar', value: 'LRD' },
			{ name: 'LSL - Lesotho Loti', value: 'LSL' },
			{ name: 'LYD - Libyan Dinar', value: 'LYD' },
			{ name: 'MAD - Moroccan Dirham', value: 'MAD' },
			{ name: 'MDL - Moldovan Leu', value: 'MDL' },
			{ name: 'MGA - Malagasy Ariary', value: 'MGA' },
			{ name: 'MKD - Macedonian Denar', value: 'MKD' },
			{ name: 'MMK - Myanmar Kyat', value: 'MMK' },
			{ name: 'MNT - Mongolian Tugrik', value: 'MNT' },
			{ name: 'MOP - Macanese Pataca', value: 'MOP' },
			{ name: 'MRU - Mauritanian Ouguiya', value: 'MRU' },
			{ name: 'MUR - Mauritian Rupee', value: 'MUR' },
			{ name: 'MVR - Maldivian Rufiyaa', value: 'MVR' },
			{ name: 'MWK - Malawian Kwacha', value: 'MWK' },
			{ name: 'MXN - Mexican Peso', value: 'MXN' },
			{ name: 'MYR - Malaysian Ringgit', value: 'MYR' },
			{ name: 'MZN - Mozambican Metical', value: 'MZN' },
			{ name: 'NAD - Namibian Dollar', value: 'NAD' },
			{ name: 'NGN - Nigerian Naira', value: 'NGN' },
			{ name: 'NIO - Nicaraguan Cordoba', value: 'NIO' },
			{ name: 'NOK - Norwegian Krone', value: 'NOK' },
			{ name: 'NPR - Nepalese Rupee', value: 'NPR' },
			{ name: 'NZD - New Zealand Dollar', value: 'NZD' },
			{ name: 'OMR - Omani Rial', value: 'OMR' },
			{ name: 'PAB - Panamanian Balboa', value: 'PAB' },
			{ name: 'PEN - Peruvian Sol', value: 'PEN' },
			{ name: 'PGK - Papua New Guinean Kina', value: 'PGK' },
			{ name: 'PHP - Philippine Peso', value: 'PHP' },
			{ name: 'PKR - Pakistani Rupee', value: 'PKR' },
			{ name: 'PLN - Polish Zloty', value: 'PLN' },
			{ name: 'PYG - Paraguayan Guarani', value: 'PYG' },
			{ name: 'QAR - Qatari Riyal', value: 'QAR' },
			{ name: 'RON - Romanian Leu', value: 'RON' },
			{ name: 'RSD - Serbian Dinar', value: 'RSD' },
			{ name: 'RUB - Russian Ruble', value: 'RUB' },
			{ name: 'RWF - Rwandan Franc', value: 'RWF' },
			{ name: 'SAR - Saudi Riyal', value: 'SAR' },
			{ name: 'SBD - Solomon Islands Dollar', value: 'SBD' },
			{ name: 'SCR - Seychellois Rupee', value: 'SCR' },
			{ name: 'SDG - Sudanese Pound', value: 'SDG' },
			{ name: 'SEK - Swedish Krona', value: 'SEK' },
			{ name: 'SGD - Singapore Dollar', value: 'SGD' },
			{ name: 'SHP - Saint Helena Pound', value: 'SHP' },
			{ name: 'SLL - Sierra Leonean Leone', value: 'SLL' },
			{ name: 'SOS - Somali Shilling', value: 'SOS' },
			{ name: 'SRD - Surinamese Dollar', value: 'SRD' },
			{ name: 'SSP - South Sudanese Pound', value: 'SSP' },
			{ name: 'STN - São Tomé and Príncipe Dobra', value: 'STN' },
			{ name: 'SVC - Salvadoran Colón', value: 'SVC' },
			{ name: 'SYP - Syrian Pound', value: 'SYP' },
			{ name: 'SZL - Swazi Lilangeni', value: 'SZL' },
			{ name: 'THB - Thai Baht', value: 'THB' },
			{ name: 'TJS - Tajikistani Somoni', value: 'TJS' },
			{ name: 'TMT - Turkmenistani Manat', value: 'TMT' },
			{ name: 'TND - Tunisian Dinar', value: 'TND' },
			{ name: 'TOP - Tongan Paʻanga', value: 'TOP' },
			{ name: 'TRY - Turkish Lira', value: 'TRY' },
			{ name: 'TTD - Trinidad and Tobago Dollar', value: 'TTD' },
			{ name: 'TWD - Taiwan Dollar', value: 'TWD' },
			{ name: 'TZS - Tanzanian Shilling', value: 'TZS' },
			{ name: 'UAH - Ukrainian Hryvnia', value: 'UAH' },
			{ name: 'UGX - Ugandan Shilling', value: 'UGX' },
			{ name: 'USD - US Dollar', value: 'USD' },
			{ name: 'UYU - Uruguayan Peso', value: 'UYU' },
			{ name: 'UZS - Uzbekistani Som', value: 'UZS' },
			{ name: 'VES - Venezuelan Bolivar', value: 'VES' },
			{ name: 'VND - Vietnamese Dong', value: 'VND' },
			{ name: 'VUV - Vanuatu Vatu', value: 'VUV' },
			{ name: 'WST - Samoan Tala', value: 'WST' },
			{ name: 'XAF - CFA Franc BEAC', value: 'XAF' },
			{ name: 'XCD - East Caribbean Dollar', value: 'XCD' },
			{ name: 'XOF - CFA Franc BCEAO', value: 'XOF' },
			{ name: 'XPF - CFP Franc', value: 'XPF' },
			{ name: 'YER - Yemeni Rial', value: 'YER' },
			{ name: 'ZAR - South African Rand', value: 'ZAR' },
			{ name: 'ZMW - Zambian Kwacha', value: 'ZMW' },
			{ name: 'ZWL - Zimbabwean Dollar', value: 'ZWL' },
		],
		default: 'INR',
		required: true,
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
			},
		},
	},
	{
		displayName: 'Payment Method Name or ID',
		name: 'payment_mode',
		type: 'options',
		default: '',
		typeOptions: {
			loadOptionsMethod: 'getPaymentMethodsPurchase',
		},
		required: true,
		placeholder: 'Select Payment Method',
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
			},
		},
	},

	// Expense Voucher
	{
		displayName: 'Expense Type',
		name: 'expense_type',
		type: 'options',
		options: [
			{ name: 'Single Account', value: 'single' },
			{ name: 'Multiple Accounts', value: 'multiple' },
		],
		default: 'single',
		required: true,
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				voucher_type: ['1'],
			},
		},
	},

	//Expense Single Account
	{
		displayName: 'Account Name or ID',
		name: 'expense_head',
		type: 'options',
		typeOptions: {
			loadOptionsMethod: 'getCoaAccounts',
		},
		default: '',
		placeholder: 'Select Account Type',
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				expense_type: ['single'],
				voucher_type: ['1'],
			},
		},
	},
	{
		displayName: 'Amount',
		name: 'amount',
		type: 'number',
		default: 0,
		required: true,
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				expense_type: ['single'],
				voucher_type: ['1'],
			},
		},
	},

	//Expense Tax Rate
	{
		displayName: 'Tax Rate',
		name: 'tax_rate',
		type: 'options',
		options: [
			{ name: '0.1%', value: '0.1' },
			{ name: '0.25%', value: '0.25' },
			{ name: '0%', value: '0' },
			{ name: '1.5%', value: '1.5' },
			{ name: '1%', value: '1' },
			{ name: '12%', value: '12' },
			{ name: '18%', value: '18' },
			{ name: '28%', value: '28' },
			{ name: '3%', value: '3' },
			{ name: '5%', value: '5' },
			{ name: '7.5%', value: '7.5' },
			{ name: 'Exempted Supply', value: 'Exempted Supply' },
			{ name: 'Nil-Rated', value: 'Nil-Rated' },
			{ name: 'Non-GST Supply', value: 'Non-GST Supply' },
			{ name: 'Zero-Rated', value: 'Zero-Rated' },
		],
		default: '5',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				expense_type: ['single'],
				voucher_type: ['1'],
			},
		},
	},

	//Expense Multiple Accounts
	{
    displayName: 'Multiple Accounts',
    name: 'multiple_accounts',
    type: 'fixedCollection',
    placeholder: 'Add Accounts',
    default: {},
    required: true,
    typeOptions: {
      multipleValues: true,
    },
    options: [
      {
        displayName: 'Account',
        name: 'expense_head',
        values: [
          {
						displayName: 'Account Name or ID', name: 'expense_head', type: 'options', typeOptions: {
							loadOptionsMethod: 'getCoaAccounts',
						},
						default: '',
						placeholder: 'Select Account Type',
						description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>'
					},
					{
						displayName: 'Amount',
						name: 'amount',
						type: 'number',
						default: 0,
					},
					{
						displayName: 'Tax',
						name: 'tax',
						type: 'options',
						options: [
              { name: '0.1%', value: '0.1' },
              { name: '0.25%', value: '0.25' },
              { name: '0%', value: '0' },
              { name: '1.5%', value: '1.5' },
              { name: '1%', value: '1' },
              { name: '12%', value: '12' },
              { name: '18%', value: '18' },
              { name: '28%', value: '28' },
              { name: '3%', value: '3' },
              { name: '5%', value: '5' },
              { name: '7.5%', value: '7.5' },
              { name: 'Exempted Supply', value: 'Exempted Supply' },
              { name: 'Nil-Rated', value: 'Nil-Rated' },
              { name: 'Non-GST Supply', value: 'Non-GST Supply' },
              { name: 'Zero-Rated', value: 'Zero-Rated' },
            ],
            default: '5',
					}
        ],
      },
    ],
    displayOptions: {
      show: {
        resource: ['purchase'],
        operation: ['createVoucher'],
        expense_type: ['multiple'],
				voucher_type: ['1'],
      },
    },
  },

	//Expense Additional Fields
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				expense_type: ['single', 'multiple'],
				voucher_type: ['1'],
			},
		},
		options: [

			{
				displayName: 'Contact ID',
				name: 'contact_id',
				type: 'string',
				default: '',
			},
			{
				displayName: 'Payment Status',
				name: 'payment_status',
				type: 'options',
				options: [
					{ name: 'Paid', value: 1 },
					{ name: 'Unpaid', value: 0 },
				],
				default: 0,
			},
			{
				displayName: 'Reverse Charge',
				name: 'reverse_charge',
				type: 'options',
				options: [
					{ name: 'Yes', value: 1 },
					{ name: 'No', value: 0 },
				],
				default: 0,
			},
			{
				displayName: 'Claim ITC',
				name: 'tax_credit_type',
				type: 'options',
				options: [
					{ name: 'Yes', value: 1 },
					{ name: 'No', value: 0 },
				],
				default: 0,
			},
		],
	},

	//Payment Voucher
	{
		displayName: 'Amount',
		name: 'amount',
		type: 'number',
		default: 0,
		required: true,
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				voucher_type: ['2'],
			},
		},
	},
	//Payment Contact ID
	{
		displayName: 'Contact ID',
		name: 'contact_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				voucher_type: ['2'],
			},
		},
	},

	//Payment Voucher Additional Fields
	{
		displayName: 'Additional Fields',
		name: 'additionalFields',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				voucher_type: ['2'],
			},
		},
		options: [
			{
				displayName: 'Reconcile Details',
				name: 'reconcile_details',
				type: 'fixedCollection',
				placeholder: 'Add Reconcile',
				default: {},
				typeOptions: {
					multipleValues: true,
				},
				options: [
					{
						displayName: 'Reconcile',
						name: 'reconcile',
						values: [
							{
								displayName: 'Purchase Invoice ID',
								name: 'purchase_invoice_id',
								type: 'string',
								default: '',
							},
							{
								displayName: 'Amount',
								name: 'amount',
								type: 'number',
								default: 0,
							},
						],
					},
				],
			},
		],
	},

	//Salary Voucher
	{
		displayName: 'Employee ID',
		name: 'employee_id',
		type: 'string',
		required: true,
		default: '',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				voucher_type: ['3'],
			},
		},
	},

	//Salary Account Name or ID
	{
		displayName: 'Account Name or ID',
		name: 'account_name',
		type: 'options',
		typeOptions: {
			loadOptionsMethod: 'getCoaAccounts',
		},
		default: '',
		required: true,
		placeholder: 'Select Account Type',
		description: 'Choose from the list, or specify an ID using an <a href="https://docs.n8n.io/code/expressions/">expression</a>',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				voucher_type: ['3'],
			},
		},
	},

	//Salary Month and Year
	{
		displayName: 'Salary Month/Year',
		name: 'salary_month',
		type: 'string',
		required: true,
		default: '',
		description: 'Enter the month and year for salary payment in MM-YYYY format',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				voucher_type: ['3'],
			},
		},
		placeholder: 'MM-YYYY',
	},

	//Salary Amount
	{
		displayName: 'Amount',
		name: 'amount',
		type: 'number',
		default: 0,
		required: true,
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				voucher_type: ['3'],
			},
		},
	},

	//Salary Additional Fields
	{
		displayName: 'Salary Details',
		name: 'salary_details',
		type: 'collection',
		placeholder: 'Add Salary',
		default: {},
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['createVoucher'],
				voucher_type: ['3'],
			},
		},
		options: [
			{
				displayName: 'Employee State Insurance',
				name: 'esi',
				type: 'string',
				placeholder: 'Add ESI',
				default: '',
			},
			{
				displayName: 'Employer Provident Fund',
				name: 'employer_pf',
				type: 'string',
				placeholder: 'Add Employer PF',
				default: '',
			},
			{
				displayName: 'Employer State Insurance',
				name: 'employer_esi',
				type: 'string',
				placeholder: 'Add Employer ESI',
				default: '',
			},
			{
				displayName: 'Professional Tax',
				name: 'pt',
				type: 'string',
				placeholder: 'Add PT',
				default: '',
			},
			{
				displayName: 'Provident Fund',
				name: 'pf',
				type: 'string',
				placeholder: 'Add PF',
				default: '',
			},
			{
				displayName: 'Tax Deducted at Source',
				name: 'tds',
				type: 'string',
				placeholder: 'Add TDS',
				default: '',
			},
			{
				displayName: 'Welfare Fund',
				name: 'welfare',
				type: 'string',
				placeholder: 'Add Welfare',
				default: '',
			},
		],
	},

	//List Operations
	{
    displayName: 'Limit',
    name: 'page_size',
    required: true,
    displayOptions: {
      show: {
        resource: ['purchase'],
        operation: ['listPurchaseInvoices', 'listVouchers'],
      },
    },
    type: 'number',
    default: 5,
  },
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['listPurchaseInvoices'],
			},
		},
		options: [
			{
				displayName: 'From Date', name: 'from_date', type: 'dateTime', typeOptions: { dateOnly: true, showTime: false },
				default: '',
			},
			{
				displayName: 'Order By', name: 'order_by', type: 'options', options: [
					{ name: 'Ascending', value: 'asc' },
					{ name: 'Descending', value: 'desc' },
				],
				default: 'asc',
			},
			{
				displayName: 'Order Column', name: 'order_column', type: 'options', options: [
					{ name: 'Bill Number', value: 'bill_number' },
					{ name: 'Purchase Invoice Date', value: 'pur_inv_date' },
					{ name: 'Purchase Invoice Number', value: 'purchase_number' },
					{ name: 'Seller Name', value: 'seller_name' },
					{ name: 'Total Amount', value: 'total_amount' },
				],
				default: 'purchase_number',
			},
			{
				displayName: 'Payment Status', name: 'payment_status', type: 'options', options: [
					{ name: 'Fully Paid', value: 'Fully Paid' },
					{ name: 'Part Paid', value: 'Part Paid' },
					{ name: 'Unpaid', value: 'Unpaid' },
				],
				default: 'Unpaid',
			},
			{
				displayName: 'To Date', name: 'to_date', type: 'dateTime', typeOptions: { dateOnly: true, showTime: false },
				default: '',
			},
		],
	},
	{
		displayName: 'Filters',
		name: 'filters',
		type: 'collection',
		placeholder: 'Add Field',
		default: {},
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['listVouchers'],
			},
		},
		options: [
			{
				displayName: 'From Date', name: 'from_date', type: 'dateTime', typeOptions: { dateOnly: true, showTime: false },
				default: '',
			},
			{
				displayName: 'To Date', name: 'to_date', type: 'dateTime', typeOptions: { dateOnly: true, showTime: false },
				default: '',
			},
			{
				displayName: 'Order By', name: 'order_by', type: 'options', options: [
					{ name: 'Ascending', value: 'asc' },
					{ name: 'Descending', value: 'desc' },
				],
				default: 'asc',
			},
			{
				displayName: 'Order Column', name: 'order_column', type: 'options', options: [
					{ name: 'Voucher Number', value: 'voucher_number' },
					{ name: 'Seller Name', value: 'seller_name' },
					{ name: 'Payment Date', value: 'payment_date' },
					{ name: 'Amount', value: 'amount' },
				],
				default: 'voucher_number',
			},
		],
	},
	// {
	// 	displayName: 'Filters',
	// 	name: 'filters',
	// 	type: 'collection',
	// 	placeholder: 'Add Field',
	// 	default: {},
	// 	displayOptions: {
	// 		show: {
	// 			resource: ['purchase'],
	// 			operation: ['listPurchaseOrders'],
	// 		},
	// 	},
	// 	options: [
	// 		{
	// 			displayName: 'Converted Status', name: 'converted_status', type: 'options', options: [
	// 				{ name: 'Converted', value: 'converted' },
	// 				{ name: 'Not Converted', value: 'not_converted' },
	// 			],
	// 			default: 'not_converted',
	// 		},
	// 		{
	// 			displayName: 'From Date', name: 'from_date', type: 'dateTime', typeOptions: { dateOnly: true, showTime: false },
	// 			default: '',
	// 		},
	// 		{
	// 			displayName: 'To Date', name: 'to_date', type: 'dateTime', typeOptions: { dateOnly: true, showTime: false },
	// 			default: '',
	// 		},
	// 	],
	// },
	{
		displayName: 'ID',
		name: 'id',
		type: 'string',
		default: '',
		displayOptions: {
			show: {
				resource: ['purchase'],
				operation: ['viewPurchaseInvoice', 'viewVoucher'],
			},
		},
		required: true,
		description: 'The ID of the purchase invoice, voucher, or purchase order to retrieve',
	}
];
