import { INodeProperties } from 'n8n-workflow';

export const QuoteOperations: INodeProperties[] = [
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    displayOptions: {
      show: {
        resource: ['quote'],
      },
    },
    options: [
      {
        name: 'Create Quote',
        value: 'createQuote',
        action: 'Create a new quote',
      },
      {
        name: 'View Quote',
        value: 'viewQuote',
        action: 'View a quote',
      },
      {
        name: 'List Quotes',
        value: 'listQuotes',
        action: 'List all quotes',
      },
    ],
    default: 'createQuote',
  },
  {
    displayName: 'Contact',
    name: 'contact',
    type: 'collection',
    placeholder: 'Add Contact Field',
    default: {},
    required: true,
    options: [
      {
        displayName: 'Business Country',
        name: 'business_country',
        type: 'options',
        options: [
          { name: 'INDIA', value: 'INDIA' },
          { name: 'UAE', value: 'UAE' },
        ],
        default: 'INDIA',
      },
      { displayName: 'Business Name', name: 'business_name', type: 'string', default: '' },
      { displayName: 'Contact ID', name: 'id', type: 'string', default: '' },
      { displayName: 'Contact Name', name: 'name', type: 'string', default: '' },
      { displayName: 'Email', name: 'email', type: 'string', default: '', placeholder: 'name@email.com' },
      { displayName: 'GSTIN', name: 'gstin', type: 'string', default: '', placeholder: 'Enter GSTIN' },
      { displayName: 'Mobile', name: 'mobile', type: 'string', default: '' },
      {
        displayName: 'Mobile Country Code',
        name: 'country_code',
        type: 'options',
        options: [
					{ name: '🇦🇪 UAE (+971)', value: 971 },
					{ name: '🇮🇳 India (+91)', value: 91 },
					{ name: '🇺🇸 USA (+1)', value: 1 },
					{ name: '🇬🇧 UK (+44)', value: 44 },
					{ name: '🇸🇦 Saudi Arabia (+966)', value: 966 },
					{ name: '🇶🇦 Qatar (+974)', value: 974 },
					{ name: '🇰🇼 Kuwait (+965)', value: 965 },
					{ name: '🇧🇭 Bahrain (+973)', value: 973 },
					{ name: '🇴🇲 Oman (+968)', value: 968 },
					{ name: '🇯🇴 Jordan (+962)', value: 962 },
					{ name: '🇱🇧 Lebanon (+961)', value: 961 },
					{ name: '🇪🇬 Egypt (+20)', value: 20 },
					{ name: '🇲🇦 Morocco (+212)', value: 212 },
					{ name: '🇹🇳 Tunisia (+216)', value: 216 },
					{ name: '🇩🇿 Algeria (+213)', value: 213 },
					{ name: '🇱🇾 Libya (+218)', value: 218 },
					{ name: '🇸🇩 Sudan (+249)', value: 249 },
					{ name: '🇸🇾 Syria (+963)', value: 963 },
					{ name: '🇾🇪 Yemen (+967)', value: 967 },
					{ name: '🇮🇶 Iraq (+964)', value: 964 },
					{ name: '🇮🇷 Iran (+98)', value: 98 },
					{ name: '🇦🇫 Afghanistan (+93)', value: 93 },
					{ name: '🇵🇰 Pakistan (+92)', value: 92 },
					{ name: '🇧🇩 Bangladesh (+880)', value: 880 },
					{ name: '🇱🇰 Sri Lanka (+94)', value: 94 },
					{ name: '🇳🇵 Nepal (+977)', value: 977 },
					{ name: '🇧🇹 Bhutan (+975)', value: 975 },
					{ name: '🇲🇲 Myanmar (+95)', value: 95 },
					{ name: '🇹🇭 Thailand (+66)', value: 66 },
					{ name: '🇻🇳 Vietnam (+84)', value: 84 },
					{ name: '🇰🇭 Cambodia (+855)', value: 855 },
					{ name: '🇱🇦 Laos (+856)', value: 856 },
					{ name: '🇲🇳 Mongolia (+976)', value: 976 },
					{ name: '🇨🇳 China (+86)', value: 86 },
					{ name: '🇯🇵 Japan (+81)', value: 81 },
					{ name: '🇰🇷 South Korea (+82)', value: 82 },
					{ name: '🇹🇼 Taiwan (+886)', value: 886 },
					{ name: '🇭🇰 Hong Kong (+852)', value: 852 },
					{ name: '🇸🇬 Singapore (+65)', value: 65 },
					{ name: '🇲🇾 Malaysia (+60)', value: 60 },
					{ name: '🇮🇩 Indonesia (+62)', value: 62 },
					{ name: '🇵🇭 Philippines (+63)', value: 63 },
					{ name: '🇧🇷 Brazil (+55)', value: 55 },
					{ name: '🇦🇷 Argentina (+54)', value: 54 },
					{ name: '🇨🇱 Chile (+56)', value: 56 },
					{ name: '🇨🇴 Colombia (+57)', value: 57 },
					{ name: '🇵🇪 Peru (+51)', value: 51 },
					{ name: '🇺🇾 Uruguay (+598)', value: 598 },
					{ name: '🇻🇪 Venezuela (+58)', value: 58 },
					{ name: '🇲🇽 Mexico (+52)', value: 52 },
					{ name: '🇨🇦 Canada (+1)', value: 1 },
					{ name: '🇦🇺 Australia (+61)', value: 61 },
					{ name: '🇳🇿 New Zealand (+64)', value: 64 },
					{ name: '🇿🇦 South Africa (+27)', value: 27 },
					{ name: '🇳🇬 Nigeria (+234)', value: 234 },
					{ name: '🇰🇪 Kenya (+254)', value: 254 },
					{ name: '🇬🇭 Ghana (+233)', value: 233 },
					{ name: '🇺🇬 Uganda (+256)', value: 256 },
					{ name: '🇹🇿 Tanzania (+255)', value: 255 },
					{ name: '🇪🇹 Ethiopia (+251)', value: 251 },
					{ name: '🇩🇪 Germany (+49)', value: 49 },
					{ name: '🇫🇷 France (+33)', value: 33 },
					{ name: '🇮🇹 Italy (+39)', value: 39 },
					{ name: '🇪🇸 Spain (+34)', value: 34 },
					{ name: '🇵🇱 Poland (+48)', value: 48 },
					{ name: '🇷🇺 Russia (+7)', value: 7 },
					{ name: '🇹🇷 Turkey (+90)', value: 90 },
					{ name: '🇳🇱 Netherlands (+31)', value: 31 },
					{ name: '🇧🇪 Belgium (+32)', value: 32 },
					{ name: '🇨🇭 Switzerland (+41)', value: 41 },
					{ name: '🇦🇹 Austria (+43)', value: 43 },
					{ name: '🇸🇪 Sweden (+46)', value: 46 },
					{ name: '🇳🇴 Norway (+47)', value: 47 },
					{ name: '🇩🇰 Denmark (+45)', value: 45 },
					{ name: '🇫🇮 Finland (+358)', value: 358 },
					{ name: '🇮🇸 Iceland (+354)', value: 354 },
					{ name: '🇮🇪 Ireland (+353)', value: 353 },
					{ name: '🇵🇹 Portugal (+351)', value: 351 },
					{ name: '🇬🇷 Greece (+30)', value: 30 },
					{ name: '🇭🇺 Hungary (+36)', value: 36 },
					{ name: '🇨🇿 Czech Republic (+420)', value: 420 },
					{ name: '🇸🇰 Slovakia (+421)', value: 421 },
					{ name: '🇸🇮 Slovenia (+386)', value: 386 },
					{ name: '🇭🇷 Croatia (+385)', value: 385 },
					{ name: '🇷🇸 Serbia (+381)', value: 381 },
					{ name: '🇧🇬 Bulgaria (+359)', value: 359 },
					{ name: '🇷🇴 Romania (+40)', value: 40 },
					{ name: '🇺🇦 Ukraine (+380)', value: 380 },
					{ name: '🇧🇾 Belarus (+375)', value: 375 },
					{ name: '🇱🇹 Lithuania (+370)', value: 370 },
					{ name: '🇱🇻 Latvia (+371)', value: 371 },
					{ name: '🇪🇪 Estonia (+372)', value: 372 },
					{ name: '🇲🇩 Moldova (+373)', value: 373 },
					{ name: '🇦🇲 Armenia (+374)', value: 374 },
					{ name: '🇬🇪 Georgia (+995)', value: 995 },
					{ name: '🇦🇿 Azerbaijan (+994)', value: 994 },
					{ name: '🇰🇿 Kazakhstan (+7)', value: 7 },
					{ name: '🇺🇿 Uzbekistan (+998)', value: 998 },
					{ name: '🇰🇬 Kyrgyzstan (+996)', value: 996 },
				],
        default: 91,
      },
      {
        displayName: 'Place of Supply',
        name: 'place_of_supply',
        type: 'options',
        options: [
          { value: 'ANDAMAN AND NICOBAR ISLANDS', name: 'ANDAMAN AND NICOBAR ISLANDS' },
          { value: 'ANDHRA PRADESH', name: 'ANDHRA PRADESH' },
          { value: 'ARUNACHAL PRADESH', name: 'ARUNACHAL PRADESH' },
          { value: 'ASSAM', name: 'ASSAM' },
          { value: 'BIHAR', name: 'BIHAR' },
          { value: 'CHANDIGARH', name: 'CHANDIGARH' },
          { value: 'CHHATTISGARH', name: 'CHHATTISGARH' },
          { value: 'DADRA AND NAGAR HAVELI', name: 'DADRA AND NAGAR HAVELI' },
          { value: 'DAMAN AND DIU', name: 'DAMAN AND DIU' },
          { value: 'DELHI', name: 'DELHI' },
          { value: 'GOA', name: 'GOA' },
          { value: 'GUJARAT', name: 'GUJARAT' },
          { value: 'HARYANA', name: 'HARYANA' },
          { value: 'HIMACHAL PRADESH', name: 'HIMACHAL PRADESH' },
          { value: 'INTERNATIONAL', name: 'INTERNATIONAL' },
          { value: 'JAMMU AND KASHMIR', name: 'JAMMU AND KASHMIR' },
          { value: 'JHARKHAND', name: 'JHARKHAND' },
          { value: 'KARNATAKA', name: 'KARNATAKA' },
          { value: 'KERALA', name: 'KERALA' },
          { value: 'LADAKH', name: 'LADAKH' },
          { value: 'LAKSHADWEEP', name: 'LAKSHADWEEP' },
          { value: 'MADHYA PRADESH', name: 'MADHYA PRADESH' },
          { value: 'MAHARASHTRA', name: 'MAHARASHTRA' },
          { value: 'MANIPUR', name: 'MANIPUR' },
          { value: 'MEGHALAYA', name: 'MEGHALAYA' },
          { value: 'MIZORAM', name: 'MIZORAM' },
          { value: 'NAGALAND', name: 'NAGALAND' },
          { value: 'ODISHA', name: 'ODISHA' },
          { value: 'OTHER TERRITORY', name: 'OTHER TERRITORY' },
          { value: 'PUDUCHERRY', name: 'PUDUCHERRY' },
          { value: 'PUNJAB', name: 'PUNJAB' },
          { value: 'RAJASTHAN', name: 'RAJASTHAN' },
          { value: 'SIKKIM', name: 'SIKKIM' },
          { value: 'TAMIL NADU', name: 'TAMIL NADU' },
          { value: 'TELANGANA', name: 'TELANGANA' },
          { value: 'TRIPURA', name: 'TRIPURA' },
          { value: 'UTTAR PRADESH', name: 'UTTAR PRADESH' },
          { value: 'UTTARAKHAND', name: 'UTTARAKHAND' },
          { value: 'WEST BENGAL', name: 'WEST BENGAL' }
        ],
        default: 'TAMIL NADU',
      },
    ],
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['createQuote'],
      },
    },
  },
  {
    displayName: 'Items',
    name: 'items',
    type: 'fixedCollection',
    placeholder: 'Add Item',
    default: {},
    required: true,
    typeOptions: {
      multipleValues: true,
    },
    options: [
      {
        displayName: 'Item',
        name: 'item',
        values: [
          { displayName: 'Description', name: 'description', type: 'string', default: '' },
          { displayName: 'Discount', name: 'discount', type: 'number', default: 0 },
          {
            displayName: 'GST Rate',
            name: 'gst_rate',
            type: 'options',
            options: [
              { name: '0.1%', value: '0.1' },
              { name: '0.25%', value: '0.25' },
              { name: '0%', value: '0' },
              { name: '1.5%', value: '1.5' },
              { name: '1%', value: '1' },
              { name: '12%', value: '12' },
              { name: '18%', value: '18' },
              { name: '28%', value: '28' },
              { name: '3%', value: '3' },
              { name: '5%', value: '5' },
              { name: '7.5%', value: '7.5' },
              { name: 'Exempted Supply', value: 'Exempted Supply' },
              { name: 'Nil-Rated', value: 'Nil-Rated' },
              { name: 'Non-GST Supply', value: 'Non-GST Supply' },
              { name: 'Zero-Rated', value: 'Zero-Rated' },
            ],
            default: '5',
          },
          { displayName: 'Item ID', name: 'pid', type: 'string', default: '' },
          { displayName: 'Item Name', name: 'name', type: 'string', default: '' },
          { displayName: 'Item Type', name: 'item_type', type: 'options', options: [
            { name: 'Goods', value: '1' },
            { name: 'Service', value: '2' },
          ], default: '1' },
          { displayName: 'Non Taxable Per Item', name: 'non_taxable_per_item', type: 'number', default: 0 },
          { displayName: 'Price Type', name: 'price_type', type: 'options', options: [
            { name: 'Inclusive of GST', value: 0 },
            { name: 'Exclusive of GST', value: 1 },
          ], default: 0 },
          { displayName: 'Quantity', name: 'quantity', type: 'number', default: 1 },
          { displayName: 'Rate', name: 'rate', type: 'number', default: 0 },
          { displayName: 'SAC/HSN Code', name: 'item_code', type: 'string', default: '' },
          { displayName: 'Taxable Per Item', name: 'taxable_per_item', type: 'number', default: 0 },
          {
            displayName: 'Units',
            name: 'units',
            type: 'options',
            options: [
              { name: 'BAG-BAGS', value: 'BAG-BAGS' },
              { name: 'BAL-BALE', value: 'BAL-BALE' },
              { name: 'BDL-BUNDLES', value: 'BDL-BUNDLES' },
              { name: 'BKL-BUCKLES', value: 'BKL-BUCKLES' },
              { name: 'BOU-BILLIONS OF UNITS', value: 'BOU-BILLIONS OF UNITS' },
              { name: 'BOX-BOX', value: 'BOX-BOX' },
              { name: 'BTL-BOTTLES', value: 'BTL-BOTTLES' },
              { name: 'BUN-BUNCHES', value: 'BUN-BUNCHES' },
              { name: 'CAN-CANS', value: 'CAN-CANS' },
              { name: 'CBM-CUBIC METERS', value: 'CBM-CUBIC METERS' },
              { name: 'CCM-CUBIC CENTIMETERS', value: 'CCM-CUBIC CENTIMETERS' },
              { name: 'CMC-CENTIMETERS', value: 'CMC-CENTIMETERS' },
              { name: 'CTN-CARTONS', value: 'CTN-CARTONS' },
              { name: 'DOZ-DOZENS', value: 'DOZ-DOZENS' },
              { name: 'DRM-DRUMS', value: 'DRM-DRUMS' },
              { name: 'GGK-GREAT GROSS', value: 'GGK-GREAT GROSS' },
              { name: 'GMS-GRAMMES', value: 'GMS-GRAMMES' },
              { name: 'GRS-GROSS', value: 'GRS-GROSS' },
              { name: 'GYD-GROSS YARDS', value: 'GYD-GROSS YARDS' },
              { name: 'KGS-KILOGRAMS', value: 'KGS-KILOGRAMS' },
              { name: 'KLR-KILOLITRE', value: 'KLR-KILOLITRE' },
              { name: 'KME-KILOMETRE', value: 'KME-KILOMETRE' },
              { name: 'LTR-LITRES', value: 'LTR-LITRES' },
              { name: 'MLS-MILLI LITRES', value: 'MLS-MILLI LITRES' },
              { name: 'MLT-MILILITRE', value: 'MLT-MILILITRE' },
              { name: 'MTR-METERS', value: 'MTR-METERS' },
              { name: 'MTS-METRIC TON', value: 'MTS-METRIC TON' },
              { name: 'NOS-NUMBERS', value: 'NOS-NUMBERS' },
              { name: 'OTH-OTHERS', value: 'OTH-OTHERS' },
              { name: 'PAC-PACKS', value: 'PAC-PACKS' },
              { name: 'PCS-PIECES', value: 'PCS-PIECES' },
              { name: 'PRS-PAIRS', value: 'PRS-PAIRS' },
              { name: 'QTL-QUINTAL', value: 'QTL-QUINTAL' },
              { name: 'ROL-ROLLS', value: 'ROL-ROLLS' },
              { name: 'SET-SETS', value: 'SET-SETS' },
              { name: 'SQF-SQUARE FEET', value: 'SQF-SQUARE FEET' },
              { name: 'SQM-SQUARE METERS', value: 'SQM-SQUARE METERS' },
              { name: 'SQY-SQUARE YARDS', value: 'SQY-SQUARE YARDS' },
              { name: 'TBS-TABLETS', value: 'TBS-TABLETS' },
              { name: 'TGM-TEN GROSS', value: 'TGM-TEN GROSS' },
              { name: 'THD-THOUSANDS', value: 'THD-THOUSANDS' },
              { name: 'TON-TONNES', value: 'TON-TONNES' },
              { name: 'TUB-TUBES', value: 'TUB-TUBES' },
              { name: 'UGS-US GALLONS', value: 'UGS-US GALLONS' },
              { name: 'UNT-UNITS', value: 'UNT-UNITS' },
              { name: 'YDS-YARDS', value: 'YDS-YARDS' }
            ],
            default: 'UNT-UNITS',
            placeholder: '',
          },
          { displayName: 'Variant ID', name: 'variant_id', type: 'string', default: '' },
        ],
      },
    ],
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['createQuote'],
      },
    },
  },
  {
    displayName: 'Seller Branch ID',
    name: 'seller_branch_id',
    type: 'string',
    default: '',
    required: true,
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['createQuote'],
      },
    },
  },
  {
    displayName: 'Additional Fields',
    name: 'additionalFields',
    type: 'collection',
    placeholder: 'Add Field',
    default: {},
    options: [

      {
        displayName: 'Additional Charges',
        name: 'additional_charges',
        type: 'fixedCollection',
        typeOptions: { multipleValues: true },
        default: {},
        options: [
          { displayName: 'Charge', name: 'charge', type: 'string', default: '' },
        ],
      },
      {
        displayName: 'Bank ID', name: 'bank_id', type: 'string', default: '' },
      {
        displayName: 'Billing Address',
        name: 'billing_address',
        type: 'collection',
        typeOptions: { multipleValues: false },
        default: {},
        options: [
          { displayName: 'Billing Address Line 1', name: 'bill_addr1', type: 'string', default: '' },
          { displayName: 'Billing Address Line 2', name: 'bill_addr2', type: 'string', default: '' },
          { displayName: 'Billing City', name: 'bill_city', type: 'string', default: '' },
          { displayName: 'Billing Country', name: 'bill_country', type: 'string', default: '' },
          { displayName: 'Billing GSTIN', name: 'bill_gstin', type: 'string', default: '' },
          { displayName: 'Billing Pincode', name: 'bill_pincode', type: 'string', default: '' },
          { displayName: 'Billing State', name: 'bill_state', type: 'string', default: '' },
        ],
      },
      {
        displayName: 'Billing Currency', name: 'billings_currency', type: 'options',
        options: [
					{ name: 'AED - UAE Dirham', value: 'AED' },
					{ name: 'AFN - Afghan Afghani', value: 'AFN' },
					{ name: 'ALL - Albanian Lek', value: 'ALL' },
					{ name: 'AMD - Armenian Dram', value: 'AMD' },
					{ name: 'ANG - Netherlands Antillean Guilder', value: 'ANG' },
					{ name: 'AOA - Angolan Kwanza', value: 'AOA' },
					{ name: 'ARS - Argentine Peso', value: 'ARS' },
					{ name: 'AUD - Australian Dollar', value: 'AUD' },
					{ name: 'AWG - Aruban Florin', value: 'AWG' },
					{ name: 'AZN - Azerbaijani Manat', value: 'AZN' },
					{ name: 'BAM - Bosnia and Herzegovina Convertible Mark', value: 'BAM' },
					{ name: 'BBD - Barbadian Dollar', value: 'BBD' },
					{ name: 'BDT - Bangladeshi Taka', value: 'BDT' },
					{ name: 'BGN - Bulgarian Lev', value: 'BGN' },
					{ name: 'BHD - Bahraini Dinar', value: 'BHD' },
					{ name: 'BIF - Burundian Franc', value: 'BIF' },
					{ name: 'BMD - Bermudian Dollar', value: 'BMD' },
					{ name: 'BND - Brunei Dollar', value: 'BND' },
					{ name: 'BOB - Bolivian Boliviano', value: 'BOB' },
					{ name: 'BRL - Brazilian Real', value: 'BRL' },
					{ name: 'BSD - Bahamian Dollar', value: 'BSD' },
					{ name: 'BTN - Bhutanese Ngultrum', value: 'BTN' },
					{ name: 'BWP - Botswana Pula', value: 'BWP' },
					{ name: 'BYN - Belarusian Ruble', value: 'BYN' },
					{ name: 'BZD - Belize Dollar', value: 'BZD' },
					{ name: 'CAD - Canadian Dollar', value: 'CAD' },
					{ name: 'CDF - Congolese Franc', value: 'CDF' },
					{ name: 'CHF - Swiss Franc', value: 'CHF' },
					{ name: 'CLF - Unidad De Fomento', value: 'CLF' },
					{ name: 'CLP - Chilean Peso', value: 'CLP' },
					{ name: 'CNY - Chinese Yuan', value: 'CNY' },
					{ name: 'COP - Colombian Peso', value: 'COP' },
					{ name: 'CRC - Costa Rican Colon', value: 'CRC' },
					{ name: 'CUC - Cuban Convertible Peso', value: 'CUC' },
					{ name: 'CUP - Cuban Peso', value: 'CUP' },
					{ name: 'CVE - Cape Verdean Escudo', value: 'CVE' },
					{ name: 'CZK - Czech Koruna', value: 'CZK' },
					{ name: 'DJF - Djiboutian Franc', value: 'DJF' },
					{ name: 'DKK - Danish Krone', value: 'DKK' },
					{ name: 'DOP - Dominican Peso', value: 'DOP' },
					{ name: 'DZD - Algerian Dinar', value: 'DZD' },
					{ name: 'EGP - Egyptian Pound', value: 'EGP' },
					{ name: 'ERN - Eritrean Nakfa', value: 'ERN' },
					{ name: 'ETB - Ethiopian Birr', value: 'ETB' },
					{ name: 'EUR - Euro', value: 'EUR' },
					{ name: 'FJD - Fijian Dollar', value: 'FJD' },
					{ name: 'FKP - Falkland Islands Pound', value: 'FKP' },
					{ name: 'GBP - British Pound', value: 'GBP' },
					{ name: 'GEL - Georgian Lari', value: 'GEL' },
					{ name: 'GHS - Ghanaian Cedi', value: 'GHS' },
					{ name: 'GIP - Gibraltar Pound', value: 'GIP' },
					{ name: 'GMD - Gambian Dalasi', value: 'GMD' },
					{ name: 'GNF - Guinean Franc', value: 'GNF' },
					{ name: 'GTQ - Guatemalan Quetzal', value: 'GTQ' },
					{ name: 'GYD - Guyanese Dollar', value: 'GYD' },
					{ name: 'HKD - Hong Kong Dollar', value: 'HKD' },
					{ name: 'HNL - Honduran Lempira', value: 'HNL' },
					{ name: 'HRK - Croatian Kuna', value: 'HRK' },
					{ name: 'HTG - Haitian Gourde', value: 'HTG' },
					{ name: 'HUF - Hungarian Forint', value: 'HUF' },
					{ name: 'IDR - Indonesian Rupiah', value: 'IDR' },
					{ name: 'ILS - Israeli New Shekel', value: 'ILS' },
					{ name: 'INR - Indian Rupee', value: 'INR' },
					{ name: 'IQD - Iraqi Dinar', value: 'IQD' },
					{ name: 'IRR - Iranian Rial', value: 'IRR' },
					{ name: 'ISK - Icelandic Króna', value: 'ISK' },
					{ name: 'JMD - Jamaican Dollar', value: 'JMD' },
					{ name: 'JOD - Jordanian Dinar', value: 'JOD' },
					{ name: 'JPY - Japanese Yen', value: 'JPY' },
					{ name: 'KES - Kenyan Shilling', value: 'KES' },
					{ name: 'KGS - Kyrgyzstani Som', value: 'KGS' },
					{ name: 'KHR - Cambodian Riel', value: 'KHR' },
					{ name: 'KMF - Comorian Franc', value: 'KMF' },
					{ name: 'KPW - North Korean Won', value: 'KPW' },
					{ name: 'KRW - South Korean Won', value: 'KRW' },
					{ name: 'KWD - Kuwaiti Dinar', value: 'KWD' },
					{ name: 'KYD - Cayman Islands Dollar', value: 'KYD' },
					{ name: 'KZT - Kazakhstani Tenge', value: 'KZT' },
					{ name: 'LAK - Lao Kip', value: 'LAK' },
					{ name: 'LBP - Lebanese Pound', value: 'LBP' },
					{ name: 'LKR - Sri Lankan Rupee', value: 'LKR' },
					{ name: 'LRD - Liberian Dollar', value: 'LRD' },
					{ name: 'LSL - Lesotho Loti', value: 'LSL' },
					{ name: 'LYD - Libyan Dinar', value: 'LYD' },
					{ name: 'MAD - Moroccan Dirham', value: 'MAD' },
					{ name: 'MDL - Moldovan Leu', value: 'MDL' },
					{ name: 'MGA - Malagasy Ariary', value: 'MGA' },
					{ name: 'MKD - Macedonian Denar', value: 'MKD' },
					{ name: 'MMK - Myanmar Kyat', value: 'MMK' },
					{ name: 'MNT - Mongolian Tugrik', value: 'MNT' },
					{ name: 'MOP - Macanese Pataca', value: 'MOP' },
					{ name: 'MRU - Mauritanian Ouguiya', value: 'MRU' },
					{ name: 'MUR - Mauritian Rupee', value: 'MUR' },
					{ name: 'MVR - Maldivian Rufiyaa', value: 'MVR' },
					{ name: 'MWK - Malawian Kwacha', value: 'MWK' },
					{ name: 'MXN - Mexican Peso', value: 'MXN' },
					{ name: 'MYR - Malaysian Ringgit', value: 'MYR' },
					{ name: 'MZN - Mozambican Metical', value: 'MZN' },
					{ name: 'NAD - Namibian Dollar', value: 'NAD' },
					{ name: 'NGN - Nigerian Naira', value: 'NGN' },
					{ name: 'NIO - Nicaraguan Cordoba', value: 'NIO' },
					{ name: 'NOK - Norwegian Krone', value: 'NOK' },
					{ name: 'NPR - Nepalese Rupee', value: 'NPR' },
					{ name: 'NZD - New Zealand Dollar', value: 'NZD' },
					{ name: 'OMR - Omani Rial', value: 'OMR' },
					{ name: 'PAB - Panamanian Balboa', value: 'PAB' },
					{ name: 'PEN - Peruvian Sol', value: 'PEN' },
					{ name: 'PGK - Papua New Guinean Kina', value: 'PGK' },
					{ name: 'PHP - Philippine Peso', value: 'PHP' },
					{ name: 'PKR - Pakistani Rupee', value: 'PKR' },
					{ name: 'PLN - Polish Zloty', value: 'PLN' },
					{ name: 'PYG - Paraguayan Guarani', value: 'PYG' },
					{ name: 'QAR - Qatari Riyal', value: 'QAR' },
					{ name: 'RON - Romanian Leu', value: 'RON' },
					{ name: 'RSD - Serbian Dinar', value: 'RSD' },
					{ name: 'RUB - Russian Ruble', value: 'RUB' },
					{ name: 'RWF - Rwandan Franc', value: 'RWF' },
					{ name: 'SAR - Saudi Riyal', value: 'SAR' },
					{ name: 'SBD - Solomon Islands Dollar', value: 'SBD' },
					{ name: 'SCR - Seychellois Rupee', value: 'SCR' },
					{ name: 'SDG - Sudanese Pound', value: 'SDG' },
					{ name: 'SEK - Swedish Krona', value: 'SEK' },
					{ name: 'SGD - Singapore Dollar', value: 'SGD' },
					{ name: 'SHP - Saint Helena Pound', value: 'SHP' },
					{ name: 'SLL - Sierra Leonean Leone', value: 'SLL' },
					{ name: 'SOS - Somali Shilling', value: 'SOS' },
					{ name: 'SRD - Surinamese Dollar', value: 'SRD' },
					{ name: 'SSP - South Sudanese Pound', value: 'SSP' },
					{ name: 'STN - São Tomé and Príncipe Dobra', value: 'STN' },
					{ name: 'SVC - Salvadoran Colón', value: 'SVC' },
					{ name: 'SYP - Syrian Pound', value: 'SYP' },
					{ name: 'SZL - Swazi Lilangeni', value: 'SZL' },
					{ name: 'THB - Thai Baht', value: 'THB' },
					{ name: 'TJS - Tajikistani Somoni', value: 'TJS' },
					{ name: 'TMT - Turkmenistani Manat', value: 'TMT' },
					{ name: 'TND - Tunisian Dinar', value: 'TND' },
					{ name: 'TOP - Tongan Paʻanga', value: 'TOP' },
					{ name: 'TRY - Turkish Lira', value: 'TRY' },
					{ name: 'TTD - Trinidad and Tobago Dollar', value: 'TTD' },
					{ name: 'TWD - Taiwan Dollar', value: 'TWD' },
					{ name: 'TZS - Tanzanian Shilling', value: 'TZS' },
					{ name: 'UAH - Ukrainian Hryvnia', value: 'UAH' },
					{ name: 'UGX - Ugandan Shilling', value: 'UGX' },
					{ name: 'USD - US Dollar', value: 'USD' },
					{ name: 'UYU - Uruguayan Peso', value: 'UYU' },
					{ name: 'UZS - Uzbekistani Som', value: 'UZS' },
					{ name: 'VES - Venezuelan Bolivar', value: 'VES' },
					{ name: 'VND - Vietnamese Dong', value: 'VND' },
					{ name: 'VUV - Vanuatu Vatu', value: 'VUV' },
					{ name: 'WST - Samoan Tala', value: 'WST' },
					{ name: 'XAF - CFA Franc BEAC', value: 'XAF' },
					{ name: 'XCD - East Caribbean Dollar', value: 'XCD' },
					{ name: 'XOF - CFA Franc BCEAO', value: 'XOF' },
					{ name: 'XPF - CFP Franc', value: 'XPF' },
					{ name: 'YER - Yemeni Rial', value: 'YER' },
					{ name: 'ZAR - South African Rand', value: 'ZAR' },
					{ name: 'ZMW - Zambian Kwacha', value: 'ZMW' },
					{ name: 'ZWL - Zimbabwean Dollar', value: 'ZWL' },
				],
        default: 'INR' },
      {
        displayName: 'Currency Info',
        name: 'currency_info',
        type: 'collection',
        default: {},
        options: [
          { displayName: 'Name', name: 'name', type: 'options',
            options: [
							{ name: 'AED - UAE Dirham', value: 'AED' },
							{ name: 'AFN - Afghan Afghani', value: 'AFN' },
							{ name: 'ALL - Albanian Lek', value: 'ALL' },
							{ name: 'AMD - Armenian Dram', value: 'AMD' },
							{ name: 'ANG - Netherlands Antillean Guilder', value: 'ANG' },
							{ name: 'AOA - Angolan Kwanza', value: 'AOA' },
							{ name: 'ARS - Argentine Peso', value: 'ARS' },
							{ name: 'AUD - Australian Dollar', value: 'AUD' },
							{ name: 'AWG - Aruban Florin', value: 'AWG' },
							{ name: 'AZN - Azerbaijani Manat', value: 'AZN' },
							{ name: 'BAM - Bosnia and Herzegovina Convertible Mark', value: 'BAM' },
							{ name: 'BBD - Barbadian Dollar', value: 'BBD' },
							{ name: 'BDT - Bangladeshi Taka', value: 'BDT' },
							{ name: 'BGN - Bulgarian Lev', value: 'BGN' },
							{ name: 'BHD - Bahraini Dinar', value: 'BHD' },
							{ name: 'BIF - Burundian Franc', value: 'BIF' },
							{ name: 'BMD - Bermudian Dollar', value: 'BMD' },
							{ name: 'BND - Brunei Dollar', value: 'BND' },
							{ name: 'BOB - Bolivian Boliviano', value: 'BOB' },
							{ name: 'BRL - Brazilian Real', value: 'BRL' },
							{ name: 'BSD - Bahamian Dollar', value: 'BSD' },
							{ name: 'BTN - Bhutanese Ngultrum', value: 'BTN' },
							{ name: 'BWP - Botswana Pula', value: 'BWP' },
							{ name: 'BYN - Belarusian Ruble', value: 'BYN' },
							{ name: 'BZD - Belize Dollar', value: 'BZD' },
							{ name: 'CAD - Canadian Dollar', value: 'CAD' },
							{ name: 'CDF - Congolese Franc', value: 'CDF' },
							{ name: 'CHF - Swiss Franc', value: 'CHF' },
							{ name: 'CLF - Unidad De Fomento', value: 'CLF' },
							{ name: 'CLP - Chilean Peso', value: 'CLP' },
							{ name: 'CNY - Chinese Yuan', value: 'CNY' },
							{ name: 'COP - Colombian Peso', value: 'COP' },
							{ name: 'CRC - Costa Rican Colon', value: 'CRC' },
							{ name: 'CUC - Cuban Convertible Peso', value: 'CUC' },
							{ name: 'CUP - Cuban Peso', value: 'CUP' },
							{ name: 'CVE - Cape Verdean Escudo', value: 'CVE' },
							{ name: 'CZK - Czech Koruna', value: 'CZK' },
							{ name: 'DJF - Djiboutian Franc', value: 'DJF' },
							{ name: 'DKK - Danish Krone', value: 'DKK' },
							{ name: 'DOP - Dominican Peso', value: 'DOP' },
							{ name: 'DZD - Algerian Dinar', value: 'DZD' },
							{ name: 'EGP - Egyptian Pound', value: 'EGP' },
							{ name: 'ERN - Eritrean Nakfa', value: 'ERN' },
							{ name: 'ETB - Ethiopian Birr', value: 'ETB' },
							{ name: 'EUR - Euro', value: 'EUR' },
							{ name: 'FJD - Fijian Dollar', value: 'FJD' },
							{ name: 'FKP - Falkland Islands Pound', value: 'FKP' },
							{ name: 'GBP - British Pound', value: 'GBP' },
							{ name: 'GEL - Georgian Lari', value: 'GEL' },
							{ name: 'GHS - Ghanaian Cedi', value: 'GHS' },
							{ name: 'GIP - Gibraltar Pound', value: 'GIP' },
							{ name: 'GMD - Gambian Dalasi', value: 'GMD' },
							{ name: 'GNF - Guinean Franc', value: 'GNF' },
							{ name: 'GTQ - Guatemalan Quetzal', value: 'GTQ' },
							{ name: 'GYD - Guyanese Dollar', value: 'GYD' },
							{ name: 'HKD - Hong Kong Dollar', value: 'HKD' },
							{ name: 'HNL - Honduran Lempira', value: 'HNL' },
							{ name: 'HRK - Croatian Kuna', value: 'HRK' },
							{ name: 'HTG - Haitian Gourde', value: 'HTG' },
							{ name: 'HUF - Hungarian Forint', value: 'HUF' },
							{ name: 'IDR - Indonesian Rupiah', value: 'IDR' },
							{ name: 'ILS - Israeli New Shekel', value: 'ILS' },
							{ name: 'INR - Indian Rupee', value: 'INR' },
							{ name: 'IQD - Iraqi Dinar', value: 'IQD' },
							{ name: 'IRR - Iranian Rial', value: 'IRR' },
							{ name: 'ISK - Icelandic Króna', value: 'ISK' },
							{ name: 'JMD - Jamaican Dollar', value: 'JMD' },
							{ name: 'JOD - Jordanian Dinar', value: 'JOD' },
							{ name: 'JPY - Japanese Yen', value: 'JPY' },
							{ name: 'KES - Kenyan Shilling', value: 'KES' },
							{ name: 'KGS - Kyrgyzstani Som', value: 'KGS' },
							{ name: 'KHR - Cambodian Riel', value: 'KHR' },
							{ name: 'KMF - Comorian Franc', value: 'KMF' },
							{ name: 'KPW - North Korean Won', value: 'KPW' },
							{ name: 'KRW - South Korean Won', value: 'KRW' },
							{ name: 'KWD - Kuwaiti Dinar', value: 'KWD' },
							{ name: 'KYD - Cayman Islands Dollar', value: 'KYD' },
							{ name: 'KZT - Kazakhstani Tenge', value: 'KZT' },
							{ name: 'LAK - Lao Kip', value: 'LAK' },
							{ name: 'LBP - Lebanese Pound', value: 'LBP' },
							{ name: 'LKR - Sri Lankan Rupee', value: 'LKR' },
							{ name: 'LRD - Liberian Dollar', value: 'LRD' },
							{ name: 'LSL - Lesotho Loti', value: 'LSL' },
							{ name: 'LYD - Libyan Dinar', value: 'LYD' },
							{ name: 'MAD - Moroccan Dirham', value: 'MAD' },
							{ name: 'MDL - Moldovan Leu', value: 'MDL' },
							{ name: 'MGA - Malagasy Ariary', value: 'MGA' },
							{ name: 'MKD - Macedonian Denar', value: 'MKD' },
							{ name: 'MMK - Myanmar Kyat', value: 'MMK' },
							{ name: 'MNT - Mongolian Tugrik', value: 'MNT' },
							{ name: 'MOP - Macanese Pataca', value: 'MOP' },
							{ name: 'MRU - Mauritanian Ouguiya', value: 'MRU' },
							{ name: 'MUR - Mauritian Rupee', value: 'MUR' },
							{ name: 'MVR - Maldivian Rufiyaa', value: 'MVR' },
							{ name: 'MWK - Malawian Kwacha', value: 'MWK' },
							{ name: 'MXN - Mexican Peso', value: 'MXN' },
							{ name: 'MYR - Malaysian Ringgit', value: 'MYR' },
							{ name: 'MZN - Mozambican Metical', value: 'MZN' },
							{ name: 'NAD - Namibian Dollar', value: 'NAD' },
							{ name: 'NGN - Nigerian Naira', value: 'NGN' },
							{ name: 'NIO - Nicaraguan Cordoba', value: 'NIO' },
							{ name: 'NOK - Norwegian Krone', value: 'NOK' },
							{ name: 'NPR - Nepalese Rupee', value: 'NPR' },
							{ name: 'NZD - New Zealand Dollar', value: 'NZD' },
							{ name: 'OMR - Omani Rial', value: 'OMR' },
							{ name: 'PAB - Panamanian Balboa', value: 'PAB' },
							{ name: 'PEN - Peruvian Sol', value: 'PEN' },
							{ name: 'PGK - Papua New Guinean Kina', value: 'PGK' },
							{ name: 'PHP - Philippine Peso', value: 'PHP' },
							{ name: 'PKR - Pakistani Rupee', value: 'PKR' },
							{ name: 'PLN - Polish Zloty', value: 'PLN' },
							{ name: 'PYG - Paraguayan Guarani', value: 'PYG' },
							{ name: 'QAR - Qatari Riyal', value: 'QAR' },
							{ name: 'RON - Romanian Leu', value: 'RON' },
							{ name: 'RSD - Serbian Dinar', value: 'RSD' },
							{ name: 'RUB - Russian Ruble', value: 'RUB' },
							{ name: 'RWF - Rwandan Franc', value: 'RWF' },
							{ name: 'SAR - Saudi Riyal', value: 'SAR' },
							{ name: 'SBD - Solomon Islands Dollar', value: 'SBD' },
							{ name: 'SCR - Seychellois Rupee', value: 'SCR' },
							{ name: 'SDG - Sudanese Pound', value: 'SDG' },
							{ name: 'SEK - Swedish Krona', value: 'SEK' },
							{ name: 'SGD - Singapore Dollar', value: 'SGD' },
							{ name: 'SHP - Saint Helena Pound', value: 'SHP' },
							{ name: 'SLL - Sierra Leonean Leone', value: 'SLL' },
							{ name: 'SOS - Somali Shilling', value: 'SOS' },
							{ name: 'SRD - Surinamese Dollar', value: 'SRD' },
							{ name: 'SSP - South Sudanese Pound', value: 'SSP' },
							{ name: 'STN - São Tomé and Príncipe Dobra', value: 'STN' },
							{ name: 'SVC - Salvadoran Colón', value: 'SVC' },
							{ name: 'SYP - Syrian Pound', value: 'SYP' },
							{ name: 'SZL - Swazi Lilangeni', value: 'SZL' },
							{ name: 'THB - Thai Baht', value: 'THB' },
							{ name: 'TJS - Tajikistani Somoni', value: 'TJS' },
							{ name: 'TMT - Turkmenistani Manat', value: 'TMT' },
							{ name: 'TND - Tunisian Dinar', value: 'TND' },
							{ name: 'TOP - Tongan Paʻanga', value: 'TOP' },
							{ name: 'TRY - Turkish Lira', value: 'TRY' },
							{ name: 'TTD - Trinidad and Tobago Dollar', value: 'TTD' },
							{ name: 'TWD - Taiwan Dollar', value: 'TWD' },
							{ name: 'TZS - Tanzanian Shilling', value: 'TZS' },
							{ name: 'UAH - Ukrainian Hryvnia', value: 'UAH' },
							{ name: 'UGX - Ugandan Shilling', value: 'UGX' },
							{ name: 'USD - US Dollar', value: 'USD' },
							{ name: 'UYU - Uruguayan Peso', value: 'UYU' },
							{ name: 'UZS - Uzbekistani Som', value: 'UZS' },
							{ name: 'VES - Venezuelan Bolivar', value: 'VES' },
							{ name: 'VND - Vietnamese Dong', value: 'VND' },
							{ name: 'VUV - Vanuatu Vatu', value: 'VUV' },
							{ name: 'WST - Samoan Tala', value: 'WST' },
							{ name: 'XAF - CFA Franc BEAC', value: 'XAF' },
							{ name: 'XCD - East Caribbean Dollar', value: 'XCD' },
							{ name: 'XOF - CFA Franc BCEAO', value: 'XOF' },
							{ name: 'XPF - CFP Franc', value: 'XPF' },
							{ name: 'YER - Yemeni Rial', value: 'YER' },
							{ name: 'ZAR - South African Rand', value: 'ZAR' },
							{ name: 'ZMW - Zambian Kwacha', value: 'ZMW' },
							{ name: 'ZWL - Zimbabwean Dollar', value: 'ZWL' },
						],
            default: 'INR' },
          { displayName: 'Exchange Time', name: 'exchange_time', type: 'string', default: '' },
          { displayName: 'Exchange Rate', name: 'exchange_rate', type: 'string', default: '' },
        ],
      },
              {
          displayName: 'Estimate Date', name: 'estimate_date', type: 'dateTime', typeOptions: { dateOnly: true, showTime: false }, default: '' },
      {
        displayName: 'Estimate Number', name: 'estimate_number', type: 'string', default: '' },
      {
        displayName: 'Notes', name: 'notes', type: 'string', default: '' },
      {
        displayName: 'Notification', name: 'notification', type: 'options', description: 'If you want Notification, select Yes', options: [
          { name: 'Yes', value: 'Yes' },
          { name: 'No', value: 'No' },
        ], default: 'Yes' },
      {
        displayName: 'Payment Link', name: 'payment_link', type: 'options', description: 'If you want Payment Link, select Yes', options: [
          { name: 'Yes', value: 'Yes' },
          { name: 'No', value: 'No' },
        ], default: 'Yes' },
      {
        displayName: 'Shipping Address',
        name: 'shipping_address',
        type: 'collection',
        typeOptions: { multipleValues: false },
        default: {},
        options: [
          { displayName: 'Shipping Address Line 1', name: 'ship_addr1', type: 'string', default: '' },
          { displayName: 'Shipping Address Line 2', name: 'ship_addr2', type: 'string', default: '' },
          { displayName: 'Shipping City', name: 'ship_city', type: 'string', default: '' },
          { displayName: 'Shipping Country', name: 'ship_country', type: 'string', default: '' },
          { displayName: 'Shipping GSTIN', name: 'ship_gstin', type: 'string', default: '' },
          { displayName: 'Shipping Pincode', name: 'ship_pincode', type: 'string', default: '' },
          { displayName: 'Shipping State', name: 'ship_state', type: 'string', default: '' },
        ],
      },
      {
        displayName: 'Terms Conditions', name: 'terms_conditions', type: 'string', default: 'This invoice is issued subject to the following terms and conditions. All goods and services provided herein are governed by the contractual agreement between the buyer and seller. The buyer agrees to inspect the goods upon delivery and must notify the seller of any discrepancies or defects within 7 days of receipt. No returns or exchanges will be entertained after this period unless otherwise agreed in writing. Payment must be made in full within the stipulated credit period as mentioned in the invoice; failure to comply may result in interest being charged on overdue accounts at the rate of 2% per month. Title to the goods shall remain with the seller until full payment has been received. The seller shall not be held liable for any indirect, incidental, or consequential damages arising out of or related to the sale, delivery, or use of the goods. Any claim or dispute must be raised within 15 days of invoice date. Delivery dates mentioned are estimated and not guaranteed; delays due to unforeseen circumstances will not entitle the buyer to any claim for damages. All prices are subject to applicable taxes, duties, or other governmental charges. In case of export sales, compliance with the import laws and regulations of the buyer`s country is the buyer`s responsibility. No changes, alterations, or amendments shall be binding unless agreed to in writing by both parties. The seller reserves the right to cancel or reject any order in case of non-availability of goods, typographical errors, or incorrect pricing. Any discounts or promotional offers are subject to terms and may be withdrawn without prior notice. The buyer shall ensure that the goods are used in accordance with applicable safety standards and regulations. Any legal disputes arising out of this transaction shall be subject to the exclusive jurisdiction of the courts at the seller`s principal place of business. Force majeure events including but not limited to strikes, floods, natural disasters, pandemics, or war may relieve the seller from their obligations during the period of disruption. Acceptance of this invoice implies acceptance of all the above terms and conditions.' },
			        {
          displayName: 'Validity Date', name: 'validity_date', type: 'dateTime', typeOptions: { dateOnly: true, showTime: false }, default: '' },
    ],
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['createQuote'],
      },
    },
  },
  {
    displayName: 'Quote ID',
    name: 'quoteId',
    required: true,
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['viewQuote'],
      },
    },
    type: 'string',
    default: '',
  },
  {
    displayName: 'Page Number',
    name: 'page_number',
    required: true,
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['listQuotes'],
      },
    },
    type: 'number',
    default: 1,
  },
  {
    displayName: 'Page Size',
    name: 'page_size',
    required: true,
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['listQuotes'],
      },
    },
    type: 'number',
    default: 5,
  },
  {
    displayName: 'Filters',
    name: 'filters',
    type: 'collection',
    placeholder: 'Add Field',
    default: {},
    options: [
      {
        displayName: 'Date Range',
        name: 'date_range',
        type: 'fixedCollection',
        typeOptions: { multipleValues: false },
        default: {},
        options: [
          { displayName: 'Date From', name: 'date_from', type: 'string', placeholder: 'YYYY-MM-DD', default: '' },
          { displayName: 'Date To', name: 'date_to', type: 'string', placeholder: 'YYYY-MM-DD', default: '' },
        ],
      },
    ],
    displayOptions: {
      show: {
        resource: ['quote'],
        operation: ['listQuotes'],
      },
    },
  }
];
